// Arabic — auth, dashboard, courses, navigation, messages
module.exports = {
    auth: {
        failed: 'بيانات الدخول هذه غير مطابقة لسجلاتنا.',
        password: 'كلمة المرور غير صحيحة.',
        throttle: 'محاولات دخول كثيرة جدًا. يرجى المحاولة بعد :seconds ثانية.',
        login: 'تسجيل الدخول', register: 'إنشاء حساب', logout: 'تسجيل الخروج',
        email: 'البريد الإلكتروني', password_label: 'كلمة المرور', confirm_password: 'تأكيد كلمة المرور',
        remember_me: 'تذكرني', forgot_password: 'نسيت كلمة المرور؟', reset_password: 'إعادة تعيين كلمة المرور',
        send_reset_link: 'إرسال رابط إعادة التعيين', name: 'الاسم الكامل',
        already_registered: 'لديك حساب بالفعل؟', no_account: 'ليس لديك حساب؟',
        verify_email: 'تأكيد البريد الإلكتروني',
        verify_notice: 'شكرًا لتسجيلك! قبل البدء، هل يمكنك تأكيد بريدك الإلكتروني؟',
        verify_sent: 'تم إرسال رابط تأكيد جديد إلى بريدك الإلكتروني.',
        verify_resend: 'إعادة إرسال رسالة التأكيد', country: 'البلد',
        trial_notice: 'ابدأ اليوم تجربتك المجانية لمدة :days يومًا. دون بطاقة ائتمان.',
        register_as: 'أنشئ حسابك المجاني', admin_login: 'دخول المشرفين',
        admin_only: 'هذه المنطقة مخصصة للمشرفين فقط.',
        welcome_back: 'مرحبًا بعودتك', sign_in_to_continue: 'سجّل الدخول لمتابعة التعلم',
        join_acadexxa: 'انضم إلى أكاديكسا', create_account: 'أنشئ حسابك المجاني', full_name: 'الاسم الكامل',
        have_account: 'لديك حساب بالفعل؟', register_here: 'سجّل الدخول هنا',
    },
    dashboard: {
        welcome: 'مرحبًا بعودتك', total_courses: 'الدورات', instructors: 'المدربون', my_courses: 'دوراتي',
        certificates: 'الشهادات', announcements: 'الإعلانات', quick_links: 'روابط سريعة', browse_courses: 'تصفح الدورات',
        edit_profile: 'تعديل الملف الشخصي', enrolled_courses: 'الدورات المسجل فيها', completed_courses: 'الدورات المكتملة',
        in_progress: 'قيد التقدم', trial_status: 'حالة التجربة', trial_active: 'نشطة — الأيام المتبقية: :days',
        trial_expired: 'منتهية', continue: 'متابعة', view_all: 'عرض الكل',
        no_courses: 'لم تسجل في أي دورة بعد.',
        no_certificates: 'لا توجد شهادات بعد. أكمل دورة للحصول على شهادة!',
        no_announcements: 'لا توجد إعلانات حاليًا.', download_certificate: 'تنزيل الشهادة', verify: 'تحقق',
        progress: 'التقدم', instructor_dashboard: 'لوحة المدرب', total_students: 'الطلاب',
        my_courses_count: 'دوراتي', published_courses: 'المنشورة', avg_rating: 'متوسط التقييم',
        recent_reviews: 'أحدث التقييمات', pending_review: 'بانتظار المراجعة', create_course: 'إنشاء دورة',
        view_courses: 'عرض دوراتي', earnings: 'الأرباح', students_enrolled: 'الطلاب المسجلون: :count',
    },
    courses: {
        by: 'بواسطة', featured: 'مميزة', latest: 'الأحدث', courses: 'الدورات', view_all: 'عرض الكل',
        view_course: 'عرض الدورة', newest: 'الأحدث', catalog: 'دليل الدورات', filters: 'عوامل التصفية',
        courses_found: 'دورة', explore_courses: 'استكشف الدورات', browse_by: 'تصفح حسب',
        category: 'الفئة', enroll: 'سجّل الآن', enrolled: 'مسجل', already_enrolled: 'أنت مسجل بالفعل.',
        free: 'مجاني', level: 'المستوى', duration: 'المدة', language: 'اللغة', students: 'الطلاب',
        rating: 'التقييم', reviews: 'التقييمات', curriculum: 'المنهج', what_you_learn: 'ما ستتعلمه',
        requirements: 'المتطلبات', description: 'الوصف', about_instructor: 'عن المدرب',
        related_courses: 'دورات ذات صلة', write_review: 'اكتب تقييمًا', your_review: 'تقييمك',
        submit_review: 'إرسال التقييم', filter: 'تصفية الدورات', sort_by: 'ترتيب حسب', sort_newest: 'الأحدث',
        sort_popular: 'الأكثر شعبية', sort_rating: 'الأعلى تقييمًا', all_categories: 'جميع الفئات',
        all_levels: 'جميع المستويات', free_only: 'المجانية فقط', price: 'السعر', module: 'الوحدة', lesson: 'الدرس',
        quiz: 'اختبار', assignment: 'واجب', video: 'فيديو', text: 'مقال', mark_complete: 'وضع علامة كمكتمل',
        completed: 'مكتمل', progress: 'التقدم', next_lesson: 'الدرس التالي', prev_lesson: 'الدرس السابق',
        course_completed: 'تهانينا! لقد أكملت هذه الدورة.', get_certificate: 'احصل على شهادتك',
        hours: 'ساعات', free_preview: 'معاينة مجانية', locked: 'مقفل — سجّل للوصول',
        no_video: 'لا يوجد فيديو لهذا الدرس.', submit_quiz: 'إرسال الاختبار',
        quiz_passed: 'نجحت في الاختبار! النتيجة: :score%', quiz_failed: 'لم تنجح في الاختبار. النتيجة: :score%. حاول مرة أخرى.',
        question: 'سؤال', your_score: 'نتيجتك السابقة', attempt_again: 'حاول مرة أخرى',
        comments: 'الأسئلة والأجوبة', add_comment: 'اطرح سؤالًا', reply: 'رد', post_comment: 'نشر',
        download_attachment: 'تنزيل المرفق', add_to_wishlist: 'أضف إلى المفضلة', remove_from_wishlist: 'إزالة من المفضلة',
        popular: 'الأكثر شعبية', top_rated: 'الأعلى تقييمًا', price_low: 'السعر: من الأقل إلى الأعلى',
        continue_learning: 'تابع التعلم', enroll_now: 'سجّل الآن', no_courses_found: 'لم يتم العثور على دورات.',
        student_reviews: 'تقييمات الطلاب', try_different_filters: 'جرّب تعديل عوامل التصفية أو كلمات البحث.',
    },
    navigation: {
        home: 'الرئيسية', courses: 'الدورات', categories: 'الفئات', my_courses: 'دوراتي', dashboard: 'لوحة التحكم',
        profile: 'الملف الشخصي', wishlist: 'المفضلة', certificates: 'الشهادات', subscription: 'الاشتراك',
        logout: 'تسجيل الخروج', login: 'تسجيل الدخول', register: 'إنشاء حساب', become_instructor: 'كن مدربًا',
        contact: 'اتصل بنا', about: 'من نحن', privacy: 'سياسة الخصوصية', terms: 'شروط الخدمة',
        admin_panel: 'لوحة الإدارة', instructor_portal: 'مساحة المدرب', search: 'بحث',
        quick_links: 'روابط سريعة', support: 'الدعم', contact_us: 'اتصل بنا', notifications: 'الإشعارات',
        no_notifications: 'لا توجد إشعارات جديدة', start_free: 'ابدأ مجانًا',
    },
    messages: {
        welcome: 'مرحبًا بك في أكاديكسا', learn_grow: 'تعلّم وتطوّر وحقّق أهدافك',
        hero_subtitle: 'انضم إلى آلاف المتعلمين في معهد ZTF الجامعي. احصل على دورات عالمية المستوى وشهادات، وطوّر مسيرتك المهنية.',
        get_started: 'ابدأ مجانًا', browse_courses: 'تصفح الدورات', featured_courses: 'دورات مميزة',
        latest_courses: 'أحدث الدورات', view_all: 'عرض الكل', categories: 'الفئات', why_acadexxa: 'لماذا تختار أكاديكسا؟',
        enroll_now: 'سجّل الآن', start_learning: 'ابدأ التعلم', continue_learning: 'تابع التعلم',
        free: 'مجاني', all_levels: 'جميع المستويات', beginner: 'مبتدئ', intermediate: 'متوسط', advanced: 'متقدم',
        students: 'طالب', courses: 'دورة', instructors: 'مدرب', certificates_issued: 'شهادة صادرة',
        trial_active: 'التجربة نشطة', trial_expires: 'تنتهي التجربة في :date',
        trial_expired: 'انتهت فترة تجربتك. اشترك لمتابعة التعلم.', upgrade: 'اشترك الآن',
        become_instructor: 'كن مدربًا', teach_world: 'علّم العالم', no_courses: 'لم يتم العثور على دورات.',
        contact_us: 'اتصل بنا', send_message: 'إرسال الرسالة', name: 'الاسم', email: 'البريد الإلكتروني', phone: 'الهاتف',
        subject: 'الموضوع', message: 'الرسالة', message_sent: 'تم إرسال رسالتك. سنرد عليك قريبًا.',
        search_placeholder: 'ابحث عن دورات أو مواضيع...', no_results: 'لا توجد نتائج لـ ":query"',
        certificate_verified: 'تم التحقق من الشهادة', certificate_not_found: 'الشهادة غير موجودة',
        verify_certificate: 'التحقق من شهادة', enter_code: 'أدخل رمز الشهادة',
        payment_coming_soon: 'الدفع والأرباح — قريبًا', contact_support: 'تواصل مع الدعم',
        language_changed: 'تم تغيير اللغة بنجاح.', profile_updated: 'تم تحديث الملف الشخصي بنجاح.',
        password_changed: 'تم تغيير كلمة المرور بنجاح.',
        account_deactivated: 'تم تعطيل حسابك. يرجى التواصل مع الدعم.',
        already_applied: 'لقد تقدمت بالفعل لتصبح مدربًا.', already_enrolled: 'أنت مسجل بالفعل في هذه الدورة.',
        application_submitted: 'تم إرسال طلبك. سنرد عليك قريبًا.',
        certificate_issued: 'تهانينا! لقد أكملت الدورة وشهادتك جاهزة.',
        comment_posted: 'تم نشر سؤالك.', contact_sent: 'تم إرسال رسالتك. سنرد عليك قريبًا.',
        course_deleted: 'تم حذف الدورة.', course_submitted: 'تم إرسال الدورة للمراجعة. سنبلغك بالقرار.',
        course_updated: 'تم تحديث الدورة.', enrolled_success: 'تم تسجيلك. تعلمًا ممتعًا!',
        quiz_failed: 'لم تنجح بعد. راجع الدرس وحاول مرة أخرى.', quiz_passed: 'أحسنت، لقد نجحت في الاختبار!',
        review_submitted: 'شكرًا على تقييمك.', wishlist_added: 'تمت الإضافة إلى المفضلة.', wishlist_removed: 'تمت الإزالة من المفضلة.',
        wrong_password: 'كلمة المرور الحالية غير صحيحة.',
    },
};
