// Arabic — security and validation groups
module.exports = {
    security: {
        '2fa_title': 'المصادقة الثنائية (2FA)',
        '2fa_intro': 'احمِ حساب المشرف: بالإضافة إلى كلمة المرور، سيُطلب رمز من 6 أرقام يولّده هاتفك.',
        '2fa_step1': 'ثبّت تطبيق مصادقة (Google Authenticator أو Microsoft Authenticator أو Authy…).',
        '2fa_step2': 'امسح رمز QR أدناه (أو اكتب المفتاح يدويًا).',
        '2fa_step3': 'أدخل الرمز الظاهر في التطبيق للتأكيد.',
        '2fa_active_since': 'المصادقة الثنائية مفعّلة منذ :date.',
        '2fa_disable_help': 'لإيقافها، أكّد بكلمة المرور ورمز من التطبيق.',
        '2fa_challenge_help': 'أدخل الرمز المكون من 6 أرقام الظاهر في تطبيق المصادقة.',
        manual_key: 'مفتاح للإدخال اليدوي', enable: 'تفعيل', disable: 'إيقاف', verify: 'تحقق', password: 'كلمة المرور',
        enabled: 'تم تفعيل المصادقة الثنائية.', disabled: 'تم إيقاف المصادقة الثنائية.',
        invalid_code: 'رمز غير صالح أو منتهي الصلاحية.', invalid_credentials: 'كلمة المرور أو الرمز غير صحيح.',
        reset_2fa: 'إعادة تعيين 2FA', confirm_reset_2fa: 'إعادة تعيين المصادقة الثنائية لهذا الحساب؟',
        reset_done: 'تمت إعادة تعيين المصادقة الثنائية.',
        use_admin_login: 'هذا الحساب يستخدم المصادقة الثنائية: سجّل الدخول من منطقة الإدارة.',
        my_security: 'أمان الحساب',
        banned: 'تم تعليق هذا الحساب. تواصل مع الدعم إذا كنت تعتقد أن ذلك خطأ.',
        banned_badge: 'محظور', banned_since: 'محظور منذ :date', ban_reason: 'السبب (اختياري)',
        confirm_ban: 'حظر هذا المستخدم؟ سيتم تسجيل خروجه فورًا.', unban: 'رفع الحظر',
        user_banned: 'تم حظر المستخدم وتسجيل خروجه.', user_unbanned: 'تم رفع الحظر.',
        cannot_edit_self: 'لا يمكنك تنفيذ هذا الإجراء على حسابك.',
        no_permission: 'ليست لديك صلاحية الوصول إلى هذا القسم من الإدارة.',
        role_permissions: 'الدور والصلاحيات', save_permissions: 'حفظ',
        permissions_help: 'للمشرف: الأقسام المسموح بها. عدم تحديد أي قسم = وصول كامل.',
        permissions_saved: 'تم حفظ الدور والصلاحيات.',
        perm_users: 'المستخدمون', perm_courses: 'الدورات', perm_categories: 'الفئات', perm_applications: 'الطلبات',
        perm_announcements: 'الإعلانات', perm_cms: 'الصفحات', perm_reviews: 'التقييمات', perm_certificates: 'الشهادات',
        perm_contacts: 'رسائل التواصل', perm_translations: 'الترجمات', perm_settings: 'الإعدادات',
        perm_logs: 'سجل النشاط', perm_reports: 'التقارير',
        platform: 'المنصة', allow_registration: 'التسجيل مفتوح',
        require_email_verification: 'اشتراط تأكيد البريد الإلكتروني',
        maintenance_mode: 'وضع الصيانة (المشرفون فقط يمكنهم الوصول إلى الموقع)',
        email_verification_help: 'لا تفعّل تأكيد البريد الإلكتروني إلا بعد أن يعمل إرسال البريد: مفتاح Brevo API محفوظ في خانة «البريد الإلكتروني» في هذه الصفحة.',
        registration_closed: 'التسجيل مغلق مؤقتًا.',
        reports: 'التقارير', total_students: 'الطلاب', active_30d: 'النشطون (30 يومًا)', total_enrollments: 'التسجيلات في الدورات',
        completion_rate: 'نسبة الإكمال', last_12_months: 'آخر 12 شهرًا', month: 'الشهر',
        registrations: 'طلاب جدد', enrollments: 'التسجيلات', completions: 'الدورات المكتملة', certificates: 'الشهادات',
        top_courses: 'الدورات الأكثر متابعة',
        export_users: 'المستخدمون (CSV)', export_enrollments: 'التسجيلات (CSV)', export_certificates: 'الشهادات (CSV)',
    },
    validation: {
        accepted: 'يجب قبول :attribute.',
        active_url: 'يجب أن يكون :attribute رابطًا صالحًا.',
        after: 'يجب أن يكون :attribute تاريخًا بعد :date.',
        after_or_equal: 'يجب أن يكون :attribute تاريخًا في :date أو بعده.',
        alpha: 'يجب أن يحتوي :attribute على حروف فقط.',
        alpha_dash: 'يجب أن يحتوي :attribute على حروف وأرقام وشرطات وشرطات سفلية فقط.',
        alpha_num: 'يجب أن يحتوي :attribute على حروف وأرقام فقط.',
        array: 'يجب أن يكون :attribute قائمة.',
        before: 'يجب أن يكون :attribute تاريخًا قبل :date.',
        before_or_equal: 'يجب أن يكون :attribute تاريخًا في :date أو قبله.',
        between: {
            array: 'يجب أن يحتوي :attribute على عدد عناصر بين :min و:max.',
            file: 'يجب أن يكون حجم :attribute بين :min و:max كيلوبايت.',
            numeric: 'يجب أن تكون قيمة :attribute بين :min و:max.',
            string: 'يجب أن يكون طول :attribute بين :min و:max حرفًا.',
        },
        boolean: 'يجب أن تكون قيمة :attribute نعم أو لا.',
        confirmed: 'تأكيد :attribute غير مطابق.',
        current_password: 'كلمة المرور غير صحيحة.',
        date: 'يجب أن يكون :attribute تاريخًا صالحًا.',
        date_format: 'يجب أن يطابق :attribute الصيغة :format.',
        different: 'يجب أن يختلف :attribute عن :other.',
        digits: 'يجب أن يتكون :attribute من :digits أرقام.',
        digits_between: 'يجب أن يتكون :attribute من :min إلى :max أرقام.',
        email: 'يجب أن يكون :attribute بريدًا إلكترونيًا صالحًا.',
        ends_with: 'يجب أن ينتهي :attribute بإحدى القيم التالية: :values.',
        enum: 'القيمة المختارة لـ :attribute غير صالحة.',
        exists: 'القيمة المختارة لـ :attribute غير صالحة.',
        extensions: 'يجب أن يكون امتداد :attribute أحد الامتدادات التالية: :values.',
        file: 'يجب أن يكون :attribute ملفًا.',
        filled: 'يجب أن يحتوي :attribute على قيمة.',
        gt: {
            array: 'يجب أن يحتوي :attribute على أكثر من :value عنصر.',
            file: 'يجب أن يكون حجم :attribute أكبر من :value كيلوبايت.',
            numeric: 'يجب أن تكون قيمة :attribute أكبر من :value.',
            string: 'يجب أن يكون طول :attribute أكثر من :value حرفًا.',
        },
        gte: {
            array: 'يجب أن يحتوي :attribute على :value عنصر أو أكثر.',
            file: 'يجب أن يكون حجم :attribute :value كيلوبايت على الأقل.',
            numeric: 'يجب أن تكون قيمة :attribute أكبر من :value أو تساويها.',
            string: 'يجب أن يكون طول :attribute :value حرفًا على الأقل.',
        },
        image: 'يجب أن يكون :attribute صورة.',
        in: 'القيمة المختارة لـ :attribute غير صالحة.',
        integer: 'يجب أن يكون :attribute عددًا صحيحًا.',
        ip: 'يجب أن يكون :attribute عنوان IP صالحًا.',
        json: 'يجب أن يكون :attribute نص JSON صالحًا.',
        lowercase: 'يجب أن يكون :attribute بأحرف صغيرة.',
        lt: {
            array: 'يجب أن يحتوي :attribute على أقل من :value عنصر.',
            file: 'يجب أن يكون حجم :attribute أقل من :value كيلوبايت.',
            numeric: 'يجب أن تكون قيمة :attribute أقل من :value.',
            string: 'يجب أن يكون طول :attribute أقل من :value حرفًا.',
        },
        lte: {
            array: 'يجب ألا يحتوي :attribute على أكثر من :value عنصر.',
            file: 'يجب ألا يتجاوز حجم :attribute :value كيلوبايت.',
            numeric: 'يجب أن تكون قيمة :attribute أقل من :value أو تساويها.',
            string: 'يجب ألا يتجاوز طول :attribute :value حرفًا.',
        },
        max: {
            array: 'يجب ألا يحتوي :attribute على أكثر من :max عنصر.',
            file: 'يجب ألا يتجاوز حجم :attribute :max كيلوبايت.',
            numeric: 'يجب ألا تتجاوز قيمة :attribute :max.',
            string: 'يجب ألا يتجاوز طول :attribute :max حرفًا.',
        },
        mimes: 'يجب أن يكون :attribute ملفًا من نوع: :values.',
        mimetypes: 'يجب أن يكون :attribute ملفًا من نوع: :values.',
        min: {
            array: 'يجب أن يحتوي :attribute على :min عنصر على الأقل.',
            file: 'يجب أن يكون حجم :attribute :min كيلوبايت على الأقل.',
            numeric: 'يجب أن تكون قيمة :attribute :min على الأقل.',
            string: 'يجب أن يكون طول :attribute :min حرفًا على الأقل.',
        },
        not_in: 'القيمة المختارة لـ :attribute غير صالحة.',
        numeric: 'يجب أن يكون :attribute رقمًا.',
        password: {
            letters: 'يجب أن يحتوي :attribute على حرف واحد على الأقل.',
            mixed: 'يجب أن يحتوي :attribute على حرف كبير وحرف صغير على الأقل.',
            numbers: 'يجب أن يحتوي :attribute على رقم واحد على الأقل.',
            symbols: 'يجب أن يحتوي :attribute على رمز واحد على الأقل.',
            uncompromised: 'ظهرت :attribute هذه في تسريب بيانات. يرجى اختيار أخرى.',
        },
        present: 'يجب أن يكون :attribute موجودًا.',
        prohibited: ':attribute غير مسموح به.',
        regex: 'صيغة :attribute غير صالحة.',
        required: 'حقل :attribute مطلوب.',
        required_if: 'حقل :attribute مطلوب عندما يكون :other هو :value.',
        required_with: 'حقل :attribute مطلوب عند وجود :values.',
        required_without: 'حقل :attribute مطلوب عند عدم وجود :values.',
        same: 'يجب أن يتطابق :attribute مع :other.',
        size: {
            array: 'يجب أن يحتوي :attribute على :size عنصر.',
            file: 'يجب أن يكون حجم :attribute :size كيلوبايت.',
            numeric: 'يجب أن تكون قيمة :attribute :size.',
            string: 'يجب أن يكون طول :attribute :size حرفًا.',
        },
        starts_with: 'يجب أن يبدأ :attribute بإحدى القيم التالية: :values.',
        string: 'يجب أن يكون :attribute نصًا.',
        timezone: 'يجب أن يكون :attribute منطقة زمنية صالحة.',
        unique: 'قيمة :attribute مستخدمة بالفعل.',
        uploaded: 'تعذر رفع :attribute.',
        uppercase: 'يجب أن يكون :attribute بأحرف كبيرة.',
        url: 'يجب أن يكون :attribute رابطًا صالحًا.',
        uuid: 'يجب أن يكون :attribute معرّف UUID صالحًا.',
        attributes: {
            name: 'الاسم', email: 'البريد الإلكتروني', password: 'كلمة المرور', password_confirmation: 'تأكيد كلمة المرور',
            current_password: 'كلمة المرور الحالية', country: 'البلد', bio: 'النبذة', title: 'العنوان',
            description: 'الوصف', content: 'المحتوى', body: 'الرسالة', subject: 'الموضوع', message: 'الرسالة',
            phone: 'الهاتف', category_id: 'الفئة', level: 'المستوى', language: 'اللغة', price: 'السعر',
            duration_hours: 'الساعات', duration_minutes: 'المدة', thumbnail: 'صورة الغلاف', file: 'الملف',
            rating: 'التقييم', comment: 'التعليق', score: 'الدرجة', feedback: 'الملاحظات', code: 'الرمز',
            slug: 'العنوان', audience: 'الجمهور', expertise: 'مجال الخبرة', credentials: 'المؤهلات',
            reason: 'السبب', days: 'عدد الأيام', question: 'السؤال', options: 'الخيارات', correct: 'الإجابة الصحيحة',
            youtube_url: 'رابط يوتيوب', vimeo_url: 'رابط Vimeo', external_url: 'رابط الفيديو', hero_image: 'الصورة',
        },
    },
};
