// Spanish — auth, dashboard, courses, navigation, messages
module.exports = {
    auth: {
        failed: 'Estas credenciales no coinciden con nuestros registros.',
        password: 'La contraseña es incorrecta.',
        throttle: 'Demasiados intentos. Inténtalo de nuevo en :seconds segundos.',
        login: 'Iniciar sesión', register: 'Registrarse', logout: 'Cerrar sesión',
        email: 'Correo electrónico', password_label: 'Contraseña', confirm_password: 'Confirmar contraseña',
        remember_me: 'Recordarme', forgot_password: '¿Olvidaste tu contraseña?', reset_password: 'Restablecer contraseña',
        send_reset_link: 'Enviar enlace de restablecimiento', name: 'Nombre completo',
        already_registered: '¿Ya tienes cuenta?', no_account: '¿No tienes cuenta?',
        verify_email: 'Verificar correo electrónico',
        verify_notice: '¡Gracias por registrarte! Antes de empezar, ¿puedes verificar tu correo electrónico?',
        verify_sent: 'Se ha enviado un nuevo enlace de verificación a tu correo.',
        verify_resend: 'Reenviar correo de verificación', country: 'País',
        trial_notice: 'Empieza hoy tu prueba gratuita de :days días. Sin tarjeta de crédito.',
        register_as: 'Crea tu cuenta gratuita', admin_login: 'Acceso de administrador',
        admin_only: 'Esta zona está reservada a los administradores.',
        welcome_back: 'Bienvenido de nuevo', sign_in_to_continue: 'Inicia sesión para seguir aprendiendo',
        join_acadexa: 'Únete a ACADEXA', create_account: 'Crea tu cuenta gratuita', full_name: 'Nombre completo',
        have_account: '¿Ya tienes una cuenta?', register_here: 'Inicia sesión aquí',
    },
    dashboard: {
        welcome: 'Bienvenido de nuevo', total_courses: 'Cursos', instructors: 'Instructores', my_courses: 'Mis cursos',
        certificates: 'Certificados', announcements: 'Anuncios', quick_links: 'Accesos rápidos', browse_courses: 'Explorar cursos',
        edit_profile: 'Editar perfil', enrolled_courses: 'Cursos inscritos', completed_courses: 'Cursos completados',
        in_progress: 'En curso', trial_status: 'Estado de la prueba', trial_active: 'Activa — quedan :days días',
        trial_expired: 'Vencida', continue: 'Continuar', view_all: 'Ver todo',
        no_courses: 'Aún no te has inscrito en ningún curso.',
        no_certificates: 'Aún no tienes certificados. ¡Completa un curso para obtener uno!',
        no_announcements: 'No hay anuncios por ahora.', download_certificate: 'Descargar certificado', verify: 'Verificar',
        progress: 'Progreso', instructor_dashboard: 'Panel del instructor', total_students: 'Estudiantes',
        my_courses_count: 'Mis cursos', published_courses: 'Publicados', avg_rating: 'Valoración media',
        recent_reviews: 'Reseñas recientes', pending_review: 'Pendiente de revisión', create_course: 'Crear curso',
        view_courses: 'Ver mis cursos', earnings: 'Ingresos', students_enrolled: ':count estudiantes inscritos',
    },
    courses: {
        by: 'por', featured: 'Destacados', latest: 'Más recientes', courses: 'Cursos', view_all: 'Ver todo',
        view_course: 'Ver curso', newest: 'Más recientes', catalog: 'Catálogo de cursos', filters: 'Filtros',
        courses_found: 'cursos encontrados', explore_courses: 'Explorar cursos', browse_by: 'Explorar por',
        category: 'Categoría', enroll: 'Inscribirse', enrolled: 'Inscrito', already_enrolled: 'Ya estás inscrito.',
        free: 'Gratis', level: 'Nivel', duration: 'Duración', language: 'Idioma', students: 'Estudiantes',
        rating: 'Valoración', reviews: 'Reseñas', curriculum: 'Programa', what_you_learn: 'Lo que aprenderás',
        requirements: 'Requisitos', description: 'Descripción', about_instructor: 'Sobre el instructor',
        related_courses: 'Cursos relacionados', write_review: 'Escribir una reseña', your_review: 'Tu reseña',
        submit_review: 'Enviar reseña', filter: 'Filtrar cursos', sort_by: 'Ordenar por', sort_newest: 'Más recientes',
        sort_popular: 'Más populares', sort_rating: 'Mejor valorados', all_categories: 'Todas las categorías',
        all_levels: 'Todos los niveles', free_only: 'Solo gratuitos', price: 'Precio', module: 'Módulo', lesson: 'Lección',
        quiz: 'Cuestionario', assignment: 'Tarea', video: 'Vídeo', text: 'Artículo', mark_complete: 'Marcar como completada',
        completed: 'Completado', progress: 'Progreso', next_lesson: 'Lección siguiente', prev_lesson: 'Lección anterior',
        course_completed: '¡Enhorabuena! Has completado este curso.', get_certificate: 'Obtener tu certificado',
        hours: 'horas', free_preview: 'Vista previa gratuita', locked: 'Bloqueado — inscríbete para acceder',
        no_video: 'No hay vídeo disponible para esta lección.', submit_quiz: 'Enviar cuestionario',
        quiz_passed: '¡Cuestionario aprobado! Puntuación: :score %', quiz_failed: 'Cuestionario no aprobado. Puntuación: :score %. Inténtalo de nuevo.',
        question: 'Pregunta', your_score: 'Tu puntuación anterior', attempt_again: 'Intentar de nuevo',
        comments: 'Preguntas y respuestas', add_comment: 'Hacer una pregunta', reply: 'Responder', post_comment: 'Publicar',
        download_attachment: 'Descargar adjunto', add_to_wishlist: 'Añadir a favoritos', remove_from_wishlist: 'Quitar de favoritos',
        popular: 'Más populares', top_rated: 'Mejor valorados', price_low: 'Precio: de menor a mayor',
        continue_learning: 'Seguir aprendiendo', enroll_now: 'Inscribirse ahora', no_courses_found: 'No se encontraron cursos.',
        student_reviews: 'Reseñas de estudiantes', try_different_filters: 'Prueba a cambiar los filtros o los términos de búsqueda.',
    },
    navigation: {
        home: 'Inicio', courses: 'Cursos', categories: 'Categorías', my_courses: 'Mis cursos', dashboard: 'Panel',
        profile: 'Perfil', wishlist: 'Favoritos', certificates: 'Certificados', subscription: 'Suscripción',
        logout: 'Cerrar sesión', login: 'Iniciar sesión', register: 'Registrarse', become_instructor: 'Hazte instructor',
        contact: 'Contacto', about: 'Acerca de', privacy: 'Política de privacidad', terms: 'Términos del servicio',
        admin_panel: 'Administración', instructor_portal: 'Espacio del instructor', search: 'Buscar',
        quick_links: 'Accesos rápidos', support: 'Soporte', contact_us: 'Contáctanos', notifications: 'Notificaciones',
        no_notifications: 'No hay notificaciones nuevas', start_free: 'Empezar gratis',
    },
    messages: {
        welcome: 'Bienvenido a ACADEXA', learn_grow: 'Aprende, crece y alcanza tus metas',
        hero_subtitle: 'Únete a miles de estudiantes del Instituto Universitario ZTF. Accede a cursos de primer nivel, obtén certificados y avanza en tu carrera.',
        get_started: 'Empieza gratis', browse_courses: 'Explorar cursos', featured_courses: 'Cursos destacados',
        latest_courses: 'Cursos recientes', view_all: 'Ver todo', categories: 'Categorías', why_acadexa: '¿Por qué elegir ACADEXA?',
        enroll_now: 'Inscribirse ahora', start_learning: 'Empezar a aprender', continue_learning: 'Seguir aprendiendo',
        free: 'Gratis', all_levels: 'Todos los niveles', beginner: 'Principiante', intermediate: 'Intermedio', advanced: 'Avanzado',
        students: 'estudiantes', courses: 'cursos', instructors: 'instructores', certificates_issued: 'certificados emitidos',
        trial_active: 'Prueba activa', trial_expires: 'La prueba vence el :date',
        trial_expired: 'Tu periodo de prueba ha terminado. Suscríbete para seguir aprendiendo.', upgrade: 'Suscribirse',
        become_instructor: 'Hazte instructor', teach_world: 'Enseña al mundo', no_courses: 'No se encontraron cursos.',
        contact_us: 'Contáctanos', send_message: 'Enviar mensaje', name: 'Nombre', email: 'Correo electrónico', phone: 'Teléfono',
        subject: 'Asunto', message: 'Mensaje', message_sent: 'Tu mensaje ha sido enviado. Te responderemos pronto.',
        search_placeholder: 'Buscar cursos, temas...', no_results: 'No hay resultados para ":query"',
        certificate_verified: 'Certificado verificado', certificate_not_found: 'Certificado no encontrado',
        verify_certificate: 'Verificar certificado', enter_code: 'Introduce el código del certificado',
        payment_coming_soon: 'Pagos y monetización — próximamente', contact_support: 'Contactar con soporte',
        language_changed: 'Idioma cambiado correctamente.', profile_updated: 'Perfil actualizado correctamente.',
        password_changed: 'Contraseña cambiada correctamente.',
        account_deactivated: 'Tu cuenta ha sido desactivada. Contacta con soporte.',
        already_applied: 'Ya has solicitado ser instructor.', already_enrolled: 'Ya estás inscrito en este curso.',
        application_submitted: 'Tu solicitud ha sido enviada. Te responderemos pronto.',
        certificate_issued: '¡Enhorabuena! Has completado el curso y tu certificado está listo.',
        comment_posted: 'Tu pregunta ha sido publicada.', contact_sent: 'Tu mensaje ha sido enviado. Te responderemos pronto.',
        course_deleted: 'Curso eliminado.', course_submitted: 'Curso enviado para revisión. Te avisaremos de la decisión.',
        course_updated: 'Curso actualizado.', enrolled_success: 'Te has inscrito. ¡Buen aprendizaje!',
        quiz_failed: 'Aún no aprobado. Repasa la lección e inténtalo de nuevo.', quiz_passed: '¡Bien hecho, has aprobado el cuestionario!',
        review_submitted: 'Gracias por tu reseña.', wishlist_added: 'Añadido a tus favoritos.', wishlist_removed: 'Quitado de tus favoritos.',
        wrong_password: 'La contraseña actual es incorrecta.',
    },
};
