// Spanish — security and validation groups
module.exports = {
    security: {
        '2fa_title': 'Verificación en dos pasos (2FA)',
        '2fa_intro': 'Protege tu cuenta de administrador: además de la contraseña, se pedirá un código de 6 cifras generado por tu teléfono.',
        '2fa_step1': 'Instala una aplicación de autenticación (Google Authenticator, Microsoft Authenticator, Authy…).',
        '2fa_step2': 'Escanea el código QR (o escribe la clave manualmente).',
        '2fa_step3': 'Introduce el código que muestra la aplicación para confirmar.',
        '2fa_active_since': 'Verificación en dos pasos activa desde el :date.',
        '2fa_disable_help': 'Para desactivarla, confirma con tu contraseña y un código de la aplicación.',
        '2fa_challenge_help': 'Introduce el código de 6 cifras de tu aplicación de autenticación.',
        manual_key: 'Clave para escribir manualmente', enable: 'Activar', disable: 'Desactivar', verify: 'Verificar', password: 'Contraseña',
        enabled: 'Verificación en dos pasos activada.', disabled: 'Verificación en dos pasos desactivada.',
        invalid_code: 'Código no válido o caducado.', invalid_credentials: 'Contraseña o código incorrectos.',
        reset_2fa: 'Restablecer 2FA', confirm_reset_2fa: '¿Restablecer la verificación en dos pasos de esta cuenta?',
        reset_done: 'Verificación en dos pasos restablecida.',
        use_admin_login: 'Esta cuenta usa verificación en dos pasos: inicia sesión desde el área de administración.',
        my_security: 'Seguridad de la cuenta',
        banned: 'Esta cuenta ha sido suspendida. Contacta con soporte si crees que es un error.',
        banned_badge: 'Bloqueado', banned_since: 'Bloqueado desde el :date', ban_reason: 'Motivo (opcional)',
        confirm_ban: '¿Bloquear a este usuario? Su sesión se cerrará inmediatamente.', unban: 'Desbloquear',
        user_banned: 'Usuario bloqueado y desconectado.', user_unbanned: 'Bloqueo levantado.',
        cannot_edit_self: 'No puedes realizar esta acción sobre tu propia cuenta.',
        no_permission: 'No tienes acceso a esta sección de la administración.',
        role_permissions: 'Rol y permisos', save_permissions: 'Guardar',
        permissions_help: 'Para un administrador: secciones permitidas. Ninguna marcada = acceso completo.',
        permissions_saved: 'Rol y permisos guardados.',
        perm_users: 'Usuarios', perm_courses: 'Cursos', perm_categories: 'Categorías', perm_applications: 'Solicitudes',
        perm_announcements: 'Anuncios', perm_cms: 'Páginas', perm_reviews: 'Reseñas', perm_certificates: 'Certificados',
        perm_contacts: 'Mensajes de contacto', perm_translations: 'Traducciones', perm_settings: 'Configuración',
        perm_logs: 'Registro de actividad', perm_reports: 'Informes',
        platform: 'Plataforma', allow_registration: 'Registro abierto',
        require_email_verification: 'Exigir la verificación del correo electrónico',
        maintenance_mode: 'Modo mantenimiento (solo los administradores acceden al sitio)',
        email_verification_help: 'Activa la verificación del correo solo cuando los correos ya se envíen: clave API de Brevo guardada en el recuadro «Correos» de esta página.',
        registration_closed: 'El registro está cerrado temporalmente.',
        reports: 'Informes', total_students: 'Estudiantes', active_30d: 'Activos (30 días)', total_enrollments: 'Inscripciones a cursos',
        completion_rate: 'Tasa de finalización', last_12_months: 'Últimos 12 meses', month: 'Mes',
        registrations: 'Nuevos estudiantes', enrollments: 'Inscripciones', completions: 'Cursos completados', certificates: 'Certificados',
        top_courses: 'Cursos más seguidos',
        export_users: 'Usuarios (CSV)', export_enrollments: 'Inscripciones (CSV)', export_certificates: 'Certificados (CSV)',
    },
    validation: {
        accepted: 'El campo :attribute debe ser aceptado.',
        active_url: 'El campo :attribute debe ser una URL válida.',
        after: 'El campo :attribute debe ser una fecha posterior a :date.',
        after_or_equal: 'El campo :attribute debe ser una fecha posterior o igual a :date.',
        alpha: 'El campo :attribute solo puede contener letras.',
        alpha_dash: 'El campo :attribute solo puede contener letras, números, guiones y guiones bajos.',
        alpha_num: 'El campo :attribute solo puede contener letras y números.',
        array: 'El campo :attribute debe ser una lista.',
        before: 'El campo :attribute debe ser una fecha anterior a :date.',
        before_or_equal: 'El campo :attribute debe ser una fecha anterior o igual a :date.',
        between: {
            array: 'El campo :attribute debe tener entre :min y :max elementos.',
            file: 'El archivo :attribute debe pesar entre :min y :max kilobytes.',
            numeric: 'El valor de :attribute debe estar entre :min y :max.',
            string: 'El texto :attribute debe tener entre :min y :max caracteres.',
        },
        boolean: 'El campo :attribute debe ser verdadero o falso.',
        confirmed: 'La confirmación de :attribute no coincide.',
        current_password: 'La contraseña es incorrecta.',
        date: 'El campo :attribute debe ser una fecha válida.',
        date_format: 'El campo :attribute debe tener el formato :format.',
        different: 'Los campos :attribute y :other deben ser distintos.',
        digits: 'El campo :attribute debe tener :digits cifras.',
        digits_between: 'El campo :attribute debe tener entre :min y :max cifras.',
        email: 'El campo :attribute debe ser un correo electrónico válido.',
        ends_with: 'El campo :attribute debe terminar con uno de estos valores: :values.',
        enum: 'El valor seleccionado para :attribute no es válido.',
        exists: 'El valor seleccionado para :attribute no es válido.',
        extensions: 'El archivo :attribute debe tener una de estas extensiones: :values.',
        file: 'El campo :attribute debe ser un archivo.',
        filled: 'El campo :attribute debe tener un valor.',
        gt: {
            array: 'El campo :attribute debe tener más de :value elementos.',
            file: 'El archivo :attribute debe pesar más de :value kilobytes.',
            numeric: 'El valor de :attribute debe ser mayor que :value.',
            string: 'El texto :attribute debe tener más de :value caracteres.',
        },
        gte: {
            array: 'El campo :attribute debe tener :value elementos o más.',
            file: 'El archivo :attribute debe pesar al menos :value kilobytes.',
            numeric: 'El valor de :attribute debe ser mayor o igual que :value.',
            string: 'El texto :attribute debe tener al menos :value caracteres.',
        },
        image: 'El campo :attribute debe ser una imagen.',
        in: 'El valor seleccionado para :attribute no es válido.',
        integer: 'El campo :attribute debe ser un número entero.',
        ip: 'El campo :attribute debe ser una dirección IP válida.',
        json: 'El campo :attribute debe ser un texto JSON válido.',
        lowercase: 'El campo :attribute debe estar en minúsculas.',
        lt: {
            array: 'El campo :attribute debe tener menos de :value elementos.',
            file: 'El archivo :attribute debe pesar menos de :value kilobytes.',
            numeric: 'El valor de :attribute debe ser menor que :value.',
            string: 'El texto :attribute debe tener menos de :value caracteres.',
        },
        lte: {
            array: 'El campo :attribute no debe tener más de :value elementos.',
            file: 'El archivo :attribute debe pesar como máximo :value kilobytes.',
            numeric: 'El valor de :attribute debe ser menor o igual que :value.',
            string: 'El texto :attribute debe tener como máximo :value caracteres.',
        },
        max: {
            array: 'El campo :attribute no debe tener más de :max elementos.',
            file: 'El archivo :attribute no debe superar los :max kilobytes.',
            numeric: 'El valor de :attribute no debe ser mayor que :max.',
            string: 'El texto :attribute no debe superar los :max caracteres.',
        },
        mimes: 'El archivo :attribute debe ser de tipo: :values.',
        mimetypes: 'El archivo :attribute debe ser de tipo: :values.',
        min: {
            array: 'El campo :attribute debe tener al menos :min elementos.',
            file: 'El archivo :attribute debe pesar al menos :min kilobytes.',
            numeric: 'El valor de :attribute debe ser al menos :min.',
            string: 'El texto :attribute debe tener al menos :min caracteres.',
        },
        not_in: 'El valor seleccionado para :attribute no es válido.',
        numeric: 'El campo :attribute debe ser un número.',
        password: {
            letters: 'El campo :attribute debe contener al menos una letra.',
            mixed: 'El campo :attribute debe contener al menos una mayúscula y una minúscula.',
            numbers: 'El campo :attribute debe contener al menos un número.',
            symbols: 'El campo :attribute debe contener al menos un símbolo.',
            uncompromised: 'Este :attribute ha aparecido en una filtración de datos. Elige otro.',
        },
        present: 'El campo :attribute debe estar presente.',
        prohibited: 'El campo :attribute no está permitido.',
        regex: 'El formato del campo :attribute no es válido.',
        required: 'El campo :attribute es obligatorio.',
        required_if: 'El campo :attribute es obligatorio cuando :other es :value.',
        required_with: 'El campo :attribute es obligatorio cuando :values está presente.',
        required_without: 'El campo :attribute es obligatorio cuando :values no está presente.',
        same: 'Los campos :attribute y :other deben coincidir.',
        size: {
            array: 'El campo :attribute debe contener :size elementos.',
            file: 'El archivo :attribute debe pesar :size kilobytes.',
            numeric: 'El valor de :attribute debe ser :size.',
            string: 'El texto :attribute debe tener :size caracteres.',
        },
        starts_with: 'El campo :attribute debe empezar por uno de estos valores: :values.',
        string: 'El campo :attribute debe ser un texto.',
        timezone: 'El campo :attribute debe ser una zona horaria válida.',
        unique: 'El valor de :attribute ya está en uso.',
        uploaded: 'No se pudo subir el archivo :attribute.',
        uppercase: 'El campo :attribute debe estar en mayúsculas.',
        url: 'El campo :attribute debe ser una URL válida.',
        uuid: 'El campo :attribute debe ser un UUID válido.',
        attributes: {
            name: 'nombre', email: 'correo electrónico', password: 'contraseña', password_confirmation: 'confirmación de la contraseña',
            current_password: 'contraseña actual', country: 'país', bio: 'biografía', title: 'título',
            description: 'descripción', content: 'contenido', body: 'mensaje', subject: 'asunto', message: 'mensaje',
            phone: 'teléfono', category_id: 'categoría', level: 'nivel', language: 'idioma', price: 'precio',
            duration_hours: 'horas', duration_minutes: 'duración', thumbnail: 'imagen de portada', file: 'archivo',
            rating: 'valoración', comment: 'comentario', score: 'nota', feedback: 'comentario', code: 'código',
            slug: 'dirección', audience: 'público', expertise: 'área de especialización', credentials: 'titulaciones',
            reason: 'motivo', days: 'número de días', question: 'pregunta', options: 'opciones', correct: 'respuesta correcta',
            youtube_url: 'enlace de YouTube', vimeo_url: 'enlace de Vimeo', external_url: 'enlace del vídeo', hero_image: 'imagen',
        },
    },
};
