// Spanish — JSON strings (key = English source)
module.exports = {
    "2FA": "2FA",
    "6 Languages": "6 idiomas",
    ":count certificate|:count certificates": ":count certificado|:count certificados",
    ":count course available|:count courses available": ":count curso disponible|:count cursos disponibles",
    ":count course|:count courses": ":count curso|:count cursos",
    ":count day left|:count days left": "Queda :count día|Quedan :count días",
    ":count day of free trial|:count days of free trial": ":count día de prueba gratuita|:count días de prueba gratuita",
    ":count missing string|:count missing strings": ":count texto sin traducir|:count textos sin traducir",
    ":count result for :query|:count results for :query": ":count resultado para :query|:count resultados para :query",
    ":count review|:count reviews": ":count reseña|:count reseñas",
    ":count star|:count stars": ":count estrella|:count estrellas",
    ":count student|:count students": ":count estudiante|:count estudiantes",
    ":count subcategory|:count subcategories": ":count subcategoría|:count subcategorías",
    ":count% of the interface": ":count % de la interfaz",
    ":done of :total languages": ":done de :total idiomas",
    ":hours in total": ":hours en total",
    ":login or register to enroll": ":login o regístrate para inscribirte",
    ":name on :course": ":name en :course",
    ":network link": "Enlace de :network",
    ":rating average rating": "Valoración media: :rating",
    ":site — ZTF University Institute. All rights reserved.": ":site — Instituto Universitario ZTF. Todos los derechos reservados.",
    "A new link has been sent!": "¡Se ha enviado un nuevo enlace!",
    "ACADEXA is currently undergoing scheduled maintenance. We apologize for the inconvenience — check back soon!": "ACADEXA está en mantenimiento programado. Disculpa las molestias — ¡vuelve pronto!",
    "ACADEXA — Empowering World Innovators and Leaders for Global Impact. Learn from top instructors at ZTF University Institute, Bertoua, Cameroon.": "ACADEXA — Formando a innovadores y líderes del mundo para un impacto global. Aprende con los mejores instructores del Instituto Universitario ZTF, Bertoua, Camerún.",
    "About": "Acerca de",
    "Access denied. Admin only.": "Acceso denegado. Solo administradores.",
    "Access world-class education online. :courses+ courses, :instructors+ expert instructors, in 6 languages. Start your free trial today.": "Accede en línea a una formación de primer nivel. Más de :courses cursos, más de :instructors instructores expertos, en 6 idiomas. Empieza hoy tu prueba gratuita.",
    "Access your courses on any device, anytime, at your own pace — even offline.": "Accede a tus cursos en cualquier dispositivo, en cualquier momento y a tu ritmo — incluso sin conexión.",
    "Account": "Cuenta",
    "Action": "Acción",
    "Actions": "Acciones",
    "Actions Needed": "Acciones pendientes",
    "Activate": "Activar",
    "Active": "Activo",
    "Activity Logs": "Registro de actividad",
    "Activity logs older than 30 days have been cleared.": "Se han borrado los registros de más de 30 días.",
    "Add Category": "Añadir categoría",
    "Address": "Dirección",
    "Admin": "Administración",
    "Admin Feedback:": "Comentarios de la administración:",
    "Admin Login": "Acceso de administrador",
    "Admin Login — ACADEXA": "Acceso de administrador — ACADEXA",
    "Admin Notes:": "Notas de la administración:",
    "Admin Panel": "Administración",
    "Admin access required.": "Se requiere acceso de administrador.",
    "Admins and instructors are never affected by trial limits.": "Los administradores e instructores nunca están sujetos al límite de prueba.",
    "African students learning": "Estudiantes africanos aprendiendo",
    "All": "Todos",
    "All Categories": "Todas las categorías",
    "All Courses": "Todos los cursos",
    "All Ratings": "Todas las valoraciones",
    "All Reviews": "Todas las reseñas",
    "All Roles": "Todos los roles",
    "All Status": "Todos los estados",
    "All rights reserved.": "Todos los derechos reservados.",
    "Announcement created.": "Anuncio creado.",
    "Announcement deleted.": "Anuncio eliminado.",
    "Announcement updated.": "Anuncio actualizado.",
    "Announcements": "Anuncios",
    "Applicant": "Solicitante",
    "Application Details": "Detalles de la solicitud",
    "Application rejected.": "Solicitud rechazada.",
    "Application: :name": "Solicitud: :name",
    "Applications": "Solicitudes",
    "Applied": "Solicitud",
    "Applied on :date": "Solicitud enviada el :date",
    "Apply to Become an Instructor": "Solicita ser instructor",
    "Apply to Teach": "Solicitar para enseñar",
    "Approve": "Aprobar",
    "Approve & Publish": "Aprobar y publicar",
    "Approve Application": "Aceptar la solicitud",
    "Approve this application? The user will become a confirmed instructor.": "¿Aceptar esta solicitud? El usuario pasará a ser instructor confirmado.",
    "Approved": "Aceptada",
    "Area of Expertise": "Área de especialización",
    "Area of Expertise *": "Área de especialización *",
    "Audience": "Público",
    "Audience *": "Público *",
    "Avg Rating": "Valoración media",
    "Back": "Volver",
    "Back to ACADEXA": "Volver a ACADEXA",
    "Back to the website": "Volver al sitio web",
    "Background Color": "Color de fondo",
    "Ban User": "Bloquear usuario",
    "Be associated with ZTF University Institute, a respected academic institution.": "Asocia tu nombre al Instituto Universitario ZTF, una institución académica reconocida.",
    "Become Instructor": "Hazte instructor",
    "Become an ACADEXA Instructor": "Hazte instructor en ACADEXA",
    "Become an Instructor": "Hazte instructor",
    "Bertoua, East Region, Cameroon": "Bertoua, Región del Este, Camerún",
    "Bio": "Biografía",
    "Bio:": "Biografía:",
    "Breadcrumb": "Ruta de navegación",
    "Browse All Courses": "Ver todos los cursos",
    "Browse Courses": "Explorar cursos",
    "By registering you get :trial. No payment required. By continuing, you agree to our :terms and :privacy.": "Al registrarte obtienes :trial. Sin pago. Al continuar, aceptas nuestros :terms y nuestra :privacy.",
    "CERTIFICATE CODE": "CÓDIGO DEL CERTIFICADO",
    "CERTIFICATE OF COMPLETION": "CERTIFICADO DE FINALIZACIÓN",
    "CMS Pages": "Páginas del sitio",
    "COURSE": "CURSO",
    "Cancel": "Cancelar",
    "Categories": "Categorías",
    "Category created.": "Categoría creada.",
    "Category deleted.": "Categoría eliminada.",
    "Category updated.": "Categoría actualizada.",
    "Certificate": "Certificado",
    "Certificate Code": "Código del certificado",
    "Certificate Description Text": "Texto descriptivo del certificado",
    "Certificate ID: :code": "N.º de certificado: :code",
    "Certificate Not Found": "Certificado no encontrado",
    "Certificate Signature": "Firma del certificado",
    "Certificate Template": "Plantilla del certificado",
    "Certificate Template Settings": "Configuración de la plantilla del certificado",
    "Certificate Verified!": "¡Certificado verificado!",
    "Certificate of completion": "Certificado de finalización",
    "Certificate revoked.": "Certificado revocado.",
    "Certificate signature used on all generated PDFs.": "Firma utilizada en todos los certificados PDF generados.",
    "Certificate template updated.": "Plantilla del certificado actualizada.",
    "Certificates": "Certificados",
    "Change Lives.": "Cambia vidas.",
    "Change Password (optional)": "Cambiar contraseña (opcional)",
    "Change Photo": "Cambiar foto",
    "Clear Filters": "Borrar filtros",
    "Clear Old Logs": "Borrar registros antiguos",
    "Clear all activity logs older than 30 days?": "¿Borrar todos los registros de actividad de más de 30 días?",
    "Close": "Cerrar",
    "Code:": "Código:",
    "Coming Soon": "Próximamente",
    "Complete a course to earn certificates.": "Completa un curso para obtener certificados.",
    "Complete a course to earn your first certificate.": "Completa un curso para obtener tu primer certificado.",
    "Completed": "Completado",
    "Confirm": "Confirmar",
    "Confirm New": "Confirmar la nueva",
    "Confirm Password": "Confirmar contraseña",
    "Confirm Your Password": "Confirma tu contraseña",
    "Contact": "Contacto",
    "Contact Email": "Correo de contacto",
    "Contact Information": "Datos de contacto",
    "Contact Messages": "Mensajes de contacto",
    "Contact Phone": "Teléfono de contacto",
    "Contact Submission": "Mensaje de contacto",
    "Contact Submissions": "Mensajes de contacto",
    "Contact Us": "Contáctanos",
    "Contact Us for More Info": "Contáctanos para más información",
    "Contact info appears in the site footer and contact page.": "Los datos de contacto aparecen en el pie de página y en la página de contacto.",
    "Contact: :name": "Contacto: :name",
    "Contacts": "Contactos",
    "Content": "Contenido",
    "Content (English) *": "Contenido (inglés) *",
    "Content (FR)": "Contenido (FR)",
    "Content (French)": "Contenido (francés)",
    "Content (HTML allowed)": "Contenido (se admite HTML)",
    "Content translations": "Traducciones de contenidos",
    "Continue Learning": "Seguir aprendiendo",
    "Control Panel": "Panel de control",
    "Control Panel — Admin Access": "Panel de control — acceso de administrador",
    "Country": "País",
    "Country:": "País:",
    "Course": "Curso",
    "Course Details": "Detalles del curso",
    "Course Management": "Gestión de cursos",
    "Course Reviews": "Reseñas de cursos",
    "Course Title Here": "Título del curso",
    "Course approved and published.": "Curso aprobado y publicado.",
    "Course deleted.": "Curso eliminado.",
    "Course featured status updated.": "Estado destacado del curso actualizado.",
    "Course rejected with feedback.": "Curso rechazado con comentarios.",
    "Course unpublished.": "Curso despublicado.",
    "Courses": "Cursos",
    "Courses by :name": "Cursos de :name",
    "Courses created by ZTF University Institute academics and industry professionals.": "Cursos creados por docentes del Instituto Universitario ZTF y profesionales del sector.",
    "Create Course": "Crear curso",
    "Create Page": "Crear página",
    "Created By": "Creado por",
    "Credentials & Qualifications": "Titulaciones y cualificaciones",
    "Credentials & Qualifications *": "Titulaciones y cualificaciones *",
    "Current Password": "Contraseña actual",
    "Current file: :name": "Archivo actual: :name",
    "Curriculum": "Programa",
    "Dashboard": "Panel",
    "Date": "Fecha",
    "Date of completion: :date": "Fecha de finalización: :date",
    "Date of issue: :date": "Fecha de emisión: :date",
    "Deactivate": "Desactivar",
    "Deactivate this user?": "¿Desactivar a este usuario?",
    "Deactivate?": "¿Desactivar?",
    "Decision": "Decisión",
    "Degrees, certifications, years of experience, institutions...": "Títulos, certificaciones, años de experiencia, instituciones…",
    "Delete": "Eliminar",
    "Delete subcategory?": "¿Eliminar la subcategoría?",
    "Delete this announcement?": "¿Eliminar este anuncio?",
    "Delete this category?": "¿Eliminar esta categoría?",
    "Delete this course?": "¿Eliminar este curso?",
    "Delete this page?": "¿Eliminar esta página?",
    "Delete this submission?": "¿Eliminar este mensaje?",
    "Deleted.": "Eliminado.",
    "Deliver your courses in English, French, Spanish, Portuguese, Chinese, or Arabic.": "Imparte tus cursos en inglés, francés, español, portugués, chino o árabe.",
    "Describe the courses you'd like to create on ACADEXA...": "Describe los cursos que te gustaría crear en ACADEXA…",
    "Description": "Descripción",
    "Description (EN):": "Descripción (EN):",
    "Download": "Descargar",
    "Download PDF": "Descargar PDF",
    "Duration:": "Duración:",
    "Earn Certificates": "Obtén certificados",
    "Earn Revenue": "Genera ingresos",
    "Earnings": "Ingresos",
    "Easy Tools": "Herramientas sencillas",
    "Edit": "Editar",
    "Edit Announcement": "Editar anuncio",
    "Edit Page": "Editar página",
    "Edit Page:": "Editar página:",
    "Edit Profile": "Editar perfil",
    "Edit: :name": "Editar: :name",
    "Email": "Correo electrónico",
    "Email *": "Correo electrónico *",
    "Email Directly": "Escribir directamente",
    "Empowering World Innovators": "Formando a los innovadores del mundo",
    "Empowering World Innovators and Leaders for Global Impact — Now Online.": "Formando a innovadores y líderes del mundo para un impacto global — ahora en línea.",
    "Empty fields fall back to English. Page contents are edited in CMS Pages; course contents are translated by their instructor.": "Los campos vacíos muestran la versión en inglés. El contenido de las páginas se edita en «Páginas del sitio»; los cursos los traduce su instructor.",
    "English": "Inglés",
    "Enrolled Courses": "Cursos inscritos",
    "Enrollments": "Inscripciones",
    "Enrollments:": "Inscripciones:",
    "Enter certificate code (e.g., ACADEXA-ABCD-EFGH-2025)": "Introduce el código del certificado (p. ej.: ACADEXA-ABCD-EFGH-2025)",
    "Enter your email and we'll send you a reset link.": "Introduce tu correo y te enviaremos un enlace para restablecer la contraseña.",
    "Every course reviewed by our academic team before publishing.": "Cada curso lo revisa nuestro equipo académico antes de publicarse.",
    "Everyone": "Todos",
    "Expert Instructors": "Instructores expertos",
    "Expertise": "Especialización",
    "Expired": "Vencida",
    "Explore Courses": "Explorar cursos",
    "Extend": "Ampliar",
    "Extend Trial (days)": "Ampliar la prueba (días)",
    "FAQ": "Preguntas frecuentes",
    "Facebook": "Facebook",
    "Feature": "Destacar",
    "Featured": "Destacado",
    "Filter": "Filtrar",
    "Flagged Only": "Solo denunciadas",
    "Forgot Password?": "¿Olvidaste tu contraseña?",
    "Français": "Français",
    "Free Trial": "Prueba gratuita",
    "French": "Francés",
    "Full Access Subscription": "Suscripción de acceso completo",
    "Full Name": "Nombre completo",
    "General": "General",
    "Get :days days of free access to explore courses before subscribing.": "Disfruta de :days días de acceso gratuito para descubrir los cursos antes de suscribirte.",
    "Get in :touch": "Ponte en :touch",
    "Global Impact": "impacto global",
    "Global Reach": "Alcance mundial",
    "Go Back": "Volver",
    "Go Home": "Ir al inicio",
    "Go to Instructor Portal": "Ir al espacio del instructor",
    "Growth Overview (Last 6 Months)": "Crecimiento (últimos 6 meses)",
    "Guest": "Visitante",
    "Have a question about our courses, admissions, or partnerships? We'd love to hear from you.": "¿Tienes una pregunta sobre nuestros cursos, admisiones o colaboraciones? Escríbenos.",
    "Hello!": "¡Hola!",
    "Hero": "Cabecera",
    "Hero Background Image": "Imagen de fondo de la cabecera",
    "Hero Image (optional)": "Imagen de cabecera (opcional)",
    "Hero Subtitle": "Subtítulo de la cabecera",
    "Home": "Inicio",
    "IP": "IP",
    "ISSUED": "EMITIDO",
    "Icon": "Icono",
    "If you believe this is an error, please contact us at :email": "Si crees que es un error, contáctanos en :email",
    "If you did not create an account, no further action is required.": "Si no creaste una cuenta, no tienes que hacer nada.",
    "If you did not request a password reset, no further action is required.": "Si no solicitaste restablecer la contraseña, no tienes que hacer nada.",
    "If you're having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:": "Si el botón «:actionText» no funciona, copia y pega esta dirección\nen tu navegador:",
    "Inactive": "Inactivo",
    "Instagram": "Instagram",
    "Institution Name": "Nombre de la institución",
    "Instructor": "Instructor",
    "Instructor Applications": "Solicitudes de instructores",
    "Instructor Dashboard": "Panel del instructor",
    "Instructor Portal": "Espacio del instructor",
    "Instructor Status:": "Estado de instructor:",
    "Instructor application approved.": "Solicitud de instructor aceptada.",
    "Instructors": "Instructores",
    "Instructors Only": "Solo instructores",
    "Instructors teaching": "Instructores enseñando",
    "Issued": "Emitido",
    "Issued Certificates": "Certificados emitidos",
    "Issued by :site — ZTF University Institute, Bertoua, Cameroon": "Emitido por :site — Instituto Universitario ZTF, Bertoua, Camerún",
    "Issued on :date": "Emitido el :date",
    "Join ZTF University Institute's growing network of online educators. Create courses in 6 languages and reach learners across Africa and the globe.": "Únete a la creciente red de docentes en línea del Instituto Universitario ZTF. Crea cursos en 6 idiomas y llega a estudiantes de África y de todo el mundo.",
    "Joined": "Registrado el",
    "Joined:": "Registrado el:",
    "Language": "Idioma",
    "Last lesson: :title": "Última lección: :title",
    "Learn Anywhere": "Aprende en cualquier lugar",
    "Learn in English, French, Spanish, Portuguese, Chinese, or Arabic.": "Aprende en inglés, francés, español, portugués, chino o árabe.",
    "Leave a Review": "Dejar una reseña",
    "Level:": "Nivel:",
    "LinkedIn": "LinkedIn",
    "Log Out": "Cerrar sesión",
    "Log in": "Iniciar sesión",
    "Logo (top of certificate)": "Logotipo (parte superior del certificado)",
    "Logout": "Cerrar sesión",
    "Lowercase letters, numbers, and hyphens only": "Solo letras minúsculas, números y guiones",
    "MESSAGE": "MENSAJE",
    "Main": "Principal",
    "Maintenance Mode — ACADEXA": "Mantenimiento — ACADEXA",
    "Manage your courses and track student progress from here.": "Gestiona tus cursos y sigue el progreso de tus estudiantes.",
    "Message *": "Mensaje *",
    "Min. 8 characters": "Mínimo 8 caracteres",
    "Mobile accessible": "Accesible desde el móvil",
    "Monetization features are coming soon.": "Las funciones de monetización llegarán pronto.",
    "Monetization is coming — get in early and build your audience now.": "La monetización está en camino — empieza ya y construye tu audiencia.",
    "Monitoring": "Seguimiento",
    "My Certificates": "Mis certificados",
    "My Courses": "Mis cursos",
    "My Dashboard": "Mi panel",
    "My Profile": "Mi perfil",
    "My Wishlist": "Mis favoritos",
    "Name": "Nombre",
    "Name *": "Nombre *",
    "New": "Nuevo",
    "New Announcement": "Nuevo anuncio",
    "New CMS Page": "Nueva página",
    "New Course": "Nuevo curso",
    "New Page": "Nueva página",
    "New Password": "Nueva contraseña",
    "New Users": "Nuevos usuarios",
    "New password": "Nueva contraseña",
    "No CMS pages found.": "No hay páginas.",
    "No announcements yet.": "Aún no hay anuncios.",
    "No announcements.": "No hay anuncios.",
    "No applications found.": "No hay solicitudes.",
    "No certificates issued yet.": "Aún no se han emitido certificados.",
    "No certificates yet": "Aún no hay certificados",
    "No certificates yet.": "Aún no hay certificados.",
    "No contact submissions yet.": "Aún no hay mensajes de contacto.",
    "No courses found for \":query\"": "No se encontraron cursos para «:query»",
    "No courses found.": "No se encontraron cursos.",
    "No courses in this category yet.": "Aún no hay cursos en esta categoría.",
    "No courses yet.": "Aún no hay cursos.",
    "No courses yet. Create your first course!": "Aún no hay cursos. ¡Crea tu primer curso!",
    "No enrollments.": "No hay inscripciones.",
    "No logs found.": "No hay registros.",
    "No pending courses.": "No hay cursos pendientes.",
    "No published courses yet.": "Aún no hay cursos publicados.",
    "No reviews found.": "No hay reseñas.",
    "No reviews yet.": "Aún no hay reseñas.",
    "No reviews yet. Be the first!": "Aún no hay reseñas. ¡Sé el primero!",
    "No users found.": "No hay usuarios.",
    "None (root category)": "Ninguna (categoría principal)",
    "Notes for Applicant (optional)": "Mensaje para el solicitante (opcional)",
    "Online payment integration (MTN Mobile Money, Orange Money, PayPal, Stripe) is currently in development. Please contact us directly to discuss subscription options.": "El pago en línea (MTN Mobile Money, Orange Money, PayPal, Stripe) está en desarrollo. Contáctanos directamente para hablar de las opciones de suscripción.",
    "Operated by ZTF University Institute": "Gestionado por el Instituto Universitario ZTF",
    "Operated by ZTF University Institute, Bertoua, East Region, Cameroon.": "Gestionado por el Instituto Universitario ZTF, Bertoua, Región del Este, Camerún.",
    "Page": "Página",
    "Page Not Found": "Página no encontrada",
    "Page Not Found — ACADEXA": "Página no encontrada — ACADEXA",
    "Page Title (FR)": "Título de la página (FR)",
    "Page Title *": "Título de la página *",
    "Page created.": "Página creada.",
    "Page deleted.": "Página eliminada.",
    "Page updated.": "Página actualizada.",
    "Paid": "De pago",
    "Parent Category": "Categoría superior",
    "Password": "Contraseña",
    "Password reset successfully.": "Contraseña restablecida.",
    "Payment & Earnings — Coming Soon": "Pagos e ingresos — próximamente",
    "Pending": "Pendiente",
    "Pending Apps": "Solicitudes pendientes",
    "Pending Course Reviews": "Cursos pendientes de revisión",
    "Pending Courses": "Cursos pendientes",
    "People": "Personas",
    "Phone": "Teléfono",
    "Please :login or :register before applying.": "Por favor, :login o :register antes de enviar la solicitud.",
    "Please click the button below to verify your email address.": "Haz clic en el botón para verificar tu correo electrónico.",
    "Please confirm your password to continue.": "Confirma tu contraseña para continuar.",
    "Preferred Language": "Idioma preferido",
    "Preview": "Vista previa",
    "Preview Certificate": "Vista previa del certificado",
    "Price:": "Precio:",
    "Privacy Policy": "Política de privacidad",
    "Professional Bio": "Biografía profesional",
    "Professional Bio *": "Biografía profesional *",
    "Publish Announcement": "Publicar el anuncio",
    "Published": "Publicado",
    "Published Courses": "Cursos publicados",
    "Quality Assured": "Calidad garantizada",
    "Quick Actions": "Acciones rápidas",
    "Quick Info": "Resumen",
    "Quick Links": "Accesos rápidos",
    "RECIPIENT": "DESTINATARIO",
    "Rating": "Valoración",
    "Reach thousands of students across Africa, Europe, and beyond.": "Llega a miles de estudiantes en África, Europa y más allá.",
    "Read": "Leído",
    "Real Analytics": "Estadísticas reales",
    "Reason for rejection...": "Motivo del rechazo…",
    "Receive verifiable digital certificates upon course completion.": "Recibe un certificado digital verificable al terminar cada curso.",
    "Received": "Recibido",
    "Recent Reviews": "Reseñas recientes",
    "Recent Users": "Usuarios recientes",
    "Regards,": "Saludos,",
    "Registration number (learner ID): :id": "Número de matrícula (ID de estudiante): :id",
    "Reject Application": "Rechazar la solicitud",
    "Reject this application?": "¿Rechazar esta solicitud?",
    "Reject with Feedback": "Rechazar con comentarios",
    "Rejected": "Rechazada",
    "Related Courses": "Cursos relacionados",
    "Remember me": "Recordarme",
    "Remove from wishlist": "Quitar de favoritos",
    "Remove this review?": "¿Eliminar esta reseña?",
    "Repeat password": "Repite la contraseña",
    "Reply by Email": "Responder por correo",
    "Resend Verification Email": "Reenviar el correo de verificación",
    "Reset": "Restablecer",
    "Reset Password": "Restablecer contraseña",
    "Reset Password Notification": "Restablecimiento de contraseña",
    "Review": "Revisar",
    "Review deleted.": "Reseña eliminada.",
    "Review flag toggled.": "Denuncia de la reseña actualizada.",
    "Reviews": "Reseñas",
    "Revoke this certificate?": "¿Revocar este certificado?",
    "Role": "Rol",
    "Sample Content / Course Ideas": "Ejemplos de contenido / ideas de cursos",
    "Save": "Guardar",
    "Save Changes": "Guardar cambios",
    "Save Page": "Guardar página",
    "Save Settings": "Guardar configuración",
    "Save Template": "Guardar plantilla",
    "Save courses you want to take later.": "Guarda los cursos que quieras hacer más adelante.",
    "Search": "Buscar",
    "Search Results": "Resultados de búsqueda",
    "Search action...": "Buscar una acción…",
    "Search courses...": "Buscar cursos…",
    "Search name or email...": "Buscar nombre o correo…",
    "Search student or course...": "Buscar estudiante o curso…",
    "Search: :query": "Búsqueda: :query",
    "Secured admin access — ZTF University Institute": "Acceso de administrador seguro — Instituto Universitario ZTF",
    "Select Country": "Elige un país",
    "Select...": "Elegir…",
    "Send Message": "Enviar mensaje",
    "Send Reset Link": "Enviar enlace",
    "Send Us a Message": "Envíanos un mensaje",
    "Server Error — ACADEXA": "Error del servidor — ACADEXA",
    "Set New Password": "Establecer nueva contraseña",
    "Settings": "Configuración",
    "Settings saved.": "Configuración guardada.",
    "Share Your Knowledge.": "Comparte tus conocimientos.",
    "Share your experience...": "Comparte tu experiencia…",
    "Share your expertise with thousands of learners across Africa and the world. Join our growing community of educators.": "Comparte tu experiencia con miles de estudiantes de África y del mundo. Únete a nuestra creciente comunidad de docentes.",
    "Showing": "Mostrando",
    "Sign In": "Iniciar sesión",
    "Signature Name": "Nombre del firmante",
    "Signature Title": "Cargo del firmante",
    "Site Name": "Nombre del sitio",
    "Site Settings": "Configuración del sitio",
    "Site Translations": "Traducciones del sitio",
    "Sitemap": "Mapa del sitio",
    "Slug": "Dirección (slug)",
    "Social Media": "Redes sociales",
    "Something Went Wrong": "Algo ha salido mal",
    "Start Teaching Today": "Empieza a enseñar hoy",
    "Status": "Estado",
    "Student": "Estudiante",
    "Student Name": "Nombre del estudiante",
    "Student View": "Vista de estudiante",
    "Students": "Estudiantes",
    "Students Only": "Solo estudiantes",
    "Sub-heading": "Subtítulo",
    "Subject": "Asunto",
    "Subject *": "Asunto *",
    "Submit Application": "Enviar solicitud",
    "Submit Review": "Publicar reseña",
    "Subscribe Now": "Suscribirse",
    "Subscription": "Suscripción",
    "System": "Sistema",
    "System pages cannot be deleted.": "Las páginas del sistema no se pueden eliminar.",
    "Tell us about your background, experience, and teaching style (minimum 100 characters)": "Cuéntanos tu trayectoria, tu experiencia y tu forma de enseñar (mínimo 100 caracteres)",
    "Tell us about yourself...": "Háblanos de ti…",
    "Terms": "Términos",
    "Terms of Service": "Términos del servicio",
    "The certificate code :code was not found in our system.": "El código de certificado :code no existe en nuestro sistema.",
    "The page you're looking for doesn't exist or has been moved.": "La página que buscas no existe o se ha movido.",
    "This instructor has not added a bio yet.": "Este instructor aún no ha añadido su biografía.",
    "This is a simplified preview. Download an actual certificate to see the full PDF design.": "Esta es una vista previa simplificada. Descarga un certificado real para ver el diseño PDF completo.",
    "This is a valid ACADEXA certificate.": "Este certificado de ACADEXA es auténtico.",
    "This password reset link will expire in :count minutes.": "Este enlace para restablecer la contraseña caducará en :count minutos.",
    "Time": "Hora",
    "Title": "Título",
    "Title (English) *": "Título (inglés) *",
    "Title (French)": "Título (francés)",
    "Total Students": "Total de estudiantes",
    "Total Users": "Total de usuarios",
    "Track enrollments, ratings, and student progress in real-time.": "Sigue en tiempo real las inscripciones, las valoraciones y el progreso de los estudiantes.",
    "Translations": "Traducciones",
    "Translations updated.": "Traducciones actualizadas.",
    "Trial": "Prueba",
    "Trial Days (Default: 30)": "Días de prueba (por defecto: 30)",
    "Trial Ends:": "Fin de la prueba:",
    "Trial active — :count day left|Trial active — :count days left": "Prueba activa — queda :count día|Prueba activa — quedan :count días",
    "Trial days applies to new student registrations.": "Los días de prueba se aplican a los nuevos registros de estudiantes.",
    "Trial expired": "Prueba vencida",
    "Trial extended by :count day.|Trial extended by :count days.": "Prueba ampliada :count día.|Prueba ampliada :count días.",
    "Try different keywords or browse our categories.": "Prueba otras palabras clave o explora nuestras categorías.",
    "Twitter/X": "Twitter/X",
    "URL Slug *": "Dirección de la página *",
    "Unauthorized access.": "Acceso no autorizado.",
    "Unfeature": "Quitar de destacados",
    "Unpublish": "Despublicar",
    "Unpublish this course?": "¿Despublicar este curso?",
    "Updated": "Actualizado",
    "Use our intuitive course builder — no technical skills needed.": "Usa nuestro editor de cursos intuitivo — no necesitas conocimientos técnicos.",
    "User": "Usuario",
    "User Management": "Gestión de usuarios",
    "User activated.": "Usuario activado.",
    "User deactivated.": "Usuario desactivado.",
    "Users": "Usuarios",
    "Verification": "Verificación",
    "Verified instructor at :site": "Instructor verificado en :site",
    "Verify": "Verificar",
    "Verify Another Certificate": "Verificar otro certificado",
    "Verify Certificate": "Verificar un certificado",
    "Verify Email": "Verificar correo",
    "Verify Email Address": "Verifica tu correo electrónico",
    "Verify Your Email": "Verifica tu correo",
    "Verify at: :url": "Verificación: :url",
    "View": "Ver",
    "View All": "Ver todo",
    "View Site": "Ver el sitio",
    "Visit Website": "Visitar el sitio web",
    "We are building a powerful earnings dashboard with course revenue tracking, payout management, and detailed analytics. This feature will be available in a future update.": "Estamos preparando un panel de ingresos con seguimiento por curso, gestión de pagos y estadísticas detalladas. Esta función llegará en una próxima actualización.",
    "We encountered an unexpected error. Our team has been notified. Please try again in a few moments.": "Se ha producido un error inesperado. Nuestro equipo ha sido avisado. Inténtalo de nuevo en unos instantes.",
    "We sent a verification link to your email. Please click it to continue.": "Te hemos enviado un enlace de verificación por correo. Haz clic en él para continuar.",
    "We'll be right back": "Volvemos enseguida",
    "Website": "Sitio web",
    "Welcome back, :name!": "¡Hola de nuevo, :name!",
    "Whoops!": "¡Vaya!",
    "Why choose :brand?": "¿Por qué elegir :brand?",
    "Why teach on :brand?": "¿Por qué enseñar en :brand?",
    "Wishlist": "Favoritos",
    "You are already a confirmed instructor!": "¡Ya eres instructor confirmado!",
    "You are receiving this email because we received a password reset request for your account.": "Recibes este correo porque se ha solicitado restablecer la contraseña de tu cuenta.",
    "You can still access your certificates, profile, and course catalog. Only the course player is restricted.": "Sigues teniendo acceso a tus certificados, tu perfil y el catálogo. Solo el reproductor de cursos está restringido.",
    "You have already applied. Our team will review your application and get back to you within 3-5 business days.": "Ya has enviado tu solicitud. Nuestro equipo la revisará y te responderá en 3 a 5 días hábiles.",
    "You must be enrolled to review.": "Debes estar inscrito en el curso para dejar una reseña.",
    "You're not enrolled in any courses yet.": "Aún no estás inscrito en ningún curso.",
    "YouTube": "YouTube",
    "Your Course Enrollments": "Tus inscripciones",
    "Your Free Trial Has Expired": "Tu prueba gratuita ha terminado",
    "Your Full Name": "Tu nombre completo",
    "Your free trial ended on :date. Subscribe to continue accessing all courses and content.": "Tu prueba gratuita terminó el :date. Suscríbete para seguir accediendo a todos los cursos y contenidos.",
    "Your full name": "Tu nombre completo",
    "Your wishlist is empty": "Tu lista de favoritos está vacía",
    "ZTF University Institute — Bertoua, Cameroon": "Instituto Universitario ZTF — Bertoua, Camerún",
    "ZTF University Institute — www.ztfuniversity.com": "Instituto Universitario ZTF — www.ztfuniversity.com",
    "ZTF University Institute, Bertoua, East Region, Cameroon": "Instituto Universitario ZTF, Bertoua, Región del Este, Camerún",
    "ZTF University Institute, Koumé – Bertoua, East Region, Cameroon": "Instituto Universitario ZTF, Koumé – Bertoua, Región del Este, Camerún",
    "ZTF-UI Brand": "La marca IU-ZTF",
    "and Leaders for :impact": "y líderes para un :impact",
    "avatar": "foto de perfil",
    "by :name": "por :name",
    "e.g., Data Science, Law, Medicine, Engineering...": "p. ej.: ciencia de datos, derecho, medicina, ingeniería…",
    "has completed": "ha completado con éxito",
    "https://...": "https://…",
    "https://vimeo.com/123456789": "https://vimeo.com/123456789",
    "https://www.youtube.com/watch?v=…": "https://www.youtube.com/watch?v=…",
    "https://…/video.mp4": "https://…/video.mp4",
    "log in": "inicia sesión",
    "max. :size": "máx. :size",
    "min": "min",
    "my-page": "mi-pagina",
    "not found": "no encontrado",
    "of": "de",
    "register": "regístrate",
    "results": "resultados",
    "reviewer": "autor de la reseña",
    "to": "a",
    "touch": "contacto",
    "you@example.com": "tu@ejemplo.com",
    "Optional: leave empty to show the English version in this language.": "Opcional: déjalo vacío para mostrar la versión en inglés en este idioma.",
};
