// Spanish — lms group
module.exports = {
    actions: 'Acciones', add: 'Añadir', all: 'Todos', back: 'Volver', cancel: 'Cancelar', close: 'Cerrar',
    delete: 'Eliminar', details: 'Detalles', download: 'Descargar', edit: 'Editar', filter: 'Filtrar',
    loading: 'Cargando…', more: 'Más', none: 'Ninguno', post: 'Publicar', previous: 'Anterior', next: 'Siguiente',
    save: 'Guardar', send: 'Enviar', see_all: 'Ver todo', view: 'Ver', unlimited: 'Ilimitado',
    unauthorized: 'Acción no autorizada.', order_saved: 'Nuevo orden guardado.', confirm_delete: '¿Confirmar la eliminación?',
    name: 'Nombre', title: 'Título', description: 'Descripción', category: 'Categoría', level: 'Nivel',
    price: 'Precio', price_help: 'El pago en línea llegará pronto. 0 = gratis.', hours: 'horas',
    status: 'Estado', message: 'Mensaje', subject: 'Asunto', file: 'Archivo', course: 'Curso',
    student: 'Estudiante', students: 'Estudiantes', instructor: 'Instructor', lesson: 'Lección', lessons: 'lecciones',
    module: 'Módulo', modules: 'Módulos', progress: 'Progreso', rating: 'Valoración', stats: 'Estadísticas',
    certificate: 'Certificado', preview: 'Vista previa', tips: 'Consejos', my_courses: 'Mis cursos',
    lessons_count: '{0} Sin lecciones|{1} :count lección|[2,*] :count lecciones',
    modules_count: '{0} Sin módulos|{1} :count módulo|[2,*] :count módulos',
    questions_count: '{0} Sin preguntas|{1} :count pregunta|[2,*] :count preguntas',
    status_draft: 'Borrador', status_pending: 'En revisión', status_published: 'Publicado', status_rejected: 'Rechazado', status_unpublished: 'Despublicado',
    type_video: 'Vídeo', type_text: 'Texto / artículo', type_quiz: 'Cuestionario', type_assignment: 'Tarea',
    source_upload: 'Archivo de vídeo', source_youtube: 'YouTube', source_vimeo: 'Vimeo', source_url: 'Enlace directo',
    new_course: 'Nuevo curso',
    new_course_help: 'Empieza por lo esencial. Después construirás el programa: módulos (con sus horas) y luego lecciones.',
    step_info: 'Información', step_modules: 'Módulos y horas', step_lessons: 'Lecciones y contenido', step_submit: 'Envío',
    course_language: 'Idioma principal del curso', course_language_help: 'Podrás añadir una traducción más adelante.',
    course_hours: 'Horas lectivas del curso', course_hours_help: 'Número total de horas de formación (p. ej. 40 h).',
    course_title_placeholder: 'P. ej.: Introducción a la contabilidad general',
    thumbnail: 'Imagen de portada', thumbnail_help: 'JPG, PNG o WebP, 1280×720 recomendado, 4 MB máx.',
    create_and_continue: 'Crear y construir el programa', course_created_next_step: 'Curso creado. Ahora añade los módulos y sus horas.',
    edit_course: 'Editar curso', tab_info: 'Información', tab_curriculum: 'Programa',
    view_public_page: 'Página pública', admin_feedback: 'Comentarios de la administración',
    course_locked_pending: 'Este curso está en revisión: no se puede editar hasta que la administración decida.',
    sequential: 'Progresión secuencial', sequential_help: 'cada lección se desbloquea al completar la anterior.',
    optional_translation: 'Traducción opcional: déjala vacía si el curso solo se ofrece en su idioma principal.',
    what_you_learn: 'Lo que aprenderán los estudiantes', requirements: 'Requisitos', one_per_line: 'Un elemento por línea',
    course_delete_forbidden: 'No se puede eliminar un curso publicado o con estudiantes inscritos.',
    delete_course: 'Eliminar este curso', confirm_delete_course: '¿Eliminar definitivamente este curso, sus módulos, lecciones y vídeos?',
    no_courses_yet: 'Aún no has creado ningún curso.', students_and_stats: 'Estudiantes y estadísticas',
    drag_help: 'Arrastra y suelta módulos y lecciones para reordenarlos (también entre módulos).',
    drag: 'Mover', add_module: 'Añadir un módulo', edit_module: 'Editar módulo', add_first_module: 'Añadir el primer módulo',
    no_modules_title: 'Aún no hay módulos', no_modules_help: 'Un curso se divide en módulos (con su número de horas), que a su vez se dividen en lecciones.',
    module_hours: 'Horas del módulo', module_title: 'Título del módulo', module_description: 'Descripción / objetivos del módulo',
    module_description_placeholder: 'Objetivos de aprendizaje, competencias…',
    module_created: 'Módulo añadido.', module_updated: 'Módulo actualizado.', module_deleted: 'Módulo eliminado.',
    confirm_delete_module: '¿Eliminar este módulo y todas sus lecciones (vídeos incluidos)?',
    content_minutes: ':minutes min de contenido', content_duration: 'Duración de los contenidos (vídeos, lecturas): :duration',
    hours_breakdown: 'Reparto de horas', modules_total: 'Total de módulos',
    hours_over: 'La suma de horas de los módulos supera las horas del curso.',
    hours_remaining: 'Quedan :hours por repartir entre los módulos.', hours_match: 'Las horas de los módulos coinciden con las del curso.',
    before_submit: 'Antes de enviar',
    check_info: 'Título y descripción en el idioma principal', check_hours: 'Horas del curso y de cada módulo indicadas',
    check_modules: 'Al menos un módulo, y cada módulo tiene lecciones', check_videos: 'Cada lección de vídeo tiene un vídeo',
    check_quizzes: 'Cada cuestionario tiene al menos una pregunta', check_thumbnail: 'Imagen de portada',
    submit_review: 'Enviar para revisión', submit_incomplete: 'El curso está incompleto: revisa la lista «Antes de enviar».',
    pending_review_help: 'Tu curso está en revisión. Te avisaremos de la decisión por correo.',
    add_lesson: 'Añadir una lección', add_lesson_help: 'Añadirás el contenido (vídeo, texto, cuestionario…) en el siguiente paso.',
    create_and_edit: 'Crear y editar', edit_lesson: 'Editar lección', lesson_title: 'Título de la lección', lesson_type: 'Tipo de lección',
    lesson_content: 'Contenido de la lección', lesson_content_placeholder: 'Texto de la lección, notas, enlaces… (opcional para un vídeo)',
    lesson_created: 'Lección creada. Ahora añade su contenido.', lesson_saved: 'Lección guardada.', lesson_deleted: 'Lección eliminada.',
    lesson_incomplete: 'por completar', save_lesson: 'Guardar lección', back_to_curriculum: 'Programa',
    confirm_delete_lesson: '¿Eliminar esta lección?', delete_lesson: 'Eliminar lección',
    duration_minutes: 'Duración', free_preview: 'Vista previa gratuita', free_preview_help: 'visible sin inscribirse en la página del curso',
    downloadable: 'Disponible sin conexión', downloadable_help: 'los estudiantes pueden descargar esta lección en la aplicación',
    video: 'Vídeo', upload_video: 'Subir un vídeo', drop_video: 'Arrastra tu vídeo aquí o haz clic para elegir un archivo',
    video_formats: 'Formatos: :formats — hasta :max', upload_resumable_help: 'Si se corta la conexión, vuelve a elegir el mismo archivo: la subida continuará donde se quedó.',
    replace_video_help: 'Para sustituir el vídeo, sube un archivo nuevo.',
    delete_video: 'Eliminar vídeo', confirm_delete_video: '¿Eliminar definitivamente este vídeo?',
    video_uploaded: 'Vídeo subido correctamente.', video_deleted: 'Vídeo eliminado.',
    upload_too_large: 'Archivo demasiado grande (máximo :max MB).', upload_bad_extension: 'Formato no admitido. Usa MP4, WebM o MOV.',
    upload_not_video: 'El archivo subido no es un vídeo válido.', upload_missing_chunk: 'Falta una parte del archivo (n.º :index). Vuelve a subirlo.',
    youtube_url: 'Enlace del vídeo de YouTube', youtube_invalid: 'Enlace de YouTube no válido.',
    youtube_help: 'El vídeo se reproduce directamente en ACADEXA, sin salir de la plataforma. Consejo: en YouTube, elige la visibilidad «No listado».',
    vimeo_url: 'Enlace de Vimeo', vimeo_invalid: 'Enlace de Vimeo no válido.',
    external_url: 'Enlace directo a un archivo de vídeo', external_url_help: 'URL de un archivo .mp4 alojado en otro sitio.',
    assignment_instructions: 'Instrucciones de la tarea', grading: 'Calificación', max_score: 'Nota máxima', pass_score: 'Nota para aprobar',
    assignment_completion_help: 'La lección se completa cuando asignas una nota igual o superior a la nota para aprobar.',
    tip_video: 'Sube los vídeos en MP4 (H.264): se reproduce en todos los dispositivos y está disponible sin conexión.',
    tip_youtube: 'Los vídeos de YouTube se reproducen en la plataforma, pero no se pueden descargar para usar sin conexión.',
    tip_offline: 'Añade PDF como recursos: los estudiantes pueden leerlos sin conexión.',
    tip_completion: 'Un vídeo se completa cuando el estudiante ha visto realmente al menos el 90 %.',
    resources: 'Recursos', resources_help: 'Apuntes, ejercicios, diapositivas… descargables por los estudiantes (y disponibles sin conexión).',
    resource_title: 'Título', resource_title_placeholder: 'P. ej.: Apuntes del curso (PDF)',
    resource_added: 'Recurso añadido.', resource_deleted: 'Recurso eliminado.', confirm_delete_resource: '¿Eliminar este recurso?',
    quiz: 'Cuestionario', passing_score: 'Nota para aprobar', max_attempts: 'Intentos máximos', time_limit: 'Tiempo límite',
    shuffle_questions: 'Mezclar las preguntas', show_correct_answers: 'Mostrar las respuestas correctas tras la corrección',
    save_settings: 'Guardar configuración', quiz_settings_saved: 'Configuración del cuestionario guardada.',
    timed_quiz_offline_note: 'Un cuestionario con tiempo solo puede hacerse en línea.',
    add_question: 'Añadir una pregunta', question: 'Pregunta', answer_type: 'Tipo de respuesta',
    single_answer: 'Una sola respuesta correcta', multiple_answers: 'Varias respuestas correctas', options: 'Opciones',
    tick_correct: 'marca la(s) respuesta(s) correcta(s)', add_option: 'Añadir una opción',
    question_added: 'Pregunta añadida.', question_updated: 'Pregunta actualizada.', question_deleted: 'Pregunta eliminada.',
    confirm_delete_question: '¿Eliminar esta pregunta?', no_questions: 'No hay preguntas. Añade al menos una.',
    save_to_create_quiz: 'Guarda la lección para crear el cuestionario.',
    quiz_need_correct: 'Marca al menos una respuesta correcta.', quiz_need_two_options: 'Una pregunta necesita al menos dos opciones.',
    quiz_single_one_correct: 'Una pregunta de respuesta única solo puede tener una respuesta correcta.',
    lesson_x_of_y: 'Lección :x de :y', course_content: 'Contenido del curso', offline_mode: 'Modo sin conexión',
    offline_mode_help: 'Descarga el curso para seguirlo sin conexión. El progreso se sincroniza en cuanto vuelvas a estar en línea.',
    contact_instructor: 'Escribir al instructor', course_page: 'Página del curso', course_empty: 'Este curso aún no tiene lecciones.',
    video_unavailable: 'El vídeo de esta lección aún no está disponible.', completed: 'Completado', mark_complete: 'Marcar como completada',
    watched_percent: 'Visto: :percent %', auto_complete_hint: 'se completa automáticamente al terminar el vídeo',
    watch_more: 'Mira al menos el :percent % del vídeo para completar la lección.',
    quiz_completes_lesson: 'Aprueba el cuestionario para completar esta lección.', assignment_completes_lesson: 'Se completa cuando tu tarea se califica como aprobada.',
    complete_via_assessment: 'Esta lección se completa aprobando su evaluación.', lesson_completed: '¡Lección completada!',
    lesson_locked: 'Completa las lecciones anteriores para desbloquear esta.',
    tab_lesson: 'Lección', qa: 'Preguntas y respuestas', ask_question: 'Hacer una pregunta al instructor',
    ask_question_placeholder: 'Tu pregunta sobre esta lección…', no_questions_yet: 'Aún no hay preguntas. ¡Sé el primero!',
    lesson_navigation: 'Navegación entre lecciones', get_certificate: 'Obtener mi certificado', back_to_course: 'Volver al curso',
    quiz_not_ready: 'Este cuestionario aún no está listo.',
    pass_at: 'Aprobado con :score %', attempts_unlimited: 'Intentos ilimitados',
    attempts_left: '{0} No quedan intentos|{1} Queda :count intento|[2,*] Quedan :count intentos',
    quiz_passed_best: 'Cuestionario aprobado — mejor puntuación: :score %', quiz_last_score: 'Última puntuación: :score % (aprobado con :pass %)',
    quiz_no_attempts_left: 'Has agotado todos los intentos de este cuestionario.',
    quiz_not_started: 'El temporizador no se inició. Recarga la página.',
    quiz_timed_out: 'Se acabó el tiempo: este intento no se ha contado como aprobado.',
    timed_quiz_intro: 'Este cuestionario tiene tiempo: dispondrás de :minutes minutos desde que pulses «Empezar».',
    start_quiz: 'Empezar', several_answers: 'varias respuestas', submit_answers: 'Enviar mis respuestas',
    your_work: 'Tu trabajo', your_grade: 'Tu nota', assignment_passed: 'aprobada', assignment_failed: 'por mejorar',
    assignment_waiting: 'Entregada el :date — pendiente de corrección.', view_my_submission: 'Ver mi entrega',
    resubmit: 'Entregar una nueva versión', your_answer: 'Tu respuesta', attach_file: 'Adjuntar un archivo',
    submit_assignment: 'Entregar la tarea', assignment_submitted: 'Tarea entregada. Tu instructor ha sido avisado.',
    assignment_already_passed: 'Esta tarea ya está aprobada.', assignment_empty: 'Escribe una respuesta o adjunta un archivo.',
    pass_mark_is: 'Aprobado desde :score',
    assignments: 'Tareas', to_grade: 'Por corregir', graded: 'Corregidas', all_courses: 'Todos los cursos',
    submitted_on: 'Entregada el', grade: 'Calificar', grade_submission: 'Corrección de la tarea', no_submissions: 'No hay tareas aquí.',
    score: 'Nota', feedback: 'Comentario', feedback_placeholder: 'Puntos fuertes, aspectos a mejorar…',
    save_grade: 'Guardar la nota', grade_notify_help: 'Se avisa al estudiante y la lección se completa si la nota alcanza el mínimo.',
    graded_by_on: 'Calificado por :name el :date', submission_graded: 'Nota guardada. Se ha avisado al estudiante.',
    enrolled: 'Inscritos', completion_rate: 'Tasa de finalización', avg_progress: 'Progreso medio', avg_quiz: 'Media en cuestionarios',
    search_student: 'Nombre o correo', not_started: 'Sin empezar', in_progress: 'En curso',
    export_csv: 'Exportar (CSV)', last_lesson: 'Última lección', enrolled_on: 'Inscrito el', completed_on: 'Completado el',
    no_students: 'No hay estudiantes.', completion_by_lesson: 'Finalización por lección',
    completion_by_lesson_help: 'Porcentaje de inscritos que completó cada lección: detecta dónde abandonan los estudiantes.',
    student_progress: 'Progreso del estudiante', best_score: 'Mejor puntuación', send_message: 'Enviar un mensaje',
    announcements: 'Anuncios', new_announcement: 'Nuevo anuncio',
    announcement_help: 'Se envía a todos los inscritos del curso (notificación + correo).', publish_announcement: 'Publicar el anuncio',
    announcement_sent: '{0} Anuncio publicado (aún no hay inscritos).|{1} Anuncio enviado a :count estudiante.|[2,*] Anuncio enviado a :count estudiantes.',
    announcement_deleted: 'Anuncio eliminado.', no_announcements: 'No hay anuncios.',
    unanswered: 'Sin respuesta', your_reply: 'Tu respuesta…', reply: 'Responder', reply_posted: 'Respuesta publicada.',
    no_questions_to_answer: 'No hay preguntas pendientes. ¡Bien hecho!',
    todo_submissions: '{1} :count tarea por corregir|[2,*] :count tareas por corregir', todo_submissions_help: 'Los estudiantes esperan su nota.',
    todo_questions: '{1} :count pregunta sin respuesta|[2,*] :count preguntas sin respuesta', todo_questions_help: 'Responde desde la página de preguntas.',
    messages: 'Mensajes', new_message: 'Nuevo mensaje', new_message_help: 'Escribe al instructor de uno de tus cursos.',
    no_messages: 'No hay conversaciones.', message_sent: 'Mensaje enviado.',
    mark_all_read: 'Marcar todo como leído', notifications_all_read: 'Todas las notificaciones están leídas.',
    email_notifications: 'Recibir también las notificaciones por correo', preferences_saved: 'Preferencias guardadas.',
    mail_greeting: 'Hola, :name:', mail_salutation: 'El equipo de ACADEXA — Instituto Universitario ZTF', notif_open: 'Abrir',
    notif_feedback: 'Comentario: :feedback',
    notif_certificate_subject: 'Tu certificado está listo', notif_certificate_line: '¡Enhorabuena! Has completado «:course».',
    notif_certificate_code: 'Código de verificación: :code',
    notif_course_approved_subject: 'Tu curso está publicado', notif_course_approved_line: 'Tu curso «:course» ha sido aprobado y ya está en línea.',
    notif_course_rejected_subject: 'Tu curso necesita cambios', notif_course_rejected_line: 'Tu curso «:course» no ha sido aprobado. Lee los comentarios y vuelve a enviarlo.',
    notif_course_submitted_subject: 'Curso por revisar', notif_course_submitted_line: ':instructor ha enviado «:course» para revisión.',
    notif_application_approved_subject: 'Solicitud aceptada', notif_application_approved_line: 'Ya eres instructor en ACADEXA. ¡Crea tu primer curso!',
    notif_application_rejected_subject: 'Solicitud de instructor', notif_application_rejected_line: 'Tu solicitud no ha sido aceptada por ahora.',
    notif_assignment_submitted_subject: 'Nueva tarea por corregir', notif_assignment_submitted_line: ':student ha entregado la tarea «:lesson».',
    notif_assignment_graded_subject: 'Tu tarea está corregida', notif_assignment_graded_line: 'Tarea «:lesson»: :score / :max.',
    notif_question_subject: 'Nueva pregunta de un estudiante', notif_question_line: ':name ha hecho una pregunta en «:lesson».',
    notif_reply_subject: 'Respuesta a tu pregunta', notif_reply_line: ':name ha respondido a tu pregunta en «:lesson».',
    notif_announcement_subject: 'Anuncio — :course',
    notif_message_subject: 'Nuevo mensaje de :name', notif_message_line: ':name te ha escrito: «:subject».',
    notif_trial_subject: 'Tu prueba termina pronto',
    notif_trial_line: '{1} Te queda :days día de acceso gratuito.|[2,*] Te quedan :days días de acceso gratuito.',
    notif_welcome_subject: '¡Bienvenido a :site!', notif_browse_courses: 'Explorar los cursos',
    notif_welcome_line: '{1} Tu cuenta está lista: tienes :days día de acceso gratuito a todos los cursos.|[2,*] Tu cuenta está lista: tienes :days días de acceso gratuito a todos los cursos.',
    install_app: 'Instalar la aplicación', offline_courses: 'Cursos sin conexión', back_online: 'Versión en línea',
    offline_needs_js: 'Activa JavaScript para usar tus cursos sin conexión.',
    pwa_description: 'Sigue tus cursos del Instituto Universitario ZTF, incluso sin conexión.',
    preview_cta_title: '¿Quieres ir más lejos?', preview_cta_help: 'Inscríbete para acceder a todas las lecciones y obtener el certificado.',
    review_requires_completion: 'Completa el curso para dejar una reseña.',
    no_enrollments: 'Aún no estás inscrito en ningún curso.',
    minutes_short: ':count min', hours_short: ':count h', hours_minutes_short: ':hours h :minutes min',
    byte_units: ['B', 'KB', 'MB', 'GB', 'TB'], decimal_separator: ',',
    role_student: 'Estudiante', role_instructor: 'Instructor', role_admin: 'Administrador', role_super_admin: 'Superadministrador',
    instructor_status_none: 'Ninguno', instructor_status_pending: 'Pendiente', instructor_status_confirmed: 'Confirmado', instructor_status_rejected: 'Rechazado',
    application_status_pending: 'Pendiente', application_status_approved: 'Aceptada', application_status_rejected: 'Rechazada',
    audience_all: 'Todos', audience_students: 'Estudiantes', audience_instructors: 'Instructores',
    js: {
        byte_units: ['B', 'KB', 'MB', 'GB'],
        seconds_short: ':count s', minutes_short: ':count min', hours_minutes_short: ':hours h :minutes min',
        offline_banner: 'Estás sin conexión.', offline_open: 'Abrir mis cursos sin conexión',
        syncing: 'Sincronizando :count acción(es) realizada(s) sin conexión…', synced: ':count acción(es) sincronizada(s)',
        offline_download: 'Descargar para usar sin conexión', offline_available: 'Disponible sin conexión',
        offline_remove: 'Eliminar', offline_remove_confirm: 'Confirmar la eliminación', offline_update: 'Actualizar',
        offline_unsupported: 'Tu navegador no admite el modo sin conexión. Usa Chrome, Edge, Firefox o Safari recientes.',
        offline_need_network: 'Se necesita conexión a Internet para descargar.',
        offline_preparing: 'Preparando…', offline_progress: ':pct % — :loaded / :total (archivo :file/:files)',
        offline_done: 'Curso disponible sin conexión', offline_cancelled: 'Descarga cancelada.',
        offline_failed: 'La descarga ha fallado.', offline_quota: 'Espacio insuficiente: se necesitan :needed, quedan :available.',
        offline_courses: 'Cursos sin conexión', offline_empty_title: 'No hay cursos descargados',
        offline_empty_help: 'Con conexión, abre «Mis cursos» y pulsa «Descargar para usar sin conexión». Después podrás seguir el curso sin Internet.',
        offline_home_help: 'Estos cursos están guardados en este dispositivo. Tu progreso se enviará automáticamente al recuperar la conexión.',
        go_my_courses: 'Ir a mis cursos', online: 'En línea', offline: 'Sin conexión',
        pending_sync: ':count pendiente(s) de sincronizar', progress_pct: ':pct % completado', open: 'Abrir',
        module: 'Módulo', previous: 'Anterior', next: 'Siguiente', resources: 'Recursos',
        online_only: 'en línea', course_empty: 'Este curso no tiene lecciones.',
        youtube_needs_network: 'Los vídeos de YouTube necesitan conexión a Internet.',
        video_needs_network: 'Este vídeo necesita conexión a Internet.',
        assignment_online_only: 'Las tareas se entregan en línea. Prepara tu trabajo y envíalo cuando vuelvas a tener conexión.',
        offline_quiz_help: 'Sin conexión, tus respuestas se guardan y se corrigen al reconectar (aprobado con :score %).',
        quiz_saved_offline: 'Respuestas guardadas: se corregirán en cuanto vuelvas a tener conexión.',
        saved_offline: 'Guardado en el dispositivo: se sincronizará al recuperar la conexión.',
        next_available: 'Siguiente lección desbloqueada.', lesson_completed: '¡Lección completada!',
        mark_complete: 'Marcar como completada', completed: 'Completado',
        watched_percent: 'Visto: :percent %', auto_complete_hint: 'se completa automáticamente al terminar el vídeo',
        certificate_ready: '¡Curso completado! Tu certificado está listo.', resumed_at: 'Reanudado en :time',
        next_in: 'Siguiente lección en :seconds s…', go_now: 'Ir ahora', cancel: 'Cancelar',
        youtube_unreachable: 'No se pudo cargar el vídeo de YouTube. Comprueba tu conexión.',
        timed_quiz_needs_network: 'Un cuestionario con tiempo necesita conexión a Internet.',
        time_up: 'Se acabó el tiempo: enviando tus respuestas.',
        unanswered_confirm: ':count pregunta(s) sin responder. Pulsa «Enviar» de nuevo para enviar igualmente.',
        sending: 'Enviando…', submit_answers: 'Enviar mis respuestas', error: 'Se ha producido un error. Inténtalo de nuevo.',
        correct: 'Correcta', incorrect: 'Incorrecta', retry: 'Intentar de nuevo',
        score_line: 'Puntuación: :score % (:correct/:total)',
        pause: 'Pausa', resume: 'Reanudar', upload_eta: 'Tiempo restante ≈ :time',
        upload_resuming: 'Reanudando la subida en el :pct %.', upload_retry_hint: 'vuelve a elegir el mismo archivo para reanudar.',
        upload_bad_extension: 'Formato no admitido. Usa MP4, WebM o MOV.', upload_too_large: 'Archivo demasiado grande (máximo :max MB).',
        youtube_invalid: 'Enlace de YouTube no válido.', option: 'Opción', correct_answer: 'Respuesta correcta', delete: 'Eliminar',
        quiz_need_correct: 'Marca al menos una respuesta correcta.', quiz_need_two_options: 'Una pregunta necesita al menos dos opciones.',
    },
};
