// "learn" group — sign in with Google, e-mail confirmation code, two-factor authentication and profile.
// Merged into learn.cjs. Build: node scripts/write-group.cjs learn resources/lang-src/learn.cjs
module.exports = {
    en: {
        or: 'or',
        continue_with_google: 'Continue with Google',
        google_unavailable: 'Sign in with Google is not available yet.',
        google_failed: 'Google sign-in failed or was cancelled. Please try again.',
        google_email_unverified: 'Your Google account has no verified e-mail address.',
        google_admin_refused: 'Administrator accounts must sign in through the administration login.',
        google_registration_closed: 'Registrations are currently closed.',
        google_account: 'Google account',
        google_linked: 'Your Google account is linked: you can sign in with Google.',
        google_not_linked: 'Sign in once with "Continue with Google" using this e-mail address to link your Google account.',
        google_unlink: 'Unlink',
        google_unlink_confirm: 'Unlink your Google account? You will sign in with your password.',
        google_unlink_needs_password: 'Choose a password first, otherwise you could no longer sign in.',
        google_unlinked: 'Google account unlinked.',
        confirm_email_title: 'Confirm your e-mail address',
        confirm_email_help: 'We sent a 6-digit code to :email. Enter it to activate your account.',
        two_factor_title: 'Two-step verification',
        two_factor_app_help: 'Enter the 6-digit code shown by your authenticator app.',
        two_factor_email_help: 'We sent a 6-digit code to :email. Enter it to sign in.',
        code_label: 'Verification code',
        verify: 'Verify',
        resend_code: 'Send a new code',
        code_wait: 'New code possible in :seconds s',
        code_resent: 'A new code has been sent.',
        code_sent_to: 'A code has been sent to :email.',
        lost_device_help: 'Lost your phone? Contact the support.',
        code_mail_subject_register: ':code is your ACADEXXA confirmation code',
        code_mail_subject_login: ':code is your ACADEXXA sign-in code',
        code_mail_subject_setup: ':code is your ACADEXXA security code',
        code_mail_intro_register: 'Welcome! Use this code to confirm your e-mail address and activate your account:',
        code_mail_intro_login: 'Use this code to finish signing in:',
        code_mail_intro_setup: 'Use this code to confirm the change of your security settings:',
        code_mail_expiry: 'This code expires in :minutes minutes.',
        code_mail_ignore: 'If you did not request it, ignore this message and nobody will be able to access your account.',
        setting_registration_code: 'Confirm new accounts with a code sent by e-mail (requires a working e-mail configuration)',
        profile_information: 'Personal information',
        remove_photo: 'Remove the photo',
        email_change_help: 'To change your e-mail address, contact the support.',
        email_notifications: 'Also receive my notifications by e-mail',
        security: 'Security',
        choose_password: 'Choose a password',
        choose_password_help: 'Your account was created with Google. Choose a password to also sign in with your e-mail address.',
        save_password: 'Save the password',
        password_saved: 'Password saved.',
        two_factor_intro: 'Protect your account: after your password (or Google), a code will be asked for at each sign-in.',
        two_factor_app: 'Authenticator app',
        two_factor_app_intro: 'Scan this QR code with Google Authenticator, Microsoft Authenticator or Authy, then enter the code shown.',
        two_factor_email: 'Code by e-mail',
        two_factor_email_intro: 'A code is sent to :email at each sign-in.',
        two_factor_on_app: 'Two-step verification is on (authenticator app).',
        two_factor_on_email: 'Two-step verification is on (code by e-mail).',
        two_factor_admin_help: 'Administrator accounts use an authenticator app, managed on the security page of the administration.',
        code_from_app: 'Code from the app',
        code_from_email: 'Code received by e-mail',
        send_me_a_code: 'Send me a code',
    },
    fr: {
        or: 'ou',
        continue_with_google: 'Continuer avec Google',
        google_unavailable: 'La connexion avec Google n’est pas encore disponible.',
        google_failed: 'La connexion avec Google a échoué ou a été annulée. Réessayez.',
        google_email_unverified: 'Votre compte Google n’a pas d’adresse e-mail vérifiée.',
        google_admin_refused: 'Les comptes administrateurs se connectent par la page de connexion de l’administration.',
        google_registration_closed: 'Les inscriptions sont actuellement fermées.',
        google_account: 'Compte Google',
        google_linked: 'Votre compte Google est associé : vous pouvez vous connecter avec Google.',
        google_not_linked: 'Connectez-vous une fois avec « Continuer avec Google » en utilisant cette adresse e-mail pour associer votre compte Google.',
        google_unlink: 'Dissocier',
        google_unlink_confirm: 'Dissocier votre compte Google ? Vous vous connecterez avec votre mot de passe.',
        google_unlink_needs_password: 'Choisissez d’abord un mot de passe, sinon vous ne pourriez plus vous connecter.',
        google_unlinked: 'Compte Google dissocié.',
        confirm_email_title: 'Confirmez votre adresse e-mail',
        confirm_email_help: 'Nous avons envoyé un code à 6 chiffres à :email. Saisissez-le pour activer votre compte.',
        two_factor_title: 'Vérification en deux étapes',
        two_factor_app_help: 'Saisissez le code à 6 chiffres affiché par votre application d’authentification.',
        two_factor_email_help: 'Nous avons envoyé un code à 6 chiffres à :email. Saisissez-le pour vous connecter.',
        code_label: 'Code de vérification',
        verify: 'Vérifier',
        resend_code: 'Envoyer un nouveau code',
        code_wait: 'Nouveau code possible dans :seconds s',
        code_resent: 'Un nouveau code a été envoyé.',
        code_sent_to: 'Un code a été envoyé à :email.',
        lost_device_help: 'Téléphone perdu ? Contactez le support.',
        code_mail_subject_register: ':code est votre code de confirmation ACADEXXA',
        code_mail_subject_login: ':code est votre code de connexion ACADEXXA',
        code_mail_subject_setup: ':code est votre code de sécurité ACADEXXA',
        code_mail_intro_register: 'Bienvenue ! Utilisez ce code pour confirmer votre adresse e-mail et activer votre compte :',
        code_mail_intro_login: 'Utilisez ce code pour terminer votre connexion :',
        code_mail_intro_setup: 'Utilisez ce code pour confirmer la modification de vos réglages de sécurité :',
        code_mail_expiry: 'Ce code expire dans :minutes minutes.',
        code_mail_ignore: 'Si vous n’êtes pas à l’origine de cette demande, ignorez ce message : personne ne pourra accéder à votre compte.',
        setting_registration_code: 'Confirmer les nouveaux comptes par un code envoyé par e-mail (nécessite une configuration e-mail fonctionnelle)',
        profile_information: 'Informations personnelles',
        remove_photo: 'Supprimer la photo',
        email_change_help: 'Pour changer d’adresse e-mail, contactez le support.',
        email_notifications: 'Recevoir aussi mes notifications par e-mail',
        security: 'Sécurité',
        choose_password: 'Choisir un mot de passe',
        choose_password_help: 'Votre compte a été créé avec Google. Choisissez un mot de passe pour pouvoir aussi vous connecter avec votre adresse e-mail.',
        save_password: 'Enregistrer le mot de passe',
        password_saved: 'Mot de passe enregistré.',
        two_factor_intro: 'Protégez votre compte : après votre mot de passe (ou Google), un code vous sera demandé à chaque connexion.',
        two_factor_app: 'Application d’authentification',
        two_factor_app_intro: 'Scannez ce QR code avec Google Authenticator, Microsoft Authenticator ou Authy, puis saisissez le code affiché.',
        two_factor_email: 'Code par e-mail',
        two_factor_email_intro: 'Un code est envoyé à :email à chaque connexion.',
        two_factor_on_app: 'La vérification en deux étapes est activée (application d’authentification).',
        two_factor_on_email: 'La vérification en deux étapes est activée (code par e-mail).',
        two_factor_admin_help: 'Les comptes administrateurs utilisent une application d’authentification, gérée sur la page Sécurité de l’administration.',
        code_from_app: 'Code de l’application',
        code_from_email: 'Code reçu par e-mail',
        send_me_a_code: 'M’envoyer un code',
    },
    es: {
        or: 'o',
        continue_with_google: 'Continuar con Google',
        google_unavailable: 'El inicio de sesión con Google aún no está disponible.',
        google_failed: 'El inicio de sesión con Google falló o se canceló. Inténtalo de nuevo.',
        google_email_unverified: 'Tu cuenta de Google no tiene una dirección de correo verificada.',
        google_admin_refused: 'Las cuentas de administrador inician sesión por la página de acceso de la administración.',
        google_registration_closed: 'Las inscripciones están cerradas por ahora.',
        google_account: 'Cuenta de Google',
        google_linked: 'Tu cuenta de Google está vinculada: puedes iniciar sesión con Google.',
        google_not_linked: 'Inicia sesión una vez con «Continuar con Google» usando esta dirección de correo para vincular tu cuenta de Google.',
        google_unlink: 'Desvincular',
        google_unlink_confirm: '¿Desvincular tu cuenta de Google? Iniciarás sesión con tu contraseña.',
        google_unlink_needs_password: 'Elige primero una contraseña; si no, ya no podrías iniciar sesión.',
        google_unlinked: 'Cuenta de Google desvinculada.',
        confirm_email_title: 'Confirma tu dirección de correo',
        confirm_email_help: 'Hemos enviado un código de 6 cifras a :email. Introdúcelo para activar tu cuenta.',
        two_factor_title: 'Verificación en dos pasos',
        two_factor_app_help: 'Introduce el código de 6 cifras que muestra tu aplicación de autenticación.',
        two_factor_email_help: 'Hemos enviado un código de 6 cifras a :email. Introdúcelo para iniciar sesión.',
        code_label: 'Código de verificación',
        verify: 'Verificar',
        resend_code: 'Enviar un código nuevo',
        code_wait: 'Nuevo código posible en :seconds s',
        code_resent: 'Se ha enviado un código nuevo.',
        code_sent_to: 'Se ha enviado un código a :email.',
        lost_device_help: '¿Perdiste tu teléfono? Contacta con el soporte.',
        code_mail_subject_register: ':code es tu código de confirmación de ACADEXXA',
        code_mail_subject_login: ':code es tu código de inicio de sesión de ACADEXXA',
        code_mail_subject_setup: ':code es tu código de seguridad de ACADEXXA',
        code_mail_intro_register: '¡Bienvenido! Usa este código para confirmar tu dirección de correo y activar tu cuenta:',
        code_mail_intro_login: 'Usa este código para terminar de iniciar sesión:',
        code_mail_intro_setup: 'Usa este código para confirmar el cambio de tus ajustes de seguridad:',
        code_mail_expiry: 'Este código caduca en :minutes minutos.',
        code_mail_ignore: 'Si no lo has solicitado, ignora este mensaje: nadie podrá acceder a tu cuenta.',
        setting_registration_code: 'Confirmar las cuentas nuevas con un código enviado por correo (requiere una configuración de correo operativa)',
        profile_information: 'Información personal',
        remove_photo: 'Eliminar la foto',
        email_change_help: 'Para cambiar tu dirección de correo, contacta con el soporte.',
        email_notifications: 'Recibir también mis notificaciones por correo',
        security: 'Seguridad',
        choose_password: 'Elegir una contraseña',
        choose_password_help: 'Tu cuenta se creó con Google. Elige una contraseña para poder iniciar sesión también con tu correo.',
        save_password: 'Guardar la contraseña',
        password_saved: 'Contraseña guardada.',
        two_factor_intro: 'Protege tu cuenta: después de tu contraseña (o Google), se te pedirá un código en cada inicio de sesión.',
        two_factor_app: 'Aplicación de autenticación',
        two_factor_app_intro: 'Escanea este código QR con Google Authenticator, Microsoft Authenticator o Authy y luego introduce el código mostrado.',
        two_factor_email: 'Código por correo',
        two_factor_email_intro: 'Se envía un código a :email en cada inicio de sesión.',
        two_factor_on_app: 'La verificación en dos pasos está activada (aplicación de autenticación).',
        two_factor_on_email: 'La verificación en dos pasos está activada (código por correo).',
        two_factor_admin_help: 'Las cuentas de administrador usan una aplicación de autenticación, gestionada en la página de seguridad de la administración.',
        code_from_app: 'Código de la aplicación',
        code_from_email: 'Código recibido por correo',
        send_me_a_code: 'Enviarme un código',
    },
    pt: {
        or: 'ou',
        continue_with_google: 'Continuar com o Google',
        google_unavailable: 'O início de sessão com o Google ainda não está disponível.',
        google_failed: 'O início de sessão com o Google falhou ou foi cancelado. Tente novamente.',
        google_email_unverified: 'A sua conta Google não tem um endereço de e-mail verificado.',
        google_admin_refused: 'As contas de administrador iniciam sessão pela página de acesso da administração.',
        google_registration_closed: 'As inscrições estão fechadas de momento.',
        google_account: 'Conta Google',
        google_linked: 'A sua conta Google está associada: pode iniciar sessão com o Google.',
        google_not_linked: 'Inicie sessão uma vez com «Continuar com o Google» usando este endereço de e-mail para associar a sua conta Google.',
        google_unlink: 'Desassociar',
        google_unlink_confirm: 'Desassociar a sua conta Google? Passará a iniciar sessão com a sua palavra-passe.',
        google_unlink_needs_password: 'Escolha primeiro uma palavra-passe; caso contrário, deixaria de conseguir iniciar sessão.',
        google_unlinked: 'Conta Google desassociada.',
        confirm_email_title: 'Confirme o seu endereço de e-mail',
        confirm_email_help: 'Enviámos um código de 6 dígitos para :email. Introduza-o para ativar a sua conta.',
        two_factor_title: 'Verificação em dois passos',
        two_factor_app_help: 'Introduza o código de 6 dígitos mostrado pela sua aplicação de autenticação.',
        two_factor_email_help: 'Enviámos um código de 6 dígitos para :email. Introduza-o para iniciar sessão.',
        code_label: 'Código de verificação',
        verify: 'Verificar',
        resend_code: 'Enviar um novo código',
        code_wait: 'Novo código possível dentro de :seconds s',
        code_resent: 'Foi enviado um novo código.',
        code_sent_to: 'Foi enviado um código para :email.',
        lost_device_help: 'Perdeu o telemóvel? Contacte o suporte.',
        code_mail_subject_register: ':code é o seu código de confirmação ACADEXXA',
        code_mail_subject_login: ':code é o seu código de início de sessão ACADEXXA',
        code_mail_subject_setup: ':code é o seu código de segurança ACADEXXA',
        code_mail_intro_register: 'Bem-vindo! Use este código para confirmar o seu endereço de e-mail e ativar a sua conta:',
        code_mail_intro_login: 'Use este código para concluir o início de sessão:',
        code_mail_intro_setup: 'Use este código para confirmar a alteração das suas definições de segurança:',
        code_mail_expiry: 'Este código expira dentro de :minutes minutos.',
        code_mail_ignore: 'Se não fez este pedido, ignore esta mensagem: ninguém poderá aceder à sua conta.',
        setting_registration_code: 'Confirmar as novas contas com um código enviado por e-mail (requer uma configuração de e-mail funcional)',
        profile_information: 'Informações pessoais',
        remove_photo: 'Remover a foto',
        email_change_help: 'Para alterar o seu endereço de e-mail, contacte o suporte.',
        email_notifications: 'Receber também as minhas notificações por e-mail',
        security: 'Segurança',
        choose_password: 'Escolher uma palavra-passe',
        choose_password_help: 'A sua conta foi criada com o Google. Escolha uma palavra-passe para poder iniciar sessão também com o seu e-mail.',
        save_password: 'Guardar a palavra-passe',
        password_saved: 'Palavra-passe guardada.',
        two_factor_intro: 'Proteja a sua conta: depois da palavra-passe (ou do Google), será pedido um código em cada início de sessão.',
        two_factor_app: 'Aplicação de autenticação',
        two_factor_app_intro: 'Leia este código QR com o Google Authenticator, Microsoft Authenticator ou Authy e introduza o código mostrado.',
        two_factor_email: 'Código por e-mail',
        two_factor_email_intro: 'É enviado um código para :email em cada início de sessão.',
        two_factor_on_app: 'A verificação em dois passos está ativada (aplicação de autenticação).',
        two_factor_on_email: 'A verificação em dois passos está ativada (código por e-mail).',
        two_factor_admin_help: 'As contas de administrador usam uma aplicação de autenticação, gerida na página de segurança da administração.',
        code_from_app: 'Código da aplicação',
        code_from_email: 'Código recebido por e-mail',
        send_me_a_code: 'Enviar-me um código',
    },
    zh: {
        or: '或',
        continue_with_google: '使用 Google 继续',
        google_unavailable: 'Google 登录暂不可用。',
        google_failed: 'Google 登录失败或已取消，请重试。',
        google_email_unverified: '你的 Google 账户没有已验证的电子邮箱。',
        google_admin_refused: '管理员账户请通过管理后台登录页面登录。',
        google_registration_closed: '目前暂停注册。',
        google_account: 'Google 账户',
        google_linked: '你的 Google 账户已关联：可以使用 Google 登录。',
        google_not_linked: '使用此邮箱通过“使用 Google 继续”登录一次，即可关联你的 Google 账户。',
        google_unlink: '取消关联',
        google_unlink_confirm: '取消关联 Google 账户吗？之后请使用密码登录。',
        google_unlink_needs_password: '请先设置密码，否则将无法再登录。',
        google_unlinked: '已取消关联 Google 账户。',
        confirm_email_title: '确认你的电子邮箱',
        confirm_email_help: '我们已向 :email 发送 6 位验证码。输入验证码即可激活账户。',
        two_factor_title: '两步验证',
        two_factor_app_help: '请输入身份验证器应用显示的 6 位验证码。',
        two_factor_email_help: '我们已向 :email 发送 6 位验证码。输入验证码即可登录。',
        code_label: '验证码',
        verify: '验证',
        resend_code: '重新发送验证码',
        code_wait: ':seconds 秒后可重新发送',
        code_resent: '新的验证码已发送。',
        code_sent_to: '验证码已发送至 :email。',
        lost_device_help: '手机丢失？请联系客服。',
        code_mail_subject_register: ':code 是你的 ACADEXXA 确认码',
        code_mail_subject_login: ':code 是你的 ACADEXXA 登录码',
        code_mail_subject_setup: ':code 是你的 ACADEXXA 安全码',
        code_mail_intro_register: '欢迎！请使用此验证码确认你的电子邮箱并激活账户：',
        code_mail_intro_login: '请使用此验证码完成登录：',
        code_mail_intro_setup: '请使用此验证码确认安全设置的更改：',
        code_mail_expiry: '此验证码将在 :minutes 分钟后失效。',
        code_mail_ignore: '如果这不是你本人的操作，请忽略此邮件，任何人都无法访问你的账户。',
        setting_registration_code: '通过电子邮件验证码确认新账户（需要可用的邮件配置）',
        profile_information: '个人信息',
        remove_photo: '删除照片',
        email_change_help: '如需更改电子邮箱，请联系客服。',
        email_notifications: '同时通过电子邮件接收通知',
        security: '安全',
        choose_password: '设置密码',
        choose_password_help: '你的账户是通过 Google 创建的。设置密码后，也可以使用电子邮箱登录。',
        save_password: '保存密码',
        password_saved: '密码已保存。',
        two_factor_intro: '保护你的账户：每次登录时，在输入密码（或使用 Google）之后还需要输入验证码。',
        two_factor_app: '身份验证器应用',
        two_factor_app_intro: '使用 Google Authenticator、Microsoft Authenticator 或 Authy 扫描此二维码，然后输入显示的验证码。',
        two_factor_email: '邮件验证码',
        two_factor_email_intro: '每次登录时都会向 :email 发送验证码。',
        two_factor_on_app: '两步验证已开启（身份验证器应用）。',
        two_factor_on_email: '两步验证已开启（邮件验证码）。',
        two_factor_admin_help: '管理员账户使用身份验证器应用，在管理后台的安全页面中设置。',
        code_from_app: '应用中的验证码',
        code_from_email: '邮件中的验证码',
        send_me_a_code: '给我发送验证码',
    },
    ar: {
        or: 'أو',
        continue_with_google: 'المتابعة باستخدام Google',
        google_unavailable: 'تسجيل الدخول باستخدام Google غير متاح بعد.',
        google_failed: 'فشل تسجيل الدخول باستخدام Google أو تم إلغاؤه. أعد المحاولة.',
        google_email_unverified: 'لا يحتوي حسابك في Google على بريد إلكتروني مُتحقَّق منه.',
        google_admin_refused: 'تسجّل حسابات المشرفين الدخول من صفحة دخول الإدارة.',
        google_registration_closed: 'التسجيل مغلق حاليًا.',
        google_account: 'حساب Google',
        google_linked: 'حسابك في Google مرتبط: يمكنك تسجيل الدخول باستخدام Google.',
        google_not_linked: 'سجّل الدخول مرة واحدة عبر «المتابعة باستخدام Google» بهذا البريد الإلكتروني لربط حسابك في Google.',
        google_unlink: 'إلغاء الربط',
        google_unlink_confirm: 'إلغاء ربط حسابك في Google؟ ستسجّل الدخول بكلمة المرور.',
        google_unlink_needs_password: 'اختر كلمة مرور أولًا، وإلا فلن تتمكن من تسجيل الدخول.',
        google_unlinked: 'تم إلغاء ربط حساب Google.',
        confirm_email_title: 'أكّد بريدك الإلكتروني',
        confirm_email_help: 'أرسلنا رمزًا من 6 أرقام إلى :email. أدخله لتفعيل حسابك.',
        two_factor_title: 'التحقق بخطوتين',
        two_factor_app_help: 'أدخل الرمز المكوّن من 6 أرقام الذي يعرضه تطبيق المصادقة.',
        two_factor_email_help: 'أرسلنا رمزًا من 6 أرقام إلى :email. أدخله لتسجيل الدخول.',
        code_label: 'رمز التحقق',
        verify: 'تحقّق',
        resend_code: 'إرسال رمز جديد',
        code_wait: 'يمكن طلب رمز جديد بعد :seconds ثانية',
        code_resent: 'تم إرسال رمز جديد.',
        code_sent_to: 'تم إرسال رمز إلى :email.',
        lost_device_help: 'فقدت هاتفك؟ تواصل مع الدعم.',
        code_mail_subject_register: 'رمز التأكيد الخاص بك في ACADEXXA هو :code',
        code_mail_subject_login: 'رمز الدخول الخاص بك في ACADEXXA هو :code',
        code_mail_subject_setup: 'رمز الأمان الخاص بك في ACADEXXA هو :code',
        code_mail_intro_register: 'مرحبًا! استخدم هذا الرمز لتأكيد بريدك الإلكتروني وتفعيل حسابك:',
        code_mail_intro_login: 'استخدم هذا الرمز لإكمال تسجيل الدخول:',
        code_mail_intro_setup: 'استخدم هذا الرمز لتأكيد تغيير إعدادات الأمان:',
        code_mail_expiry: 'تنتهي صلاحية هذا الرمز بعد :minutes دقيقة.',
        code_mail_ignore: 'إذا لم تطلب هذا الرمز فتجاهل هذه الرسالة، ولن يتمكن أحد من الوصول إلى حسابك.',
        setting_registration_code: 'تأكيد الحسابات الجديدة برمز يُرسل بالبريد الإلكتروني (يتطلب إعداد بريد يعمل)',
        profile_information: 'المعلومات الشخصية',
        remove_photo: 'حذف الصورة',
        email_change_help: 'لتغيير بريدك الإلكتروني، تواصل مع الدعم.',
        email_notifications: 'تلقي إشعاراتي بالبريد الإلكتروني أيضًا',
        security: 'الأمان',
        choose_password: 'اختيار كلمة مرور',
        choose_password_help: 'أُنشئ حسابك باستخدام Google. اختر كلمة مرور لتتمكن أيضًا من الدخول ببريدك الإلكتروني.',
        save_password: 'حفظ كلمة المرور',
        password_saved: 'تم حفظ كلمة المرور.',
        two_factor_intro: 'احمِ حسابك: بعد كلمة المرور (أو Google) سيُطلب منك رمز عند كل تسجيل دخول.',
        two_factor_app: 'تطبيق المصادقة',
        two_factor_app_intro: 'امسح رمز QR هذا باستخدام Google Authenticator أو Microsoft Authenticator أو Authy، ثم أدخل الرمز المعروض.',
        two_factor_email: 'رمز عبر البريد الإلكتروني',
        two_factor_email_intro: 'يُرسل رمز إلى :email عند كل تسجيل دخول.',
        two_factor_on_app: 'التحقق بخطوتين مفعّل (تطبيق المصادقة).',
        two_factor_on_email: 'التحقق بخطوتين مفعّل (رمز عبر البريد الإلكتروني).',
        two_factor_admin_help: 'تستخدم حسابات المشرفين تطبيق مصادقة يُدار من صفحة الأمان في الإدارة.',
        code_from_app: 'الرمز من التطبيق',
        code_from_email: 'الرمز المستلم بالبريد',
        send_me_a_code: 'أرسل لي رمزًا',
    },
};
