// "learn" group — Admin → Settings → E-mails: Brevo API key, sender, queue. Merged into learn.cjs.
module.exports = {
    en: {
        mail_key: 'Brevo API key',
        mail_key_help: 'In Brevo: SMTP & API → API keys → Generate a new API key. It starts with "xkeysib-" and is stored encrypted.',
        mail_key_saved: 'A key is saved (:hint). Leave the field empty to keep it.',
        mail_key_server: 'A key is set in the server variables (BREVO_API_KEY). A key saved here replaces it.',
        mail_key_remove: 'Remove the saved key',
        mail_key_is_smtp: 'This is an SMTP key (xsmtpsib-…). Create an API key in Brevo → SMTP & API → API keys: it starts with "xkeysib-".',
        mail_key_format: 'A Brevo API key starts with "xkeysib-".',
        mail_key_rejected: 'Brevo refuses this key: :error',
        mail_key_valid: 'E-mail settings saved. Brevo accepts the key (account: :account).',
        mail_key_unchecked: 'E-mail settings saved, but Brevo could not be reached to check the key. Send a test e-mail.',
        mail_saved: 'E-mail settings saved.',
        mail_from_address: 'Sender address',
        mail_from_address_help: 'It must be validated in Brevo → Senders, domains & dedicated IPs.',
        mail_from_name: 'Sender name',
        mail_queue_pending: 'Waiting to be sent',
        mail_queue_stuck: 'Notifications have been waiting for :minutes min: the scheduler service (php artisan schedule:work) is not running.',
        mail_queue_failed: 'Failed',
        mail_queue_last_error: 'Last error: :error',
        mail_queue_retry: 'Send the failed ones again',
        mail_queue_retried: 'The failed notifications are back in the queue.',
    },
    fr: {
        mail_key: 'Clé API Brevo',
        mail_key_help: 'Dans Brevo : SMTP et API → Clés API → Générer une nouvelle clé API. Elle commence par « xkeysib- » et elle est enregistrée chiffrée.',
        mail_key_saved: 'Une clé est enregistrée (:hint). Laissez le champ vide pour la conserver.',
        mail_key_server: 'Une clé est définie dans les variables du serveur (BREVO_API_KEY). Une clé enregistrée ici la remplace.',
        mail_key_remove: 'Supprimer la clé enregistrée',
        mail_key_is_smtp: 'Ceci est une clé SMTP (xsmtpsib-…). Créez une clé API dans Brevo → SMTP et API → Clés API : elle commence par « xkeysib- ».',
        mail_key_format: 'Une clé API Brevo commence par « xkeysib- ».',
        mail_key_rejected: 'Brevo refuse cette clé : :error',
        mail_key_valid: 'Réglages des e-mails enregistrés. Brevo accepte la clé (compte : :account).',
        mail_key_unchecked: 'Réglages des e-mails enregistrés, mais Brevo n’a pas pu être joint pour vérifier la clé. Envoyez un e-mail de test.',
        mail_saved: 'Réglages des e-mails enregistrés.',
        mail_from_address: 'Adresse d’expédition',
        mail_from_address_help: 'Elle doit être validée dans Brevo → Expéditeurs, domaines et IP dédiées.',
        mail_from_name: 'Nom de l’expéditeur',
        mail_queue_pending: 'En attente d’envoi',
        mail_queue_stuck: 'Des notifications attendent depuis :minutes min : le service planificateur (php artisan schedule:work) ne tourne pas.',
        mail_queue_failed: 'En échec',
        mail_queue_last_error: 'Dernière erreur : :error',
        mail_queue_retry: 'Renvoyer les envois en échec',
        mail_queue_retried: 'Les envois en échec ont été remis dans la file d’attente.',
    },
    es: {
        mail_key: 'Clave API de Brevo',
        mail_key_help: 'En Brevo: SMTP y API → Claves API → Generar una nueva clave API. Empieza por «xkeysib-» y se guarda cifrada.',
        mail_key_saved: 'Hay una clave guardada (:hint). Deja el campo vacío para conservarla.',
        mail_key_server: 'Hay una clave definida en las variables del servidor (BREVO_API_KEY). Una clave guardada aquí la sustituye.',
        mail_key_remove: 'Eliminar la clave guardada',
        mail_key_is_smtp: 'Esta es una clave SMTP (xsmtpsib-…). Crea una clave API en Brevo → SMTP y API → Claves API: empieza por «xkeysib-».',
        mail_key_format: 'Una clave API de Brevo empieza por «xkeysib-».',
        mail_key_rejected: 'Brevo rechaza esta clave: :error',
        mail_key_valid: 'Ajustes de correo guardados. Brevo acepta la clave (cuenta: :account).',
        mail_key_unchecked: 'Ajustes de correo guardados, pero no se pudo contactar con Brevo para comprobar la clave. Envía un correo de prueba.',
        mail_saved: 'Ajustes de correo guardados.',
        mail_from_address: 'Dirección del remitente',
        mail_from_address_help: 'Debe estar validada en Brevo → Remitentes, dominios e IP dedicadas.',
        mail_from_name: 'Nombre del remitente',
        mail_queue_pending: 'Pendientes de envío',
        mail_queue_stuck: 'Hay notificaciones esperando desde hace :minutes min: el servicio planificador (php artisan schedule:work) no está en marcha.',
        mail_queue_failed: 'Fallidos',
        mail_queue_last_error: 'Último error: :error',
        mail_queue_retry: 'Reenviar los envíos fallidos',
        mail_queue_retried: 'Los envíos fallidos han vuelto a la cola.',
    },
    pt: {
        mail_key: 'Chave API da Brevo',
        mail_key_help: 'Na Brevo: SMTP e API → Chaves API → Gerar uma nova chave API. Começa por «xkeysib-» e é guardada cifrada.',
        mail_key_saved: 'Há uma chave guardada (:hint). Deixe o campo vazio para a manter.',
        mail_key_server: 'Há uma chave definida nas variáveis do servidor (BREVO_API_KEY). Uma chave guardada aqui substitui-a.',
        mail_key_remove: 'Remover a chave guardada',
        mail_key_is_smtp: 'Esta é uma chave SMTP (xsmtpsib-…). Crie uma chave API na Brevo → SMTP e API → Chaves API: começa por «xkeysib-».',
        mail_key_format: 'Uma chave API da Brevo começa por «xkeysib-».',
        mail_key_rejected: 'A Brevo recusa esta chave: :error',
        mail_key_valid: 'Definições de e-mail guardadas. A Brevo aceita a chave (conta: :account).',
        mail_key_unchecked: 'Definições de e-mail guardadas, mas não foi possível contactar a Brevo para verificar a chave. Envie um e-mail de teste.',
        mail_saved: 'Definições de e-mail guardadas.',
        mail_from_address: 'Endereço do remetente',
        mail_from_address_help: 'Tem de estar validado na Brevo → Remetentes, domínios e IP dedicados.',
        mail_from_name: 'Nome do remetente',
        mail_queue_pending: 'A aguardar envio',
        mail_queue_stuck: 'Há notificações à espera há :minutes min: o serviço agendador (php artisan schedule:work) não está a correr.',
        mail_queue_failed: 'Falhados',
        mail_queue_last_error: 'Último erro: :error',
        mail_queue_retry: 'Reenviar os envios falhados',
        mail_queue_retried: 'Os envios falhados voltaram à fila.',
    },
    zh: {
        mail_key: 'Brevo API 密钥',
        mail_key_help: '在 Brevo 中：SMTP 与 API → API 密钥 → 生成新的 API 密钥。密钥以“xkeysib-”开头，并以加密方式保存。',
        mail_key_saved: '已保存一个密钥（:hint）。留空即可保留该密钥。',
        mail_key_server: '服务器变量中已设置密钥（BREVO_API_KEY）。在此保存的密钥将取代它。',
        mail_key_remove: '删除已保存的密钥',
        mail_key_is_smtp: '这是 SMTP 密钥（xsmtpsib-…）。请在 Brevo → SMTP 与 API → API 密钥 中创建 API 密钥：它以“xkeysib-”开头。',
        mail_key_format: 'Brevo API 密钥以“xkeysib-”开头。',
        mail_key_rejected: 'Brevo 拒绝了此密钥：:error',
        mail_key_valid: '邮件设置已保存。Brevo 接受该密钥（账户：:account）。',
        mail_key_unchecked: '邮件设置已保存，但无法连接 Brevo 验证密钥。请发送一封测试邮件。',
        mail_saved: '邮件设置已保存。',
        mail_from_address: '发件人地址',
        mail_from_address_help: '该地址必须在 Brevo → 发件人、域名和专用 IP 中通过验证。',
        mail_from_name: '发件人名称',
        mail_queue_pending: '等待发送',
        mail_queue_stuck: '有通知已等待 :minutes 分钟：调度服务（php artisan schedule:work）没有运行。',
        mail_queue_failed: '发送失败',
        mail_queue_last_error: '最近的错误：:error',
        mail_queue_retry: '重新发送失败的通知',
        mail_queue_retried: '发送失败的通知已重新加入队列。',
    },
    ar: {
        mail_key: 'مفتاح Brevo API',
        mail_key_help: 'في Brevo: SMTP و API ← مفاتيح API ← إنشاء مفتاح API جديد. يبدأ بـ «xkeysib-» ويُحفظ مشفّرًا.',
        mail_key_saved: 'يوجد مفتاح محفوظ (:hint). اترك الحقل فارغًا للإبقاء عليه.',
        mail_key_server: 'يوجد مفتاح معرَّف في متغيرات الخادم (BREVO_API_KEY). المفتاح المحفوظ هنا يحلّ محلّه.',
        mail_key_remove: 'حذف المفتاح المحفوظ',
        mail_key_is_smtp: 'هذا مفتاح SMTP (xsmtpsib-…). أنشئ مفتاح API في Brevo ← SMTP و API ← مفاتيح API: يبدأ بـ «xkeysib-».',
        mail_key_format: 'مفتاح Brevo API يبدأ بـ «xkeysib-».',
        mail_key_rejected: 'Brevo يرفض هذا المفتاح: :error',
        mail_key_valid: 'تم حفظ إعدادات البريد. Brevo يقبل المفتاح (الحساب: :account).',
        mail_key_unchecked: 'تم حفظ إعدادات البريد، لكن تعذّر الاتصال بـ Brevo للتحقق من المفتاح. أرسل رسالة تجريبية.',
        mail_saved: 'تم حفظ إعدادات البريد.',
        mail_from_address: 'عنوان المرسل',
        mail_from_address_help: 'يجب أن يكون مُتحقَّقًا منه في Brevo ← المرسلون والنطاقات وعناوين IP المخصّصة.',
        mail_from_name: 'اسم المرسل',
        mail_queue_pending: 'في انتظار الإرسال',
        mail_queue_stuck: 'هناك إشعارات تنتظر منذ :minutes دقيقة: خدمة الجدولة (php artisan schedule:work) لا تعمل.',
        mail_queue_failed: 'فشل إرسالها',
        mail_queue_last_error: 'آخر خطأ: :error',
        mail_queue_retry: 'إعادة إرسال ما فشل',
        mail_queue_retried: 'أُعيدت الإشعارات التي فشل إرسالها إلى قائمة الانتظار.',
    },
};
