// "learn" group — e-mail notifications (Brevo), preferences, unsubscribe. Merged into learn.cjs.
module.exports = {
    en: {
        mail_footer_activity: 'You receive this e-mail because of your activity on ACADEXXA.',
        mail_footer_news: 'You receive this e-mail because you follow the news of ACADEXXA.',
        mail_manage: 'Manage my e-mails', mail_unsubscribe: 'Unsubscribe',
        notif_new_course_subject: 'New course: :course',
        notif_new_course_line: 'A new course is available: ":course", by :instructor.',
        notif_view_course: 'View the course',
        notif_enrolled_subject: 'You are enrolled in ":course"',
        notif_enrolled_line: 'Your enrollment in ":course" is confirmed. You can start right now.',
        notif_enrolled_tip: 'Tip: install the app and download the course to follow it without Internet.',
        notif_new_student_subject: 'New student in ":course"',
        notif_new_student_line: ':student has just enrolled in your course ":course".',
        notif_inactive_subject: 'Continue ":course"',
        notif_inactive_line: 'You have completed :percent % of ":course". Pick it up where you stopped: a few minutes a day are enough.',
        notif_password_subject: 'Your password has been changed',
        notif_password_line: 'The password of your ACADEXXA account has just been changed.',
        notif_password_warning: 'If it was not you, reset your password right away and contact the support.',
        notif_password_action: 'Reset my password',
        announcement_sent: '{0} Announcement created.|{1} Announcement created and sent to :count person.|[2,*] Announcement created and sent to :count people.',
        announcement_notify: 'Notify the audience (notification and e-mail)',
        announcement_notify_help: 'Each person receives it in their language; the e-mail follows their preferences.',
        email_news: 'Receive the news by e-mail (announcements, new courses, reminders)',
        email_security_note: 'Security e-mails (codes, password changes) are always sent.',
        unsubscribed_title: 'You are unsubscribed',
        unsubscribed_activity: ':email will no longer receive e-mails about the activity of its courses.',
        unsubscribed_news: ':email will no longer receive the news and reminders of ACADEXXA.',
        unsubscribed_note: 'Notifications stay available in the platform (bell). You can change your choice at any time in your profile.',
        code_send_failed: 'The e-mail with your code could not be sent. Try again in a moment or contact the support.',
        mail_settings: 'E-mails', mail_service: 'Sending service', mail_ready: 'active', mail_not_ready: 'not configured',
        mail_not_ready_help: 'E-mails are not sent: add your Brevo API key (BREVO_API_KEY) and a validated sender (MAIL_FROM_ADDRESS) to the server variables.',
        mail_sender: 'Sender', mail_test_to: 'Send a test e-mail to', mail_test_send: 'Send',
        mail_test_subject: 'ACADEXXA test e-mail',
        mail_test_body: 'This is a test e-mail from :site. If you are reading it, the sending of e-mails works.',
        mail_test_failed: 'Sending failed: :error',
        mail_test_sent: 'Test e-mail sent to :email. Check the inbox (and the spam folder).',
    },
    fr: {
        mail_footer_activity: 'Vous recevez cet e-mail en raison de votre activité sur ACADEXXA.',
        mail_footer_news: 'Vous recevez cet e-mail parce que vous suivez les actualités d’ACADEXXA.',
        mail_manage: 'Gérer mes e-mails', mail_unsubscribe: 'Se désinscrire',
        notif_new_course_subject: 'Nouveau cours : :course',
        notif_new_course_line: 'Un nouveau cours est disponible : « :course », par :instructor.',
        notif_view_course: 'Voir le cours',
        notif_enrolled_subject: 'Vous êtes inscrit à « :course »',
        notif_enrolled_line: 'Votre inscription au cours « :course » est confirmée. Vous pouvez commencer dès maintenant.',
        notif_enrolled_tip: 'Astuce : installez l’application et téléchargez le cours pour le suivre sans Internet.',
        notif_new_student_subject: 'Nouvel étudiant dans « :course »',
        notif_new_student_line: ':student vient de s’inscrire à votre cours « :course ».',
        notif_inactive_subject: 'Poursuivez « :course »',
        notif_inactive_line: 'Vous avez terminé :percent % de « :course ». Reprenez là où vous vous êtes arrêté : quelques minutes par jour suffisent.',
        notif_password_subject: 'Votre mot de passe a été modifié',
        notif_password_line: 'Le mot de passe de votre compte ACADEXXA vient d’être modifié.',
        notif_password_warning: 'Si ce n’est pas vous, réinitialisez votre mot de passe immédiatement et contactez le support.',
        notif_password_action: 'Réinitialiser mon mot de passe',
        announcement_sent: '{0} Annonce créée.|{1} Annonce créée et envoyée à :count personne.|[2,*] Annonce créée et envoyée à :count personnes.',
        announcement_notify: 'Notifier les destinataires (notification et e-mail)',
        announcement_notify_help: 'Chacun la reçoit dans sa langue ; l’e-mail respecte ses préférences.',
        email_news: 'Recevoir les actualités par e-mail (annonces, nouveaux cours, rappels)',
        email_security_note: 'Les e-mails de sécurité (codes, changement de mot de passe) sont toujours envoyés.',
        unsubscribed_title: 'Vous êtes désinscrit',
        unsubscribed_activity: ':email ne recevra plus d’e-mails sur l’activité de ses cours.',
        unsubscribed_news: ':email ne recevra plus les actualités et rappels d’ACADEXXA.',
        unsubscribed_note: 'Les notifications restent disponibles dans la plateforme (cloche). Vous pouvez changer d’avis à tout moment dans votre profil.',
        code_send_failed: 'L’e-mail contenant votre code n’a pas pu être envoyé. Réessayez dans un instant ou contactez le support.',
        mail_settings: 'E-mails', mail_service: 'Service d’envoi', mail_ready: 'actif', mail_not_ready: 'non configuré',
        mail_not_ready_help: 'Les e-mails ne sont pas envoyés : ajoutez votre clé API Brevo (BREVO_API_KEY) et un expéditeur validé (MAIL_FROM_ADDRESS) dans les variables du serveur.',
        mail_sender: 'Expéditeur', mail_test_to: 'Envoyer un e-mail de test à', mail_test_send: 'Envoyer',
        mail_test_subject: 'E-mail de test ACADEXXA',
        mail_test_body: 'Ceci est un e-mail de test de :site. Si vous le lisez, l’envoi des e-mails fonctionne.',
        mail_test_failed: 'Échec de l’envoi : :error',
        mail_test_sent: 'E-mail de test envoyé à :email. Vérifiez la boîte de réception (et les spams).',
    },
    es: {
        mail_footer_activity: 'Recibes este correo por tu actividad en ACADEXXA.',
        mail_footer_news: 'Recibes este correo porque sigues las novedades de ACADEXXA.',
        mail_manage: 'Gestionar mis correos', mail_unsubscribe: 'Darse de baja',
        notif_new_course_subject: 'Nuevo curso: :course',
        notif_new_course_line: 'Hay un nuevo curso disponible: «:course», de :instructor.',
        notif_view_course: 'Ver el curso',
        notif_enrolled_subject: 'Te has inscrito en «:course»',
        notif_enrolled_line: 'Tu inscripción en el curso «:course» está confirmada. Puedes empezar ahora mismo.',
        notif_enrolled_tip: 'Consejo: instala la aplicación y descarga el curso para seguirlo sin Internet.',
        notif_new_student_subject: 'Nuevo estudiante en «:course»',
        notif_new_student_line: ':student acaba de inscribirse en tu curso «:course».',
        notif_inactive_subject: 'Continúa «:course»',
        notif_inactive_line: 'Has completado el :percent % de «:course». Retómalo donde lo dejaste: bastan unos minutos al día.',
        notif_password_subject: 'Tu contraseña ha sido modificada',
        notif_password_line: 'La contraseña de tu cuenta de ACADEXXA acaba de modificarse.',
        notif_password_warning: 'Si no has sido tú, restablece tu contraseña de inmediato y contacta con el soporte.',
        notif_password_action: 'Restablecer mi contraseña',
        announcement_sent: '{0} Anuncio creado.|{1} Anuncio creado y enviado a :count persona.|[2,*] Anuncio creado y enviado a :count personas.',
        announcement_notify: 'Notificar a los destinatarios (notificación y correo)',
        announcement_notify_help: 'Cada persona lo recibe en su idioma; el correo respeta sus preferencias.',
        email_news: 'Recibir las novedades por correo (anuncios, cursos nuevos, recordatorios)',
        email_security_note: 'Los correos de seguridad (códigos, cambio de contraseña) se envían siempre.',
        unsubscribed_title: 'Te has dado de baja',
        unsubscribed_activity: ':email ya no recibirá correos sobre la actividad de sus cursos.',
        unsubscribed_news: ':email ya no recibirá las novedades ni los recordatorios de ACADEXXA.',
        unsubscribed_note: 'Las notificaciones siguen disponibles en la plataforma (campana). Puedes cambiar de opinión en cualquier momento en tu perfil.',
        code_send_failed: 'No se pudo enviar el correo con tu código. Inténtalo de nuevo en un momento o contacta con el soporte.',
        mail_settings: 'Correos', mail_service: 'Servicio de envío', mail_ready: 'activo', mail_not_ready: 'sin configurar',
        mail_not_ready_help: 'Los correos no se envían: añade tu clave API de Brevo (BREVO_API_KEY) y un remitente validado (MAIL_FROM_ADDRESS) en las variables del servidor.',
        mail_sender: 'Remitente', mail_test_to: 'Enviar un correo de prueba a', mail_test_send: 'Enviar',
        mail_test_subject: 'Correo de prueba de ACADEXXA',
        mail_test_body: 'Este es un correo de prueba de :site. Si lo estás leyendo, el envío de correos funciona.',
        mail_test_failed: 'Error en el envío: :error',
        mail_test_sent: 'Correo de prueba enviado a :email. Revisa la bandeja de entrada (y el spam).',
    },
    pt: {
        mail_footer_activity: 'Recebe este e-mail devido à sua atividade na ACADEXXA.',
        mail_footer_news: 'Recebe este e-mail porque acompanha as novidades da ACADEXXA.',
        mail_manage: 'Gerir os meus e-mails', mail_unsubscribe: 'Cancelar a subscrição',
        notif_new_course_subject: 'Novo curso: :course',
        notif_new_course_line: 'Está disponível um novo curso: «:course», de :instructor.',
        notif_view_course: 'Ver o curso',
        notif_enrolled_subject: 'Está inscrito em «:course»',
        notif_enrolled_line: 'A sua inscrição no curso «:course» está confirmada. Pode começar agora mesmo.',
        notif_enrolled_tip: 'Dica: instale a aplicação e descarregue o curso para o seguir sem Internet.',
        notif_new_student_subject: 'Novo estudante em «:course»',
        notif_new_student_line: ':student acabou de se inscrever no seu curso «:course».',
        notif_inactive_subject: 'Continue «:course»',
        notif_inactive_line: 'Concluiu :percent % de «:course». Retome onde parou: bastam alguns minutos por dia.',
        notif_password_subject: 'A sua palavra-passe foi alterada',
        notif_password_line: 'A palavra-passe da sua conta ACADEXXA acabou de ser alterada.',
        notif_password_warning: 'Se não foi você, reponha a palavra-passe imediatamente e contacte o suporte.',
        notif_password_action: 'Repor a minha palavra-passe',
        announcement_sent: '{0} Anúncio criado.|{1} Anúncio criado e enviado a :count pessoa.|[2,*] Anúncio criado e enviado a :count pessoas.',
        announcement_notify: 'Notificar os destinatários (notificação e e-mail)',
        announcement_notify_help: 'Cada pessoa recebe-o na sua língua; o e-mail respeita as suas preferências.',
        email_news: 'Receber as novidades por e-mail (anúncios, novos cursos, lembretes)',
        email_security_note: 'Os e-mails de segurança (códigos, alteração de palavra-passe) são sempre enviados.',
        unsubscribed_title: 'Subscrição cancelada',
        unsubscribed_activity: ':email deixará de receber e-mails sobre a atividade dos seus cursos.',
        unsubscribed_news: ':email deixará de receber as novidades e os lembretes da ACADEXXA.',
        unsubscribed_note: 'As notificações continuam disponíveis na plataforma (sino). Pode mudar de ideias a qualquer momento no seu perfil.',
        code_send_failed: 'Não foi possível enviar o e-mail com o seu código. Tente novamente dentro de momentos ou contacte o suporte.',
        mail_settings: 'E-mails', mail_service: 'Serviço de envio', mail_ready: 'ativo', mail_not_ready: 'não configurado',
        mail_not_ready_help: 'Os e-mails não são enviados: adicione a sua chave API da Brevo (BREVO_API_KEY) e um remetente validado (MAIL_FROM_ADDRESS) nas variáveis do servidor.',
        mail_sender: 'Remetente', mail_test_to: 'Enviar um e-mail de teste para', mail_test_send: 'Enviar',
        mail_test_subject: 'E-mail de teste da ACADEXXA',
        mail_test_body: 'Este é um e-mail de teste de :site. Se o está a ler, o envio de e-mails funciona.',
        mail_test_failed: 'Falha no envio: :error',
        mail_test_sent: 'E-mail de teste enviado para :email. Verifique a caixa de entrada (e o spam).',
    },
    zh: {
        mail_footer_activity: '你收到此邮件是因为你在 ACADEXXA 上的学习动态。',
        mail_footer_news: '你收到此邮件是因为你订阅了 ACADEXXA 的资讯。',
        mail_manage: '管理我的邮件', mail_unsubscribe: '退订',
        notif_new_course_subject: '新课程：:course',
        notif_new_course_line: '新课程已上线：“:course”，讲师：:instructor。',
        notif_view_course: '查看课程',
        notif_enrolled_subject: '你已报名“:course”',
        notif_enrolled_line: '你已成功报名课程“:course”，现在就可以开始学习。',
        notif_enrolled_tip: '提示：安装应用并下载课程，没有网络也能学习。',
        notif_new_student_subject: '“:course”有新学员',
        notif_new_student_line: ':student 刚刚报名了你的课程“:course”。',
        notif_inactive_subject: '继续学习“:course”',
        notif_inactive_line: '你已完成“:course”的 :percent %。从上次停下的地方继续吧：每天几分钟就够了。',
        notif_password_subject: '你的密码已修改',
        notif_password_line: '你的 ACADEXXA 账户密码刚刚被修改。',
        notif_password_warning: '如果不是你本人操作，请立即重置密码并联系客服。',
        notif_password_action: '重置我的密码',
        announcement_sent: '公告已创建，已发送人数：:count。',
        announcement_notify: '通知受众（站内通知和电子邮件）',
        announcement_notify_help: '每个人都会收到自己语言的版本；电子邮件遵循其偏好设置。',
        email_news: '通过电子邮件接收资讯（公告、新课程、提醒）',
        email_security_note: '安全类邮件（验证码、密码修改）始终会发送。',
        unsubscribed_title: '你已退订',
        unsubscribed_activity: ':email 将不再收到课程动态邮件。',
        unsubscribed_news: ':email 将不再收到 ACADEXXA 的资讯和提醒。',
        unsubscribed_note: '通知仍可在平台内查看（铃铛）。你可以随时在个人资料中更改设置。',
        code_send_failed: '验证码邮件发送失败。请稍后重试或联系客服。',
        mail_settings: '电子邮件', mail_service: '发送服务', mail_ready: '已启用', mail_not_ready: '未配置',
        mail_not_ready_help: '邮件尚未发送：请在服务器变量中添加 Brevo API 密钥（BREVO_API_KEY）和已验证的发件人（MAIL_FROM_ADDRESS）。',
        mail_sender: '发件人', mail_test_to: '发送测试邮件至', mail_test_send: '发送',
        mail_test_subject: 'ACADEXXA 测试邮件',
        mail_test_body: '这是来自 :site 的测试邮件。如果你能看到它，说明邮件发送正常。',
        mail_test_failed: '发送失败：:error',
        mail_test_sent: '测试邮件已发送至 :email。请查看收件箱（以及垃圾邮件）。',
    },
    ar: {
        mail_footer_activity: 'تصلك هذه الرسالة بسبب نشاطك على ACADEXXA.',
        mail_footer_news: 'تصلك هذه الرسالة لأنك تتابع أخبار ACADEXXA.',
        mail_manage: 'إدارة رسائلي', mail_unsubscribe: 'إلغاء الاشتراك',
        notif_new_course_subject: 'دورة جديدة: :course',
        notif_new_course_line: 'دورة جديدة متاحة: «:course»، يقدّمها :instructor.',
        notif_view_course: 'عرض الدورة',
        notif_enrolled_subject: 'تم تسجيلك في «:course»',
        notif_enrolled_line: 'تم تأكيد تسجيلك في دورة «:course». يمكنك البدء الآن.',
        notif_enrolled_tip: 'نصيحة: ثبّت التطبيق ونزّل الدورة لمتابعتها دون إنترنت.',
        notif_new_student_subject: 'طالب جديد في «:course»',
        notif_new_student_line: 'سجّل :student للتو في دورتك «:course».',
        notif_inactive_subject: 'تابع «:course»',
        notif_inactive_line: 'أكملت :percent % من «:course». تابع من حيث توقفت: تكفي دقائق قليلة يوميًا.',
        notif_password_subject: 'تم تغيير كلمة مرورك',
        notif_password_line: 'تم للتو تغيير كلمة مرور حسابك في ACADEXXA.',
        notif_password_warning: 'إن لم تكن أنت من قام بذلك، فأعد تعيين كلمة المرور فورًا وتواصل مع الدعم.',
        notif_password_action: 'إعادة تعيين كلمة المرور',
        announcement_sent: 'تم إنشاء الإعلان. عدد المستلمين: :count.',
        announcement_notify: 'إشعار المستلمين (إشعار وبريد إلكتروني)',
        announcement_notify_help: 'يستلمه كل شخص بلغته، ويراعي البريد الإلكتروني تفضيلاته.',
        email_news: 'تلقي الأخبار بالبريد الإلكتروني (إعلانات، دورات جديدة، تذكيرات)',
        email_security_note: 'رسائل الأمان (الرموز، تغيير كلمة المرور) تُرسل دائمًا.',
        unsubscribed_title: 'تم إلغاء اشتراكك',
        unsubscribed_activity: 'لن يتلقى :email بعد الآن رسائل عن نشاط دوراته.',
        unsubscribed_news: 'لن يتلقى :email بعد الآن أخبار ACADEXXA وتذكيراتها.',
        unsubscribed_note: 'تبقى الإشعارات متاحة داخل المنصة (الجرس). يمكنك تغيير اختيارك في أي وقت من ملفك الشخصي.',
        code_send_failed: 'تعذّر إرسال البريد الذي يحتوي على رمزك. أعد المحاولة بعد قليل أو تواصل مع الدعم.',
        mail_settings: 'البريد الإلكتروني', mail_service: 'خدمة الإرسال', mail_ready: 'مفعّلة', mail_not_ready: 'غير مُعدّة',
        mail_not_ready_help: 'لا تُرسل الرسائل: أضف مفتاح Brevo API (BREVO_API_KEY) ومرسلًا مُتحقَّقًا منه (MAIL_FROM_ADDRESS) إلى متغيرات الخادم.',
        mail_sender: 'المرسل', mail_test_to: 'إرسال رسالة تجريبية إلى', mail_test_send: 'إرسال',
        mail_test_subject: 'رسالة تجريبية من ACADEXXA',
        mail_test_body: 'هذه رسالة تجريبية من :site. إذا كنت تقرؤها فإن إرسال البريد يعمل.',
        mail_test_failed: 'فشل الإرسال: :error',
        mail_test_sent: 'تم إرسال الرسالة التجريبية إلى :email. تحقق من صندوق الوارد (والبريد غير المرغوب فيه).',
    },
};
