// "learn" group — marks out of 10 / 100, open-question module exercises with detailed answers,
// and the certificate. Merged into learn.cjs (overrides some earlier keys).
module.exports = {
    en: {
        scope_help_module: 'The module exercise closes the module: at least :min open questions. For each one, write the detailed answer: students see it after handing in their own answers.',
        path_module: 'After each module: an exercise of at least :min open questions. The instructor writes the detailed answer of each question; students read it after answering.',
        module_exercise_intro: 'Write your answer to each question, then hand in the exercise: the detailed answers are then shown so that you can compare.',
        check_module_exercises: 'An exercise of at least :min questions with their detailed answers after each module',
        open_question: 'Open question',
        model_answer: 'Detailed answer',
        model_answer_placeholder: 'Write the complete, detailed answer the student should compare with.',
        model_answer_help: 'Shown to students only after they have handed in the exercise.',
        import_open_help: 'Paste your questions: one block per question, separated by an empty line. First line = the question, following lines = the detailed answer.',
        import_open_sample: "What is a balance sheet?\nA balance sheet is a statement of what a company owns (assets) and owes (liabilities) at a given date.\nAssets always equal liabilities plus equity.\n\nWhat is depreciation?\nThe spreading of the cost of an asset over the years it is used.",
        import_open_error: 'Block :number ignored (":question"): write the detailed answer on the lines under the question.',
        exercise_open_hint: 'written answers, then detailed corrections',
        exercise_unanswered: '{1} :count question has no answer yet.|[2,*] :count questions have no answer yet.',
        exercise_done: 'Exercise handed in. Compare your answers with the detailed answers below.',
        exercise_handed_in: 'Handed in',
        student_answers: 'Answers of the student',
        your_answer: 'Your answer',
        your_answer_placeholder: 'Write your answer here…',
        pass_grade: 'Pass mark: :grade/:out_of',
        cert_title: 'CERTIFICATE',
        cert_subtitle: 'OF ACHIEVEMENT',
        cert_awarded_to: 'This certificate is proudly presented to',
        cert_for_course: 'for having successfully completed the course',
        cert_final_score: 'Final evaluation: :score/100',
        cert_issued_on: 'Awarded on',
        cert_part_of: 'ACADEXA is the online learning platform of the :institution',
        js: {
            model_answer: 'Detailed answer',
            grade_line: 'Mark: :grade/:out_of (:correct right answers out of :total)',
            exercise_online_only: 'This exercise is done online: your written answers are sent to your instructor.',
        },
    },
    fr: {
        scope_help_module: 'L’exercice clôt le module : au moins :min questions ouvertes. Pour chacune, rédigez la réponse détaillée : l’étudiant la voit après avoir remis ses propres réponses.',
        path_module: 'Après chaque module : un exercice d’au moins :min questions ouvertes. Le formateur rédige la réponse détaillée de chaque question ; l’étudiant la lit après avoir répondu.',
        module_exercise_intro: 'Rédigez votre réponse à chaque question, puis remettez l’exercice : les réponses détaillées s’affichent ensuite pour que vous puissiez comparer.',
        check_module_exercises: 'Un exercice d’au moins :min questions avec leurs réponses détaillées après chaque module',
        open_question: 'Question ouverte',
        model_answer: 'Réponse détaillée',
        model_answer_placeholder: 'Rédigez la réponse complète et détaillée à laquelle l’étudiant comparera la sienne.',
        model_answer_help: 'Affichée aux étudiants uniquement après la remise de l’exercice.',
        import_open_help: 'Collez vos questions : un bloc par question, séparés par une ligne vide. Première ligne = la question, lignes suivantes = la réponse détaillée.',
        import_open_sample: "Qu’est-ce qu’un bilan ?\nLe bilan est un état de ce que l’entreprise possède (actif) et de ce qu’elle doit (passif) à une date donnée.\nL’actif est toujours égal au passif.\n\nQu’est-ce qu’un amortissement ?\nLa répartition du coût d’un bien sur ses années d’utilisation.",
        import_open_error: 'Bloc :number ignoré (« :question ») : écrivez la réponse détaillée sur les lignes sous la question.',
        exercise_open_hint: 'réponses rédigées, puis corrigé détaillé',
        exercise_unanswered: '{1} :count question n’a pas encore de réponse.|[2,*] :count questions n’ont pas encore de réponse.',
        exercise_done: 'Exercice remis. Comparez vos réponses avec les réponses détaillées ci-dessous.',
        exercise_handed_in: 'Remis',
        student_answers: 'Réponses de l’étudiant',
        your_answer: 'Votre réponse',
        your_answer_placeholder: 'Rédigez votre réponse ici…',
        pass_grade: 'Réussite : :grade/:out_of',
        cert_title: 'CERTIFICAT',
        cert_subtitle: 'DE RÉUSSITE',
        cert_awarded_to: 'Ce certificat est fièrement décerné à',
        cert_for_course: 'pour avoir suivi et réussi le cours',
        cert_final_score: 'Évaluation finale : :score/100',
        cert_issued_on: 'Délivré le',
        cert_part_of: 'ACADEXA est la plateforme de formation en ligne de l’:institution',
        js: {
            model_answer: 'Réponse détaillée',
            grade_line: 'Note : :grade/:out_of (:correct bonnes réponses sur :total)',
            exercise_online_only: 'Cet exercice se fait en ligne : vos réponses rédigées sont transmises à votre formateur.',
        },
    },
    es: {
        scope_help_module: 'El ejercicio cierra el módulo: al menos :min preguntas abiertas. Para cada una, redacta la respuesta detallada: el estudiante la ve después de entregar sus propias respuestas.',
        path_module: 'Después de cada módulo: un ejercicio de al menos :min preguntas abiertas. El instructor redacta la respuesta detallada de cada pregunta; el estudiante la lee después de responder.',
        module_exercise_intro: 'Redacta tu respuesta a cada pregunta y entrega el ejercicio: después se muestran las respuestas detalladas para que puedas comparar.',
        check_module_exercises: 'Un ejercicio de al menos :min preguntas con sus respuestas detalladas después de cada módulo',
        open_question: 'Pregunta abierta',
        model_answer: 'Respuesta detallada',
        model_answer_placeholder: 'Redacta la respuesta completa y detallada con la que el estudiante comparará la suya.',
        model_answer_help: 'Se muestra a los estudiantes solo después de entregar el ejercicio.',
        import_open_help: 'Pega tus preguntas: un bloque por pregunta, separados por una línea vacía. Primera línea = la pregunta, líneas siguientes = la respuesta detallada.',
        import_open_sample: "¿Qué es un balance?\nEl balance es un estado de lo que la empresa posee (activo) y de lo que debe (pasivo) en una fecha dada.\nEl activo siempre es igual al pasivo.\n\n¿Qué es una amortización?\nEl reparto del coste de un bien entre sus años de uso.",
        import_open_error: 'Bloque :number ignorado («:question»): escribe la respuesta detallada en las líneas debajo de la pregunta.',
        exercise_open_hint: 'respuestas redactadas y luego corrección detallada',
        exercise_unanswered: '{1} :count pregunta aún no tiene respuesta.|[2,*] :count preguntas aún no tienen respuesta.',
        exercise_done: 'Ejercicio entregado. Compara tus respuestas con las respuestas detalladas de abajo.',
        exercise_handed_in: 'Entregado',
        student_answers: 'Respuestas del estudiante',
        your_answer: 'Tu respuesta',
        your_answer_placeholder: 'Escribe tu respuesta aquí…',
        pass_grade: 'Aprobado: :grade/:out_of',
        cert_title: 'CERTIFICADO',
        cert_subtitle: 'DE APROVECHAMIENTO',
        cert_awarded_to: 'Este certificado se otorga con orgullo a',
        cert_for_course: 'por haber completado con éxito el curso',
        cert_final_score: 'Evaluación final: :score/100',
        cert_issued_on: 'Otorgado el',
        cert_part_of: 'ACADEXA es la plataforma de formación en línea del :institution',
        js: {
            model_answer: 'Respuesta detallada',
            grade_line: 'Nota: :grade/:out_of (:correct respuestas correctas de :total)',
            exercise_online_only: 'Este ejercicio se hace en línea: tus respuestas se envían a tu instructor.',
        },
    },
    pt: {
        scope_help_module: 'O exercício encerra o módulo: pelo menos :min perguntas abertas. Para cada uma, redija a resposta detalhada: o estudante vê-a depois de entregar as suas próprias respostas.',
        path_module: 'Depois de cada módulo: um exercício de pelo menos :min perguntas abertas. O formador redige a resposta detalhada de cada pergunta; o estudante lê-a depois de responder.',
        module_exercise_intro: 'Redija a sua resposta a cada pergunta e entregue o exercício: as respostas detalhadas são mostradas a seguir para poder comparar.',
        check_module_exercises: 'Um exercício de pelo menos :min perguntas com as respetivas respostas detalhadas depois de cada módulo',
        open_question: 'Pergunta aberta',
        model_answer: 'Resposta detalhada',
        model_answer_placeholder: 'Redija a resposta completa e detalhada com a qual o estudante vai comparar a sua.',
        model_answer_help: 'Mostrada aos estudantes apenas depois de entregarem o exercício.',
        import_open_help: 'Cole as suas perguntas: um bloco por pergunta, separados por uma linha vazia. Primeira linha = a pergunta, linhas seguintes = a resposta detalhada.',
        import_open_sample: "O que é um balanço?\nO balanço é um mapa do que a empresa possui (ativo) e do que deve (passivo) numa determinada data.\nO ativo é sempre igual ao passivo.\n\nO que é uma amortização?\nA repartição do custo de um bem pelos seus anos de utilização.",
        import_open_error: 'Bloco :number ignorado («:question»): escreva a resposta detalhada nas linhas por baixo da pergunta.',
        exercise_open_hint: 'respostas redigidas e depois correção detalhada',
        exercise_unanswered: '{1} :count pergunta ainda não tem resposta.|[2,*] :count perguntas ainda não têm resposta.',
        exercise_done: 'Exercício entregue. Compare as suas respostas com as respostas detalhadas abaixo.',
        exercise_handed_in: 'Entregue',
        student_answers: 'Respostas do estudante',
        your_answer: 'A sua resposta',
        your_answer_placeholder: 'Escreva a sua resposta aqui…',
        pass_grade: 'Aprovação: :grade/:out_of',
        cert_title: 'CERTIFICADO',
        cert_subtitle: 'DE APROVEITAMENTO',
        cert_awarded_to: 'Este certificado é atribuído com orgulho a',
        cert_for_course: 'por ter concluído com êxito o curso',
        cert_final_score: 'Avaliação final: :score/100',
        cert_issued_on: 'Atribuído em',
        cert_part_of: 'A ACADEXA é a plataforma de formação online do :institution',
        js: {
            model_answer: 'Resposta detalhada',
            grade_line: 'Nota: :grade/:out_of (:correct respostas certas em :total)',
            exercise_online_only: 'Este exercício é feito online: as suas respostas são enviadas ao seu formador.',
        },
    },
    zh: {
        scope_help_module: '模块练习用于结束模块：至少 :min 道开放式问题。请为每道题撰写详细答案：学员提交自己的答案后才能看到。',
        path_module: '每个模块之后：至少 :min 道开放式问题的练习。讲师为每道题撰写详细答案，学员作答后即可阅读。',
        module_exercise_intro: '请写出每道题的答案，然后提交练习：之后会显示详细答案，供你对照。',
        check_module_exercises: '每个模块后都有至少 :min 道题的练习，并附详细答案',
        open_question: '开放式问题',
        model_answer: '详细答案',
        model_answer_placeholder: '请撰写完整、详细的答案，供学员对照。',
        model_answer_help: '学员提交练习后才会显示。',
        import_open_help: '粘贴你的题目：每题一个段落，段落之间空一行。第一行是题目，后面的行是详细答案。',
        import_open_sample: "什么是资产负债表？\n资产负债表反映企业在某一日期拥有的资源（资产）和承担的债务（负债）。\n资产总额始终等于负债与所有者权益之和。\n\n什么是折旧？\n将资产成本在其使用年限内分摊。",
        import_open_error: '已忽略第 :number 段（“:question”）：请在题目下面的行中写出详细答案。',
        exercise_open_hint: '书面作答，然后查看详细答案',
        exercise_unanswered: '还有 :count 道题没有作答。',
        exercise_done: '练习已提交。请将你的答案与下面的详细答案进行对照。',
        exercise_handed_in: '已提交',
        student_answers: '学员的答案',
        your_answer: '你的答案',
        your_answer_placeholder: '在这里写下你的答案…',
        pass_grade: '及格分：:grade/:out_of',
        cert_title: '证书',
        cert_subtitle: '结业证明',
        cert_awarded_to: '特此授予',
        cert_for_course: '以表彰其顺利完成课程',
        cert_final_score: '期末评估：:score/100',
        cert_issued_on: '颁发日期',
        cert_part_of: 'ACADEXA 是 :institution 的在线学习平台',
        js: {
            model_answer: '详细答案',
            grade_line: '得分：:grade/:out_of（:total 题中答对 :correct 题）',
            exercise_online_only: '此练习需在线完成：你的书面答案会发送给讲师。',
        },
    },
    ar: {
        scope_help_module: 'تمرين الوحدة يختم الوحدة: :min أسئلة مفتوحة على الأقل. اكتب الإجابة المفصّلة لكل سؤال: يراها الطالب بعد تسليم إجاباته.',
        path_module: 'بعد كل وحدة: تمرين من :min أسئلة مفتوحة على الأقل. يكتب المدرّب الإجابة المفصّلة لكل سؤال ويقرؤها الطالب بعد أن يجيب.',
        module_exercise_intro: 'اكتب إجابتك عن كل سؤال ثم سلّم التمرين: تظهر بعد ذلك الإجابات المفصّلة لتقارن بها.',
        check_module_exercises: 'تمرين من :min أسئلة على الأقل مع إجاباتها المفصّلة بعد كل وحدة',
        open_question: 'سؤال مفتوح',
        model_answer: 'الإجابة المفصّلة',
        model_answer_placeholder: 'اكتب الإجابة الكاملة والمفصّلة التي سيقارن بها الطالب إجابته.',
        model_answer_help: 'تُعرض على الطلاب بعد تسليم التمرين فقط.',
        import_open_help: 'الصق أسئلتك: كتلة لكل سؤال مع سطر فارغ بين الكتل. السطر الأول هو السؤال والأسطر التالية هي الإجابة المفصّلة.',
        import_open_sample: "ما الميزانية العمومية؟\nالميزانية العمومية بيان بما تملكه الشركة (الأصول) وما عليها (الخصوم) في تاريخ محدد.\nالأصول تساوي دائمًا الخصوم وحقوق الملكية.\n\nما الإهلاك؟\nتوزيع تكلفة الأصل على سنوات استخدامه.",
        import_open_error: 'تم تجاهل الكتلة :number («:question»): اكتب الإجابة المفصّلة في الأسطر التي تلي السؤال.',
        exercise_open_hint: 'إجابات مكتوبة ثم تصحيح مفصّل',
        exercise_unanswered: 'عدد الأسئلة التي لم تُجب عنها بعد: :count.',
        exercise_done: 'تم تسليم التمرين. قارن إجاباتك بالإجابات المفصّلة أدناه.',
        exercise_handed_in: 'تم التسليم',
        student_answers: 'إجابات الطالب',
        your_answer: 'إجابتك',
        your_answer_placeholder: 'اكتب إجابتك هنا…',
        pass_grade: 'درجة النجاح: :grade/:out_of',
        cert_title: 'شهادة',
        cert_subtitle: 'إتمام',
        cert_awarded_to: 'تُمنح هذه الشهادة بكل فخر إلى',
        cert_for_course: 'لإتمامه بنجاح دورة',
        cert_final_score: 'التقييم النهائي: :score/100',
        cert_issued_on: 'تاريخ المنح',
        cert_part_of: 'ACADEXA هي منصة التعلّم الإلكتروني التابعة لـ :institution',
        js: {
            model_answer: 'الإجابة المفصّلة',
            grade_line: 'الدرجة: :grade/:out_of (الإجابات الصحيحة: :correct من :total)',
            exercise_online_only: 'يُنجز هذا التمرين عبر الإنترنت: تُرسل إجاباتك المكتوبة إلى مدرّبك.',
        },
    },
};
