// "learn" group — course creation with structure and content (YouTube video/playlist, videos,
// PDF/PowerPoint materials), playlists in the player. Merged into learn.cjs (overrides wizard_help).
const T = {
    en: {
        wizard_help: 'Four steps. The course is only created at the end, with its modules, lessons and content.',
        wizard_step_structure: 'Modules and lessons', wizard_step_content: 'Content',
        wizard_fix_errors: 'Some information is missing or wrong: check the steps below.',
        structure_help: 'Split the course into modules. For each module, give its name and its number of lessons: they are created for you (you can rename them afterwards).',
        lessons_number: 'Lessons', structure_total: ':modules module(s), :lessons lesson(s) in total',
        structure_required: 'Add at least one module.',
        content_help: 'Choose at least one option. Videos are placed in the lessons in order.',
        content_required: 'Choose at least one type of content: a YouTube link, a video or a course material.',
        content_youtube: 'YouTube video or playlist',
        content_youtube_help: 'A playlist fills the lessons in order (video 1 → lesson 1…); students are offered the next video at the end of each one, inside the platform.',
        content_youtube_placeholder: 'https://www.youtube.com/playlist?list=…',
        content_videos: 'Upload videos (:max MB max. each)',
        content_videos_help: 'One video per lesson, in the order of the list. If there are more videos than lessons, lessons are added to the last module.',
        content_documents: 'Course material (PDF or PowerPoint)',
        content_documents_help: 'Enrolled students keep it in their library and read it offline in the app.',
        optional: 'optional', drop_files: 'Click or drop the files here', max_per_file: 'max. :max per file',
        document_bad_extension: 'Format not accepted. Use PDF, PPT or PPTX.',
        course_created_with_content: 'Course created with its modules, lessons and content. Complete the lessons, then submit it for review.',
        lesson_n: 'Lesson :number',
        course_materials: 'Course materials',
        course_materials_help: 'Add them to your library to read them anywhere, even offline.',
        teaching: 'Teaching',
        js: {
            playlist_detected: 'YouTube playlist detected',
            playlist_no_video: 'This lesson has no video in the playlist.',
            next_video_in: 'Next video in :seconds s…',
            slides_open_help: 'PowerPoint files open in your presentation app (PowerPoint, Google Slides, WPS…), also offline once saved in your library.',
            slides_open: 'Open the presentation',
            document_bad_extension: 'Format not accepted. Use PDF, PPT or PPTX.',
        },
    },
    fr: {
        wizard_help: 'Quatre étapes. Le cours n’est créé qu’à la fin, avec ses modules, ses leçons et son contenu.',
        wizard_step_structure: 'Modules et leçons', wizard_step_content: 'Contenu',
        wizard_fix_errors: 'Des informations manquent ou sont incorrectes : vérifiez les étapes ci-dessous.',
        structure_help: 'Découpez le cours en modules. Pour chaque module, indiquez son nom et son nombre de leçons : elles sont créées pour vous (vous pourrez les renommer ensuite).',
        lessons_number: 'Leçons', structure_total: ':modules module(s), :lessons leçon(s) au total',
        structure_required: 'Ajoutez au moins un module.',
        content_help: 'Choisissez au moins une option. Les vidéos sont placées dans les leçons dans l’ordre.',
        content_required: 'Choisissez au moins un type de contenu : un lien YouTube, une vidéo ou un support de cours.',
        content_youtube: 'Vidéo ou playlist YouTube',
        content_youtube_help: 'Une playlist remplit les leçons dans l’ordre (vidéo 1 → leçon 1…) ; à la fin de chaque vidéo, l’étudiant se voit proposer la suivante, dans la plateforme.',
        content_youtube_placeholder: 'https://www.youtube.com/playlist?list=…',
        content_videos: 'Envoyer des vidéos (:max Mo max. chacune)',
        content_videos_help: 'Une vidéo par leçon, dans l’ordre de la liste. S’il y a plus de vidéos que de leçons, des leçons sont ajoutées au dernier module.',
        content_documents: 'Support de cours (PDF ou PowerPoint)',
        content_documents_help: 'Les étudiants inscrits le gardent dans leur bibliothèque et le lisent hors ligne dans l’application.',
        optional: 'facultatif', drop_files: 'Cliquez ou déposez les fichiers ici', max_per_file: 'max. :max par fichier',
        document_bad_extension: 'Format non accepté. Utilisez PDF, PPT ou PPTX.',
        course_created_with_content: 'Cours créé avec ses modules, ses leçons et son contenu. Complétez les leçons, puis soumettez-le pour validation.',
        lesson_n: 'Leçon :number',
        course_materials: 'Supports du cours',
        course_materials_help: 'Ajoutez-les à votre bibliothèque pour les lire partout, même hors ligne.',
        teaching: 'Enseignement',
        js: {
            playlist_detected: 'Playlist YouTube détectée',
            playlist_no_video: 'Cette leçon n’a pas de vidéo dans la playlist.',
            next_video_in: 'Vidéo suivante dans :seconds s…',
            slides_open_help: 'Les fichiers PowerPoint s’ouvrent dans votre application de présentation (PowerPoint, Google Slides, WPS…), aussi hors ligne une fois enregistrés dans votre bibliothèque.',
            slides_open: 'Ouvrir la présentation',
            document_bad_extension: 'Format non accepté. Utilisez PDF, PPT ou PPTX.',
        },
    },
    es: {
        wizard_help: 'Cuatro pasos. El curso solo se crea al final, con sus módulos, lecciones y contenido.',
        wizard_step_structure: 'Módulos y lecciones', wizard_step_content: 'Contenido',
        wizard_fix_errors: 'Falta información o es incorrecta: revisa los pasos de abajo.',
        structure_help: 'Divide el curso en módulos. Para cada módulo, indica su nombre y su número de lecciones: se crean automáticamente (podrás renombrarlas después).',
        lessons_number: 'Lecciones', structure_total: ':modules módulo(s), :lessons lección(es) en total',
        structure_required: 'Añade al menos un módulo.',
        content_help: 'Elige al menos una opción. Los vídeos se colocan en las lecciones en orden.',
        content_required: 'Elige al menos un tipo de contenido: un enlace de YouTube, un vídeo o un material del curso.',
        content_youtube: 'Vídeo o lista de reproducción de YouTube',
        content_youtube_help: 'Una lista rellena las lecciones en orden (vídeo 1 → lección 1…); al final de cada vídeo se propone el siguiente al estudiante, dentro de la plataforma.',
        content_youtube_placeholder: 'https://www.youtube.com/playlist?list=…',
        content_videos: 'Subir vídeos (máx. :max MB cada uno)',
        content_videos_help: 'Un vídeo por lección, en el orden de la lista. Si hay más vídeos que lecciones, se añaden lecciones al último módulo.',
        content_documents: 'Material del curso (PDF o PowerPoint)',
        content_documents_help: 'Los estudiantes inscritos lo guardan en su biblioteca y lo leen sin conexión en la aplicación.',
        optional: 'opcional', drop_files: 'Haz clic o suelta los archivos aquí', max_per_file: 'máx. :max por archivo',
        document_bad_extension: 'Formato no aceptado. Usa PDF, PPT o PPTX.',
        course_created_with_content: 'Curso creado con sus módulos, lecciones y contenido. Completa las lecciones y envíalo a revisión.',
        lesson_n: 'Lección :number',
        course_materials: 'Materiales del curso',
        course_materials_help: 'Añádelos a tu biblioteca para leerlos en cualquier lugar, incluso sin conexión.',
        teaching: 'Enseñanza',
        js: {
            playlist_detected: 'Lista de reproducción de YouTube detectada',
            playlist_no_video: 'Esta lección no tiene vídeo en la lista.',
            next_video_in: 'Siguiente vídeo en :seconds s…',
            slides_open_help: 'Los archivos de PowerPoint se abren en tu aplicación de presentaciones (PowerPoint, Google Slides, WPS…), también sin conexión una vez guardados en tu biblioteca.',
            slides_open: 'Abrir la presentación',
            document_bad_extension: 'Formato no aceptado. Usa PDF, PPT o PPTX.',
        },
    },
    pt: {
        wizard_help: 'Quatro passos. O curso só é criado no fim, com os seus módulos, aulas e conteúdo.',
        wizard_step_structure: 'Módulos e aulas', wizard_step_content: 'Conteúdo',
        wizard_fix_errors: 'Faltam informações ou estão incorretas: verifique os passos abaixo.',
        structure_help: 'Divida o curso em módulos. Para cada módulo, indique o nome e o número de aulas: são criadas automaticamente (poderá renomeá-las depois).',
        lessons_number: 'Aulas', structure_total: ':modules módulo(s), :lessons aula(s) no total',
        structure_required: 'Adicione pelo menos um módulo.',
        content_help: 'Escolha pelo menos uma opção. Os vídeos são colocados nas aulas por ordem.',
        content_required: 'Escolha pelo menos um tipo de conteúdo: uma ligação do YouTube, um vídeo ou um material do curso.',
        content_youtube: 'Vídeo ou lista de reprodução do YouTube',
        content_youtube_help: 'Uma lista preenche as aulas por ordem (vídeo 1 → aula 1…); no fim de cada vídeo é proposto o seguinte ao estudante, dentro da plataforma.',
        content_youtube_placeholder: 'https://www.youtube.com/playlist?list=…',
        content_videos: 'Enviar vídeos (máx. :max MB cada)',
        content_videos_help: 'Um vídeo por aula, pela ordem da lista. Se houver mais vídeos do que aulas, são acrescentadas aulas ao último módulo.',
        content_documents: 'Material do curso (PDF ou PowerPoint)',
        content_documents_help: 'Os estudantes inscritos guardam-no na sua biblioteca e leem-no offline na aplicação.',
        optional: 'opcional', drop_files: 'Clique ou largue os ficheiros aqui', max_per_file: 'máx. :max por ficheiro',
        document_bad_extension: 'Formato não aceite. Use PDF, PPT ou PPTX.',
        course_created_with_content: 'Curso criado com os seus módulos, aulas e conteúdo. Complete as aulas e submeta-o para validação.',
        lesson_n: 'Aula :number',
        course_materials: 'Materiais do curso',
        course_materials_help: 'Adicione-os à sua biblioteca para os ler em qualquer lugar, mesmo offline.',
        teaching: 'Ensino',
        js: {
            playlist_detected: 'Lista de reprodução do YouTube detetada',
            playlist_no_video: 'Esta aula não tem vídeo na lista.',
            next_video_in: 'Vídeo seguinte dentro de :seconds s…',
            slides_open_help: 'Os ficheiros PowerPoint abrem na sua aplicação de apresentações (PowerPoint, Google Slides, WPS…), também offline depois de guardados na sua biblioteca.',
            slides_open: 'Abrir a apresentação',
            document_bad_extension: 'Formato não aceite. Use PDF, PPT ou PPTX.',
        },
    },
    zh: {
        wizard_help: '共四个步骤。课程在最后一步才会创建，同时生成模块、课时和内容。',
        wizard_step_structure: '模块与课时', wizard_step_content: '内容',
        wizard_fix_errors: '有信息缺失或错误：请检查下面的步骤。',
        structure_help: '将课程分成若干模块。为每个模块填写名称和课时数量，系统会自动创建课时（之后可以重命名）。',
        lessons_number: '课时', structure_total: '共 :modules 个模块，:lessons 个课时',
        structure_required: '请至少添加一个模块。',
        content_help: '请至少选择一项。视频将按顺序放入各课时。',
        content_required: '请至少选择一种内容：YouTube 链接、视频或课程资料。',
        content_youtube: 'YouTube 视频或播放列表',
        content_youtube_help: '播放列表会按顺序填入课时（视频 1 → 课时 1…）；每个视频结束时，平台内会提示学员观看下一个视频。',
        content_youtube_placeholder: 'https://www.youtube.com/playlist?list=…',
        content_videos: '上传视频（每个最大 :max MB）',
        content_videos_help: '每个课时一个视频，按列表顺序排列。视频多于课时时，会在最后一个模块中增加课时。',
        content_documents: '课程资料（PDF 或 PowerPoint）',
        content_documents_help: '已报名的学员可将其保存在书架中，并在应用内离线阅读。',
        optional: '可选', drop_files: '点击或将文件拖到此处', max_per_file: '每个文件最大 :max',
        document_bad_extension: '不支持该格式。请使用 PDF、PPT 或 PPTX。',
        course_created_with_content: '课程已创建，包括模块、课时和内容。请完善课时，然后提交审核。',
        lesson_n: '第 :number 课',
        course_materials: '课程资料',
        course_materials_help: '加入书架后可随时随地阅读，离线也可以。',
        teaching: '教学',
        js: {
            playlist_detected: '已识别 YouTube 播放列表',
            playlist_no_video: '此课时在播放列表中没有对应的视频。',
            next_video_in: ':seconds 秒后播放下一个视频…',
            slides_open_help: 'PowerPoint 文件将在你的演示文稿应用（PowerPoint、Google 幻灯片、WPS…）中打开；保存到书架后离线也可打开。',
            slides_open: '打开演示文稿',
            document_bad_extension: '不支持该格式。请使用 PDF、PPT 或 PPTX。',
        },
    },
    ar: {
        wizard_help: 'أربع خطوات. لا تُنشأ الدورة إلا في النهاية، مع وحداتها ودروسها ومحتواها.',
        wizard_step_structure: 'الوحدات والدروس', wizard_step_content: 'المحتوى',
        wizard_fix_errors: 'هناك معلومات ناقصة أو غير صحيحة: راجع الخطوات أدناه.',
        structure_help: 'قسّم الدورة إلى وحدات. لكل وحدة أدخل اسمها وعدد دروسها: تُنشأ الدروس تلقائيًا (يمكنك إعادة تسميتها لاحقًا).',
        lessons_number: 'الدروس', structure_total: 'عدد الوحدات: :modules، عدد الدروس: :lessons',
        structure_required: 'أضف وحدة واحدة على الأقل.',
        content_help: 'اختر خيارًا واحدًا على الأقل. توضع مقاطع الفيديو في الدروس بالترتيب.',
        content_required: 'اختر نوع محتوى واحدًا على الأقل: رابط YouTube أو فيديو أو مادة دراسية.',
        content_youtube: 'فيديو أو قائمة تشغيل على YouTube',
        content_youtube_help: 'تملأ قائمة التشغيل الدروس بالترتيب (الفيديو 1 ← الدرس 1…)، وفي نهاية كل فيديو يُقترح على الطالب الفيديو التالي داخل المنصة.',
        content_youtube_placeholder: 'https://www.youtube.com/playlist?list=…',
        content_videos: 'رفع مقاطع فيديو (بحد أقصى :max ميغابايت لكل منها)',
        content_videos_help: 'فيديو واحد لكل درس بترتيب القائمة. إذا كانت المقاطع أكثر من الدروس تُضاف دروس إلى الوحدة الأخيرة.',
        content_documents: 'مادة الدورة (PDF أو PowerPoint)',
        content_documents_help: 'يحتفظ بها الطلاب المسجّلون في مكتبتهم ويقرؤونها دون اتصال في التطبيق.',
        optional: 'اختياري', drop_files: 'انقر أو أفلت الملفات هنا', max_per_file: 'الحد الأقصى :max لكل ملف',
        document_bad_extension: 'صيغة غير مقبولة. استخدم PDF أو PPT أو PPTX.',
        course_created_with_content: 'تم إنشاء الدورة مع وحداتها ودروسها ومحتواها. أكمل الدروس ثم أرسلها للمراجعة.',
        lesson_n: 'الدرس :number',
        course_materials: 'مواد الدورة',
        course_materials_help: 'أضفها إلى مكتبتك لقراءتها في أي مكان، حتى دون اتصال.',
        teaching: 'التدريس',
        js: {
            playlist_detected: 'تم التعرّف على قائمة تشغيل YouTube',
            playlist_no_video: 'لا يوجد فيديو لهذا الدرس في قائمة التشغيل.',
            next_video_in: 'الفيديو التالي بعد :seconds ثانية…',
            slides_open_help: 'تُفتح ملفات PowerPoint في تطبيق العروض لديك (PowerPoint أو Google Slides أو WPS…)، ودون اتصال أيضًا بعد حفظها في مكتبتك.',
            slides_open: 'فتح العرض',
            document_bad_extension: 'صيغة غير مقبولة. استخدم PDF أو PPT أو PPTX.',
        },
    },
};
module.exports = T;
