// "learn" group — new course wizard and presentation video. Merged into learn.cjs.
module.exports = {
    en: {
        wizard_help: 'Three short steps. The course is only created at the end; you will then add modules and lessons.',
        wizard_step_info: 'Information',
        wizard_step_category: 'Category and picture',
        wizard_step_video: 'Presentation video',
        thumbnail_generated_help: 'Without a picture, a cover is generated from the title.',
        intro_video: 'Presentation video',
        intro_video_help: 'Optional. Paste the link of a YouTube video (e.g. https://youtu.be/…): it plays on the course page, inside the platform.',
        create_course: 'Create the course',
    },
    fr: {
        wizard_help: 'Trois étapes rapides. Le cours n’est créé qu’à la fin ; vous ajouterez ensuite les modules et les leçons.',
        wizard_step_info: 'Informations',
        wizard_step_category: 'Catégorie et image',
        wizard_step_video: 'Vidéo de présentation',
        thumbnail_generated_help: 'Sans image, une couverture est générée à partir du titre.',
        intro_video: 'Vidéo de présentation',
        intro_video_help: 'Facultatif. Collez le lien d’une vidéo YouTube (ex. https://youtu.be/…) : elle est lue sur la page du cours, dans la plateforme.',
        create_course: 'Créer le cours',
    },
    es: {
        wizard_help: 'Tres pasos rápidos. El curso solo se crea al final; después añadirás los módulos y las lecciones.',
        wizard_step_info: 'Información',
        wizard_step_category: 'Categoría e imagen',
        wizard_step_video: 'Vídeo de presentación',
        thumbnail_generated_help: 'Sin imagen, se genera una portada a partir del título.',
        intro_video: 'Vídeo de presentación',
        intro_video_help: 'Opcional. Pega el enlace de un vídeo de YouTube (p. ej. https://youtu.be/…): se reproduce en la página del curso, dentro de la plataforma.',
        create_course: 'Crear el curso',
    },
    pt: {
        wizard_help: 'Três passos rápidos. O curso só é criado no fim; depois vai adicionar os módulos e as aulas.',
        wizard_step_info: 'Informações',
        wizard_step_category: 'Categoria e imagem',
        wizard_step_video: 'Vídeo de apresentação',
        thumbnail_generated_help: 'Sem imagem, é gerada uma capa a partir do título.',
        intro_video: 'Vídeo de apresentação',
        intro_video_help: 'Opcional. Cole a ligação de um vídeo do YouTube (ex. https://youtu.be/…): é reproduzido na página do curso, dentro da plataforma.',
        create_course: 'Criar o curso',
    },
    zh: {
        wizard_help: '三个简单步骤。课程在最后一步才会创建，之后再添加模块和课时。',
        wizard_step_info: '基本信息',
        wizard_step_category: '分类与图片',
        wizard_step_video: '介绍视频',
        thumbnail_generated_help: '未上传图片时，将根据标题自动生成封面。',
        intro_video: '介绍视频',
        intro_video_help: '可选。粘贴 YouTube 视频链接（如 https://youtu.be/…），视频将在平台内的课程页面播放。',
        create_course: '创建课程',
    },
    ar: {
        wizard_help: 'ثلاث خطوات سريعة. لا تُنشأ الدورة إلا في النهاية، ثم تضيف الوحدات والدروس.',
        wizard_step_info: 'المعلومات',
        wizard_step_category: 'الفئة والصورة',
        wizard_step_video: 'فيديو التعريف',
        thumbnail_generated_help: 'بدون صورة، يتم إنشاء غلاف انطلاقًا من العنوان.',
        intro_video: 'فيديو التعريف',
        intro_video_help: 'اختياري. الصق رابط فيديو على YouTube (مثل https://youtu.be/…): يُعرض في صفحة الدورة داخل المنصة.',
        create_course: 'إنشاء الدورة',
    },
};
