// "learn" group: assessment path (lesson quizzes, module exercises, final evaluation),
// knowledge tracking and the student library — all six languages in one place.
// Build: node scripts/write-group.cjs learn resources/lang-src/learn.cjs
module.exports = {
    en: {
        // Path & player
        final_evaluation: 'Final evaluation',
        module_exercise: 'Module exercise',
        module_exercise_of: 'Exercise — :module',
        lesson_quiz: 'Lesson quiz',
        lesson_quiz_of: 'Quiz — :lesson',
        assessment_locked: 'Finish the previous steps to unlock this assessment.',
        step_x_of_y: 'Step :x of :y',
        with_quiz: 'quiz',
        take_lesson_quiz: 'Take the lesson quiz',
        lesson_quiz_rule: 'Score at least :score % (7 out of 10) in the quiz to validate this lesson.',
        check_your_knowledge: 'Check your knowledge',
        module_exercise_intro: 'This exercise covers the whole module. Pass it to validate the module and move on.',
        final_intro: 'The final evaluation covers the whole course. Pass it to complete the course and receive your certificate.',
        quiz_failed_need: 'Not passed: you need at least :score %. Review the lesson and try again.',
        mode_not_available: 'This mode is only available for the final evaluation.',
        // Diagnostic / retake
        diagnostic_title: 'Placement test',
        diagnostic_banner: 'Measure your starting level with the final evaluation. It does not count towards your progress; it lets you see how much you learn.',
        diagnostic_start: 'Take the placement test',
        diagnostic_intro: 'This placement test measures what you already know before studying. It does not count towards your progress and the answers are not shown.',
        diagnostic_done: 'Placement test done: :score %. Your starting level is saved.',
        diagnostic_already_taken: 'The placement test can only be taken once, before the final evaluation.',
        later: 'Later',
        retake_title: 'Re-evaluation',
        retake_intro: 'Re-take the final evaluation to check that your knowledge is still there. It does not change your certificate.',
        retake_start: 'Re-evaluate my knowledge',
        retake_done: 'Re-evaluation done: :score %.',
        retake_after_pass: 'Re-evaluations are available once the final evaluation is passed.',
        retake_available_on: 'Next re-evaluation possible on :date.',
        final_passed_retake_hint: 'Final evaluation passed. Come back regularly to re-evaluate your knowledge and follow its evolution.',
        // Knowledge
        my_results: 'My results',
        knowledge_evolution: 'Knowledge evolution',
        knowledge_evolution_help: 'Measured with the final evaluation: placement test, end of course, then re-evaluations.',
        knowledge_chart: 'Evolution of the final evaluation scores',
        no_final_evaluation: 'This course has no final evaluation yet.',
        starting_level: 'Starting level',
        first_evaluation: 'First evaluation',
        current_level: 'Current level',
        knowledge_gain: 'Progress',
        trend: 'Trend',
        trend_progress: 'Progressing',
        trend_regression: 'Regressing',
        trend_stable: 'Stable',
        trend_single: 'One evaluation',
        trend_none: 'Not evaluated',
        knowledge_level_beginner: 'Beginner',
        knowledge_level_intermediate: 'Intermediate',
        knowledge_level_advanced: 'Advanced',
        knowledge_level_expert: 'Expert',
        mode_diagnostic: 'Placement test',
        mode_standard: 'Final evaluation',
        mode_retake: 'Re-evaluation',
        pass_line: 'Pass mark (:score %)',
        mastery_by_module: 'Mastery by module',
        mastery_by_module_help: 'Average score per module (final evaluation, otherwise module exercise).',
        while_studying: 'While studying',
        lesson_quiz_average: 'Lesson quizzes (average)',
        module_exercise_average: 'Module exercises (average)',
        evaluation_history: 'Evaluation history',
        best_evaluation: 'Best evaluation',
        date: 'Date',
        type: 'Type',
        result: 'Level',
        points: ':value pts',
        not_evaluated: 'Not evaluated',
        student_not_evaluated: 'This student has not taken the final evaluation yet.',
        notif_regression_subject: 'A student is regressing',
        notif_regression_line: ':student scored :score % in the final evaluation of ":course", :delta points less than before.',
        notif_reassess_subject: 'Time to re-evaluate your knowledge',
        notif_reassess_line: 'Take the final evaluation of ":course" again to check what you remember.',
        // Instructor
        tab_assessments: 'Assessments',
        tab_books: 'Books',
        assessment_editor: 'Assessment',
        assessment_path: 'Assessment path of the course',
        path_lesson: 'After each lesson: a quiz of at least :min questions; the student must score :pass % (7/10) to validate the lesson.',
        path_module: 'After each module: a complete exercise of at least :min questions (pass mark :pass %).',
        path_final: 'After the course: a final evaluation of at least :min questions (pass mark :pass %). It is also used as a placement test and for re-evaluations, to measure each student\'s progression or regression.',
        assessment_plan: 'Assessment plan',
        assessment_plan_help: 'Every assessment of the course and its number of questions.',
        scope_help_lesson: 'The lesson quiz validates the lesson: at least :min questions, pass mark :pass % (7/10).',
        scope_help_module: 'The module exercise closes the module: at least :min questions, pass mark :pass %.',
        scope_help_course: 'The final evaluation closes the course: at least :min questions, pass mark :pass %. Tag each question with its module to measure knowledge per module.',
        quiz_lesson_help: 'This lesson is a quiz: at least :min questions, pass mark :pass %.',
        questions_of_min: ':count/:min questions',
        questions_missing: '{1} :count question missing.|[2,*] :count questions missing.',
        edit_questions: 'Edit the questions',
        create_quiz: 'Create the quiz',
        pass_minimum: 'Minimum :pass % (platform rule).',
        final_settings_help: 'Tip: keep "show correct answers" off so that re-evaluations stay meaningful.',
        import_questions: 'Import questions',
        import_help: 'Paste your questions: one block per question, separated by an empty line.',
        import_example: 'Example',
        import_sample: "What is the capital of Cameroon?\n- Douala\n* Yaoundé\n- Bertoua\n> Yaoundé is the political capital.\n\nWhich of these are even numbers?\n* 2\n- 3\n* 4",
        import_block_error: 'Block :number ignored (":question"): it needs at least two options and one right answer (line starting with *).',
        import_empty: 'No question found.',
        questions_imported: '{1} :count question imported.|[2,*] :count questions imported.',
        question_module: 'Module assessed',
        no_module: 'Whole course',
        question_module_help: 'Used to measure knowledge per module.',
        explanation: 'Explanation (optional)',
        explanation_placeholder: 'Shown to the student after answering.',
        final_evaluation_help: 'Closes the course and measures the progression of each student.',
        check_lesson_quizzes: 'A quiz of at least :min questions after each lesson',
        check_module_exercises: 'An exercise of at least :min questions after each module',
        check_final_evaluation: 'A final evaluation of at least :min questions',
        knowledge_tracking: 'Knowledge tracking',
        knowledge_tracking_help: 'Level of each student measured with the final evaluation (placement test, end of course, re-evaluations) and its evolution.',
        final_needed_for_tracking: 'Add a final evaluation of at least :min questions to measure your students\' knowledge.',
        edit_final_evaluation: 'Edit the final evaluation',
        evaluated_students: 'Evaluated students',
        average_level: 'Average level',
        average_gain: 'Average progress',
        in_progression: 'Progressing',
        in_regression: 'Regressing',
        students_knowledge: 'Your students\' knowledge',
        students_knowledge_help: 'Measured with the final evaluation of each course: starting level, current level, progression or regression.',
        students_in_regression: 'Students regressing',
        // Books & library
        books_help: 'PDF books and audio or video documents. Enrolled students add them to their library and read them in the app, even offline.',
        book_author: 'Author',
        book_formats: 'PDF, MP3, M4A, OGG, WAV, MP4, WebM — max. :max',
        no_books: 'No book for this course yet.',
        confirm_delete_book: 'Delete this book? It will disappear from the students\' libraries.',
        book_uploaded: 'Book added.',
        book_updated: 'Book updated.',
        book_deleted: 'Book deleted.',
        my_library: 'My library',
        library_help: 'Books you add are saved in your account, not in your device\'s files: you find them on every device where you sign in, and the app keeps a private copy to read them offline.',
        library_empty: 'Your library is empty',
        library_empty_help: 'Add the books of your courses to read them anywhere, even without Internet.',
        books_of_my_courses: 'Books of my courses',
        course_books: 'Course books',
        add_to_library: 'Add to my library',
        in_library: 'In my library',
        remove_from_library: 'Remove from my library',
        confirm_remove_book: 'Remove this book from your library? It will also be removed from your devices.',
        book_added: 'Book added to your library. It will be available offline on your devices.',
        book_removed: 'Book removed from your library.',
        read: 'Read',
        continue_reading: 'Continue reading',
        open: 'Open',
        hero_image: 'Home page photo',
        hero_image_help: 'JPG, PNG or WebP, landscape (e.g. 1920×1080), max. 5 MB. Shown behind the title of the home page.',
        hero_image_reset: 'Go back to the default photo',
        cert_awarded_to: 'This certificate is proudly awarded to',
        cert_hours: 'Course duration: :hours',
        cert_final_score: 'Final evaluation: :score %',
        js: {
            now_take_quiz: 'Video finished: take the quiz to validate the lesson.',
            knowledge_evolution: 'Knowledge evolution',
            current_level: 'Current level',
            knowledge_gain: 'Progress',
            trend_progress: 'Progressing', trend_regression: 'Regressing', trend_stable: 'Stable',
            trend_single: 'First evaluation', trend_none: 'Not evaluated',
            media_error: 'This document cannot be opened.',
            media_not_offline: 'This document is not available offline on this device.',
            zoom_in: 'Zoom in', zoom_out: 'Zoom out', page_x_of_y: ':x / :y',
            close: 'Close', loading: 'Loading…', read: 'Read',
            my_library: 'My library',
            library_offline_help: 'Books of your library saved on this device.',
            library_empty_offline: 'No book saved on this device yet. Open "My library" when you are online.',
            book_not_downloaded: 'Not saved on this device',
            book_downloading: 'Saving on this device…',
            final_online_only: 'final evaluation — online only',
            with_quiz: 'quiz',
            questions_n: 'Questions: :count',
            check_your_knowledge: 'Check your knowledge',
            take_lesson_quiz: 'Take the lesson quiz',
            pass_at: 'Pass mark: :score %',
            provisional_score: 'Provisional score: :score % (:correct/:total)',
            provisional_passed: 'passed (confirmed when back online)',
            provisional_failed: 'not passed: :score % needed',
        },
    },

    fr: {
        final_evaluation: 'Évaluation finale',
        module_exercise: 'Exercice du module',
        module_exercise_of: 'Exercice — :module',
        lesson_quiz: 'Quiz de la leçon',
        lesson_quiz_of: 'Quiz — :lesson',
        assessment_locked: 'Terminez les étapes précédentes pour débloquer cette évaluation.',
        step_x_of_y: 'Étape :x sur :y',
        with_quiz: 'quiz',
        take_lesson_quiz: 'Passer le quiz de la leçon',
        lesson_quiz_rule: 'Obtenez au moins :score % (7 sur 10) au quiz pour valider cette leçon.',
        check_your_knowledge: 'Vérifiez vos acquis',
        module_exercise_intro: 'Cet exercice porte sur tout le module. Réussissez-le pour valider le module et continuer.',
        final_intro: 'L’évaluation finale porte sur tout le cours. Réussissez-la pour terminer le cours et obtenir votre certificat.',
        quiz_failed_need: 'Non validé : il faut au moins :score %. Revoyez la leçon puis réessayez.',
        mode_not_available: 'Ce mode n’existe que pour l’évaluation finale.',
        diagnostic_title: 'Test de positionnement',
        diagnostic_banner: 'Mesurez votre niveau de départ avec l’évaluation finale. Il ne compte pas dans votre progression : il permet de voir tout ce que vous apprenez.',
        diagnostic_start: 'Passer le test de positionnement',
        diagnostic_intro: 'Ce test mesure ce que vous savez déjà avant d’étudier. Il ne compte pas dans votre progression et les réponses ne sont pas affichées.',
        diagnostic_done: 'Test de positionnement terminé : :score %. Votre niveau de départ est enregistré.',
        diagnostic_already_taken: 'Le test de positionnement ne peut être passé qu’une fois, avant l’évaluation finale.',
        later: 'Plus tard',
        retake_title: 'Réévaluation',
        retake_intro: 'Repassez l’évaluation finale pour vérifier que vos connaissances sont toujours là. Votre certificat n’est pas modifié.',
        retake_start: 'Réévaluer mes connaissances',
        retake_done: 'Réévaluation terminée : :score %.',
        retake_after_pass: 'Les réévaluations sont possibles une fois l’évaluation finale réussie.',
        retake_available_on: 'Prochaine réévaluation possible le :date.',
        final_passed_retake_hint: 'Évaluation finale réussie. Revenez régulièrement réévaluer vos connaissances et suivre leur évolution.',
        my_results: 'Mes résultats',
        knowledge_evolution: 'Évolution des connaissances',
        knowledge_evolution_help: 'Mesurée avec l’évaluation finale : test de positionnement, fin de cours, puis réévaluations.',
        knowledge_chart: 'Évolution des scores à l’évaluation finale',
        no_final_evaluation: 'Ce cours n’a pas encore d’évaluation finale.',
        starting_level: 'Niveau de départ',
        first_evaluation: 'Première évaluation',
        current_level: 'Niveau actuel',
        knowledge_gain: 'Progression',
        trend: 'Tendance',
        trend_progress: 'En progression',
        trend_regression: 'En régression',
        trend_stable: 'Stable',
        trend_single: 'Une évaluation',
        trend_none: 'Non évalué',
        knowledge_level_beginner: 'Débutant',
        knowledge_level_intermediate: 'Intermédiaire',
        knowledge_level_advanced: 'Avancé',
        knowledge_level_expert: 'Expert',
        mode_diagnostic: 'Test de positionnement',
        mode_standard: 'Évaluation finale',
        mode_retake: 'Réévaluation',
        pass_line: 'Seuil de réussite (:score %)',
        mastery_by_module: 'Maîtrise par module',
        mastery_by_module_help: 'Score moyen par module (évaluation finale, sinon exercice du module).',
        while_studying: 'Pendant l’apprentissage',
        lesson_quiz_average: 'Quiz des leçons (moyenne)',
        module_exercise_average: 'Exercices des modules (moyenne)',
        evaluation_history: 'Historique des évaluations',
        best_evaluation: 'Meilleure évaluation',
        date: 'Date',
        type: 'Type',
        result: 'Niveau',
        points: ':value pts',
        not_evaluated: 'Non évalué',
        student_not_evaluated: 'Cet étudiant n’a pas encore passé l’évaluation finale.',
        notif_regression_subject: 'Un étudiant est en régression',
        notif_regression_line: ':student a obtenu :score % à l’évaluation finale de « :course », soit :delta points de moins qu’avant.',
        notif_reassess_subject: 'Réévaluez vos connaissances',
        notif_reassess_line: 'Repassez l’évaluation finale de « :course » pour vérifier ce que vous avez retenu.',
        tab_assessments: 'Évaluations',
        tab_books: 'Livres',
        assessment_editor: 'Évaluation',
        assessment_path: 'Parcours d’évaluation du cours',
        path_lesson: 'Après chaque leçon : un quiz d’au moins :min questions ; l’étudiant doit obtenir :pass % (7/10) pour valider la leçon.',
        path_module: 'Après chaque module : un exercice complet d’au moins :min questions (réussite à :pass %).',
        path_final: 'Après le cours : une évaluation finale d’au moins :min questions (réussite à :pass %). Elle sert aussi de test de positionnement et de réévaluation pour mesurer la progression ou la régression de chaque étudiant.',
        assessment_plan: 'Plan d’évaluation',
        assessment_plan_help: 'Toutes les évaluations du cours et leur nombre de questions.',
        scope_help_lesson: 'Le quiz de la leçon valide la leçon : au moins :min questions, réussite à :pass % (7/10).',
        scope_help_module: 'L’exercice clôt le module : au moins :min questions, réussite à :pass %.',
        scope_help_course: 'L’évaluation finale clôt le cours : au moins :min questions, réussite à :pass %. Associez chaque question à son module pour mesurer la maîtrise par module.',
        quiz_lesson_help: 'Cette leçon est un quiz : au moins :min questions, réussite à :pass %.',
        questions_of_min: ':count/:min questions',
        questions_missing: '{1} Il manque :count question.|[2,*] Il manque :count questions.',
        edit_questions: 'Modifier les questions',
        create_quiz: 'Créer le quiz',
        pass_minimum: 'Minimum :pass % (règle de la plateforme).',
        final_settings_help: 'Conseil : laissez « afficher les bonnes réponses » désactivé pour que les réévaluations restent pertinentes.',
        import_questions: 'Importer des questions',
        import_help: 'Collez vos questions : un bloc par question, séparés par une ligne vide.',
        import_example: 'Exemple',
        import_sample: "Quelle est la capitale du Cameroun ?\n- Douala\n* Yaoundé\n- Bertoua\n> Yaoundé est la capitale politique.\n\nLesquels sont des nombres pairs ?\n* 2\n- 3\n* 4",
        import_block_error: 'Bloc :number ignoré (« :question ») : il faut au moins deux propositions et une bonne réponse (ligne commençant par *).',
        import_empty: 'Aucune question trouvée.',
        questions_imported: '{1} :count question importée.|[2,*] :count questions importées.',
        question_module: 'Module évalué',
        no_module: 'Tout le cours',
        question_module_help: 'Sert à mesurer la maîtrise par module.',
        explanation: 'Explication (facultatif)',
        explanation_placeholder: 'Affichée à l’étudiant après sa réponse.',
        final_evaluation_help: 'Clôt le cours et mesure la progression de chaque étudiant.',
        check_lesson_quizzes: 'Un quiz d’au moins :min questions après chaque leçon',
        check_module_exercises: 'Un exercice d’au moins :min questions après chaque module',
        check_final_evaluation: 'Une évaluation finale d’au moins :min questions',
        knowledge_tracking: 'Suivi des connaissances',
        knowledge_tracking_help: 'Niveau de chaque étudiant mesuré avec l’évaluation finale (positionnement, fin de cours, réévaluations) et son évolution.',
        final_needed_for_tracking: 'Ajoutez une évaluation finale d’au moins :min questions pour mesurer les connaissances de vos étudiants.',
        edit_final_evaluation: 'Modifier l’évaluation finale',
        evaluated_students: 'Étudiants évalués',
        average_level: 'Niveau moyen',
        average_gain: 'Progression moyenne',
        in_progression: 'En progression',
        in_regression: 'En régression',
        students_knowledge: 'Connaissances de vos étudiants',
        students_knowledge_help: 'Mesurées avec l’évaluation finale de chaque cours : niveau de départ, niveau actuel, progression ou régression.',
        students_in_regression: 'Étudiants en régression',
        books_help: 'Livres PDF et documents audio ou vidéo. Les étudiants inscrits les ajoutent à leur bibliothèque et les lisent dans l’application, même hors ligne.',
        book_author: 'Auteur',
        book_formats: 'PDF, MP3, M4A, OGG, WAV, MP4, WebM — max. :max',
        no_books: 'Aucun livre pour ce cours.',
        confirm_delete_book: 'Supprimer ce livre ? Il disparaîtra des bibliothèques des étudiants.',
        book_uploaded: 'Livre ajouté.',
        book_updated: 'Livre mis à jour.',
        book_deleted: 'Livre supprimé.',
        my_library: 'Ma bibliothèque',
        library_help: 'Les livres ajoutés sont enregistrés dans votre compte, pas dans les fichiers de votre appareil : vous les retrouvez sur tous les appareils où vous vous connectez, et l’application en garde une copie privée pour les lire hors ligne.',
        library_empty: 'Votre bibliothèque est vide',
        library_empty_help: 'Ajoutez les livres de vos cours pour les lire partout, même sans Internet.',
        books_of_my_courses: 'Livres de mes cours',
        course_books: 'Livres du cours',
        add_to_library: 'Ajouter à ma bibliothèque',
        in_library: 'Dans ma bibliothèque',
        remove_from_library: 'Retirer de ma bibliothèque',
        confirm_remove_book: 'Retirer ce livre de votre bibliothèque ? Il sera aussi retiré de vos appareils.',
        book_added: 'Livre ajouté à votre bibliothèque. Il sera disponible hors ligne sur vos appareils.',
        book_removed: 'Livre retiré de votre bibliothèque.',
        read: 'Lire',
        continue_reading: 'Reprendre la lecture',
        open: 'Ouvrir',
        hero_image: 'Photo de la page d’accueil',
        hero_image_help: 'JPG, PNG ou WebP, au format paysage (ex. 1920×1080), 5 Mo max. Affichée derrière le titre de la page d’accueil.',
        hero_image_reset: 'Revenir à la photo par défaut',
        cert_awarded_to: 'Ce certificat est décerné à',
        cert_hours: 'Durée du cours : :hours',
        cert_final_score: 'Évaluation finale : :score %',
        js: {
            now_take_quiz: 'Vidéo terminée : passez le quiz pour valider la leçon.',
            knowledge_evolution: 'Évolution des connaissances',
            current_level: 'Niveau actuel',
            knowledge_gain: 'Progression',
            trend_progress: 'En progression', trend_regression: 'En régression', trend_stable: 'Stable',
            trend_single: 'Première évaluation', trend_none: 'Non évalué',
            media_error: 'Impossible d’ouvrir ce document.',
            media_not_offline: 'Ce document n’est pas disponible hors ligne sur cet appareil.',
            zoom_in: 'Agrandir', zoom_out: 'Réduire', page_x_of_y: ':x / :y',
            close: 'Fermer', loading: 'Chargement…', read: 'Lire',
            my_library: 'Ma bibliothèque',
            library_offline_help: 'Livres de votre bibliothèque enregistrés sur cet appareil.',
            library_empty_offline: 'Aucun livre enregistré sur cet appareil. Ouvrez « Ma bibliothèque » quand vous êtes connecté.',
            book_not_downloaded: 'Pas encore sur cet appareil',
            book_downloading: 'Enregistrement sur cet appareil…',
            final_online_only: 'évaluation finale — en ligne uniquement',
            with_quiz: 'quiz',
            questions_n: 'Questions : :count',
            check_your_knowledge: 'Vérifiez vos acquis',
            take_lesson_quiz: 'Passer le quiz de la leçon',
            pass_at: 'Réussite : :score %',
            provisional_score: 'Score provisoire : :score % (:correct/:total)',
            provisional_passed: 'validé (confirmé au retour de la connexion)',
            provisional_failed: 'non validé : il faut :score %',
        },
    },

    es: {
        final_evaluation: 'Evaluación final',
        module_exercise: 'Ejercicio del módulo',
        module_exercise_of: 'Ejercicio — :module',
        lesson_quiz: 'Cuestionario de la lección',
        lesson_quiz_of: 'Cuestionario — :lesson',
        assessment_locked: 'Termina los pasos anteriores para desbloquear esta evaluación.',
        step_x_of_y: 'Paso :x de :y',
        with_quiz: 'cuestionario',
        take_lesson_quiz: 'Hacer el cuestionario de la lección',
        lesson_quiz_rule: 'Obtén al menos :score % (7 de 10) en el cuestionario para validar esta lección.',
        check_your_knowledge: 'Comprueba lo que has aprendido',
        module_exercise_intro: 'Este ejercicio abarca todo el módulo. Apruébalo para validar el módulo y continuar.',
        final_intro: 'La evaluación final abarca todo el curso. Apruébala para terminar el curso y obtener tu certificado.',
        quiz_failed_need: 'No aprobado: necesitas al menos :score %. Repasa la lección e inténtalo de nuevo.',
        mode_not_available: 'Este modo solo existe para la evaluación final.',
        diagnostic_title: 'Prueba de nivel',
        diagnostic_banner: 'Mide tu nivel inicial con la evaluación final. No cuenta para tu progreso: te permite ver todo lo que aprendes.',
        diagnostic_start: 'Hacer la prueba de nivel',
        diagnostic_intro: 'Esta prueba mide lo que ya sabes antes de estudiar. No cuenta para tu progreso y no se muestran las respuestas.',
        diagnostic_done: 'Prueba de nivel terminada: :score %. Tu nivel inicial ha quedado registrado.',
        diagnostic_already_taken: 'La prueba de nivel solo se puede hacer una vez, antes de la evaluación final.',
        later: 'Más tarde',
        retake_title: 'Reevaluación',
        retake_intro: 'Vuelve a hacer la evaluación final para comprobar que conservas tus conocimientos. Tu certificado no cambia.',
        retake_start: 'Reevaluar mis conocimientos',
        retake_done: 'Reevaluación terminada: :score %.',
        retake_after_pass: 'Las reevaluaciones están disponibles una vez aprobada la evaluación final.',
        retake_available_on: 'Próxima reevaluación posible el :date.',
        final_passed_retake_hint: 'Evaluación final aprobada. Vuelve con regularidad para reevaluar tus conocimientos y seguir su evolución.',
        my_results: 'Mis resultados',
        knowledge_evolution: 'Evolución de los conocimientos',
        knowledge_evolution_help: 'Medida con la evaluación final: prueba de nivel, fin del curso y luego reevaluaciones.',
        knowledge_chart: 'Evolución de las puntuaciones de la evaluación final',
        no_final_evaluation: 'Este curso aún no tiene evaluación final.',
        starting_level: 'Nivel inicial',
        first_evaluation: 'Primera evaluación',
        current_level: 'Nivel actual',
        knowledge_gain: 'Progreso',
        trend: 'Tendencia',
        trend_progress: 'En progreso',
        trend_regression: 'En retroceso',
        trend_stable: 'Estable',
        trend_single: 'Una evaluación',
        trend_none: 'Sin evaluar',
        knowledge_level_beginner: 'Principiante',
        knowledge_level_intermediate: 'Intermedio',
        knowledge_level_advanced: 'Avanzado',
        knowledge_level_expert: 'Experto',
        mode_diagnostic: 'Prueba de nivel',
        mode_standard: 'Evaluación final',
        mode_retake: 'Reevaluación',
        pass_line: 'Nota de aprobado (:score %)',
        mastery_by_module: 'Dominio por módulo',
        mastery_by_module_help: 'Puntuación media por módulo (evaluación final o, si no, ejercicio del módulo).',
        while_studying: 'Durante el aprendizaje',
        lesson_quiz_average: 'Cuestionarios de lecciones (media)',
        module_exercise_average: 'Ejercicios de módulos (media)',
        evaluation_history: 'Historial de evaluaciones',
        best_evaluation: 'Mejor evaluación',
        date: 'Fecha',
        type: 'Tipo',
        result: 'Nivel',
        points: ':value pts',
        not_evaluated: 'Sin evaluar',
        student_not_evaluated: 'Este estudiante aún no ha hecho la evaluación final.',
        notif_regression_subject: 'Un estudiante retrocede',
        notif_regression_line: ':student obtuvo :score % en la evaluación final de «:course», :delta puntos menos que antes.',
        notif_reassess_subject: 'Es hora de reevaluar tus conocimientos',
        notif_reassess_line: 'Vuelve a hacer la evaluación final de «:course» para comprobar lo que recuerdas.',
        tab_assessments: 'Evaluaciones',
        tab_books: 'Libros',
        assessment_editor: 'Evaluación',
        assessment_path: 'Recorrido de evaluación del curso',
        path_lesson: 'Después de cada lección: un cuestionario de al menos :min preguntas; el estudiante debe obtener :pass % (7/10) para validar la lección.',
        path_module: 'Después de cada módulo: un ejercicio completo de al menos :min preguntas (aprobado con :pass %).',
        path_final: 'Después del curso: una evaluación final de al menos :min preguntas (aprobado con :pass %). También sirve como prueba de nivel y como reevaluación para medir el progreso o el retroceso de cada estudiante.',
        assessment_plan: 'Plan de evaluación',
        assessment_plan_help: 'Todas las evaluaciones del curso y su número de preguntas.',
        scope_help_lesson: 'El cuestionario valida la lección: al menos :min preguntas, aprobado con :pass % (7/10).',
        scope_help_module: 'El ejercicio cierra el módulo: al menos :min preguntas, aprobado con :pass %.',
        scope_help_course: 'La evaluación final cierra el curso: al menos :min preguntas, aprobado con :pass %. Asocia cada pregunta a su módulo para medir el dominio por módulo.',
        quiz_lesson_help: 'Esta lección es un cuestionario: al menos :min preguntas, aprobado con :pass %.',
        questions_of_min: ':count/:min preguntas',
        questions_missing: '{1} Falta :count pregunta.|[2,*] Faltan :count preguntas.',
        edit_questions: 'Editar las preguntas',
        create_quiz: 'Crear el cuestionario',
        pass_minimum: 'Mínimo :pass % (regla de la plataforma).',
        final_settings_help: 'Consejo: deja desactivado «mostrar las respuestas correctas» para que las reevaluaciones sigan siendo útiles.',
        import_questions: 'Importar preguntas',
        import_help: 'Pega tus preguntas: un bloque por pregunta, separados por una línea vacía.',
        import_example: 'Ejemplo',
        import_sample: "¿Cuál es la capital de Camerún?\n- Duala\n* Yaundé\n- Bertoua\n> Yaundé es la capital política.\n\n¿Cuáles son números pares?\n* 2\n- 3\n* 4",
        import_block_error: 'Bloque :number ignorado («:question»): necesita al menos dos opciones y una respuesta correcta (línea que empieza por *).',
        import_empty: 'No se encontró ninguna pregunta.',
        questions_imported: '{1} :count pregunta importada.|[2,*] :count preguntas importadas.',
        question_module: 'Módulo evaluado',
        no_module: 'Todo el curso',
        question_module_help: 'Sirve para medir el dominio por módulo.',
        explanation: 'Explicación (opcional)',
        explanation_placeholder: 'Se muestra al estudiante después de responder.',
        final_evaluation_help: 'Cierra el curso y mide el progreso de cada estudiante.',
        check_lesson_quizzes: 'Un cuestionario de al menos :min preguntas después de cada lección',
        check_module_exercises: 'Un ejercicio de al menos :min preguntas después de cada módulo',
        check_final_evaluation: 'Una evaluación final de al menos :min preguntas',
        knowledge_tracking: 'Seguimiento de conocimientos',
        knowledge_tracking_help: 'Nivel de cada estudiante medido con la evaluación final (prueba de nivel, fin del curso, reevaluaciones) y su evolución.',
        final_needed_for_tracking: 'Añade una evaluación final de al menos :min preguntas para medir los conocimientos de tus estudiantes.',
        edit_final_evaluation: 'Editar la evaluación final',
        evaluated_students: 'Estudiantes evaluados',
        average_level: 'Nivel medio',
        average_gain: 'Progreso medio',
        in_progression: 'En progreso',
        in_regression: 'En retroceso',
        students_knowledge: 'Conocimientos de tus estudiantes',
        students_knowledge_help: 'Medidos con la evaluación final de cada curso: nivel inicial, nivel actual, progreso o retroceso.',
        students_in_regression: 'Estudiantes en retroceso',
        books_help: 'Libros en PDF y documentos de audio o vídeo. Los estudiantes inscritos los añaden a su biblioteca y los leen en la aplicación, incluso sin conexión.',
        book_author: 'Autor',
        book_formats: 'PDF, MP3, M4A, OGG, WAV, MP4, WebM — máx. :max',
        no_books: 'Este curso aún no tiene libros.',
        confirm_delete_book: '¿Eliminar este libro? Desaparecerá de las bibliotecas de los estudiantes.',
        book_uploaded: 'Libro añadido.',
        book_updated: 'Libro actualizado.',
        book_deleted: 'Libro eliminado.',
        my_library: 'Mi biblioteca',
        library_help: 'Los libros que añades se guardan en tu cuenta, no en los archivos de tu dispositivo: los encuentras en todos los dispositivos donde inicias sesión, y la aplicación guarda una copia privada para leerlos sin conexión.',
        library_empty: 'Tu biblioteca está vacía',
        library_empty_help: 'Añade los libros de tus cursos para leerlos en cualquier lugar, incluso sin Internet.',
        books_of_my_courses: 'Libros de mis cursos',
        course_books: 'Libros del curso',
        add_to_library: 'Añadir a mi biblioteca',
        in_library: 'En mi biblioteca',
        remove_from_library: 'Quitar de mi biblioteca',
        confirm_remove_book: '¿Quitar este libro de tu biblioteca? También se quitará de tus dispositivos.',
        book_added: 'Libro añadido a tu biblioteca. Estará disponible sin conexión en tus dispositivos.',
        book_removed: 'Libro quitado de tu biblioteca.',
        read: 'Leer',
        continue_reading: 'Seguir leyendo',
        open: 'Abrir',
        hero_image: 'Foto de la página de inicio',
        hero_image_help: 'JPG, PNG o WebP, horizontal (p. ej. 1920×1080), máx. 5 MB. Se muestra detrás del título de la página de inicio.',
        hero_image_reset: 'Volver a la foto predeterminada',
        cert_awarded_to: 'Este certificado se otorga a',
        cert_hours: 'Duración del curso: :hours',
        cert_final_score: 'Evaluación final: :score %',
        js: {
            now_take_quiz: 'Vídeo terminado: haz el cuestionario para validar la lección.',
            knowledge_evolution: 'Evolución de los conocimientos',
            current_level: 'Nivel actual',
            knowledge_gain: 'Progreso',
            trend_progress: 'En progreso', trend_regression: 'En retroceso', trend_stable: 'Estable',
            trend_single: 'Primera evaluación', trend_none: 'Sin evaluar',
            media_error: 'No se puede abrir este documento.',
            media_not_offline: 'Este documento no está disponible sin conexión en este dispositivo.',
            zoom_in: 'Ampliar', zoom_out: 'Reducir', page_x_of_y: ':x / :y',
            close: 'Cerrar', loading: 'Cargando…', read: 'Leer',
            my_library: 'Mi biblioteca',
            library_offline_help: 'Libros de tu biblioteca guardados en este dispositivo.',
            library_empty_offline: 'Aún no hay libros guardados en este dispositivo. Abre «Mi biblioteca» cuando tengas conexión.',
            book_not_downloaded: 'Aún no está en este dispositivo',
            book_downloading: 'Guardando en este dispositivo…',
            final_online_only: 'evaluación final — solo en línea',
            with_quiz: 'cuestionario',
            questions_n: 'Preguntas: :count',
            check_your_knowledge: 'Comprueba lo que has aprendido',
            take_lesson_quiz: 'Hacer el cuestionario de la lección',
            pass_at: 'Aprobado: :score %',
            provisional_score: 'Puntuación provisional: :score % (:correct/:total)',
            provisional_passed: 'aprobado (se confirmará al volver la conexión)',
            provisional_failed: 'no aprobado: se necesita :score %',
        },
    },

    pt: {
        final_evaluation: 'Avaliação final',
        module_exercise: 'Exercício do módulo',
        module_exercise_of: 'Exercício — :module',
        lesson_quiz: 'Questionário da aula',
        lesson_quiz_of: 'Questionário — :lesson',
        assessment_locked: 'Conclua as etapas anteriores para desbloquear esta avaliação.',
        step_x_of_y: 'Etapa :x de :y',
        with_quiz: 'questionário',
        take_lesson_quiz: 'Fazer o questionário da aula',
        lesson_quiz_rule: 'Obtenha pelo menos :score % (7 em 10) no questionário para validar esta aula.',
        check_your_knowledge: 'Verifique o que aprendeu',
        module_exercise_intro: 'Este exercício abrange todo o módulo. Seja aprovado para validar o módulo e continuar.',
        final_intro: 'A avaliação final abrange todo o curso. Seja aprovado para concluir o curso e receber o seu certificado.',
        quiz_failed_need: 'Não aprovado: precisa de pelo menos :score %. Reveja a aula e tente novamente.',
        mode_not_available: 'Este modo só existe para a avaliação final.',
        diagnostic_title: 'Teste de nivelamento',
        diagnostic_banner: 'Meça o seu nível inicial com a avaliação final. Não conta para o seu progresso: permite ver tudo o que aprende.',
        diagnostic_start: 'Fazer o teste de nivelamento',
        diagnostic_intro: 'Este teste mede o que já sabe antes de estudar. Não conta para o seu progresso e as respostas não são mostradas.',
        diagnostic_done: 'Teste de nivelamento concluído: :score %. O seu nível inicial foi registado.',
        diagnostic_already_taken: 'O teste de nivelamento só pode ser feito uma vez, antes da avaliação final.',
        later: 'Mais tarde',
        retake_title: 'Reavaliação',
        retake_intro: 'Refaça a avaliação final para verificar se mantém os seus conhecimentos. O seu certificado não muda.',
        retake_start: 'Reavaliar os meus conhecimentos',
        retake_done: 'Reavaliação concluída: :score %.',
        retake_after_pass: 'As reavaliações ficam disponíveis após a aprovação na avaliação final.',
        retake_available_on: 'Próxima reavaliação possível em :date.',
        final_passed_retake_hint: 'Avaliação final aprovada. Volte regularmente para reavaliar os seus conhecimentos e acompanhar a sua evolução.',
        my_results: 'Os meus resultados',
        knowledge_evolution: 'Evolução dos conhecimentos',
        knowledge_evolution_help: 'Medida com a avaliação final: teste de nivelamento, fim do curso e depois reavaliações.',
        knowledge_chart: 'Evolução das pontuações da avaliação final',
        no_final_evaluation: 'Este curso ainda não tem avaliação final.',
        starting_level: 'Nível inicial',
        first_evaluation: 'Primeira avaliação',
        current_level: 'Nível atual',
        knowledge_gain: 'Progresso',
        trend: 'Tendência',
        trend_progress: 'Em progresso',
        trend_regression: 'Em regressão',
        trend_stable: 'Estável',
        trend_single: 'Uma avaliação',
        trend_none: 'Não avaliado',
        knowledge_level_beginner: 'Iniciante',
        knowledge_level_intermediate: 'Intermédio',
        knowledge_level_advanced: 'Avançado',
        knowledge_level_expert: 'Especialista',
        mode_diagnostic: 'Teste de nivelamento',
        mode_standard: 'Avaliação final',
        mode_retake: 'Reavaliação',
        pass_line: 'Nota de aprovação (:score %)',
        mastery_by_module: 'Domínio por módulo',
        mastery_by_module_help: 'Pontuação média por módulo (avaliação final ou, caso contrário, exercício do módulo).',
        while_studying: 'Durante a aprendizagem',
        lesson_quiz_average: 'Questionários das aulas (média)',
        module_exercise_average: 'Exercícios dos módulos (média)',
        evaluation_history: 'Histórico de avaliações',
        best_evaluation: 'Melhor avaliação',
        date: 'Data',
        type: 'Tipo',
        result: 'Nível',
        points: ':value pts',
        not_evaluated: 'Não avaliado',
        student_not_evaluated: 'Este estudante ainda não fez a avaliação final.',
        notif_regression_subject: 'Um estudante está em regressão',
        notif_regression_line: ':student obteve :score % na avaliação final de «:course», :delta pontos a menos do que antes.',
        notif_reassess_subject: 'É hora de reavaliar os seus conhecimentos',
        notif_reassess_line: 'Refaça a avaliação final de «:course» para verificar o que recorda.',
        tab_assessments: 'Avaliações',
        tab_books: 'Livros',
        assessment_editor: 'Avaliação',
        assessment_path: 'Percurso de avaliação do curso',
        path_lesson: 'Depois de cada aula: um questionário de pelo menos :min perguntas; o estudante deve obter :pass % (7/10) para validar a aula.',
        path_module: 'Depois de cada módulo: um exercício completo de pelo menos :min perguntas (aprovação com :pass %).',
        path_final: 'Depois do curso: uma avaliação final de pelo menos :min perguntas (aprovação com :pass %). Serve também como teste de nivelamento e reavaliação para medir o progresso ou a regressão de cada estudante.',
        assessment_plan: 'Plano de avaliação',
        assessment_plan_help: 'Todas as avaliações do curso e o respetivo número de perguntas.',
        scope_help_lesson: 'O questionário valida a aula: pelo menos :min perguntas, aprovação com :pass % (7/10).',
        scope_help_module: 'O exercício encerra o módulo: pelo menos :min perguntas, aprovação com :pass %.',
        scope_help_course: 'A avaliação final encerra o curso: pelo menos :min perguntas, aprovação com :pass %. Associe cada pergunta ao seu módulo para medir o domínio por módulo.',
        quiz_lesson_help: 'Esta aula é um questionário: pelo menos :min perguntas, aprovação com :pass %.',
        questions_of_min: ':count/:min perguntas',
        questions_missing: '{1} Falta :count pergunta.|[2,*] Faltam :count perguntas.',
        edit_questions: 'Editar as perguntas',
        create_quiz: 'Criar o questionário',
        pass_minimum: 'Mínimo :pass % (regra da plataforma).',
        final_settings_help: 'Dica: mantenha «mostrar as respostas corretas» desativado para que as reavaliações continuem úteis.',
        import_questions: 'Importar perguntas',
        import_help: 'Cole as suas perguntas: um bloco por pergunta, separados por uma linha vazia.',
        import_example: 'Exemplo',
        import_sample: "Qual é a capital dos Camarões?\n- Douala\n* Iaundé\n- Bertoua\n> Iaundé é a capital política.\n\nQuais são números pares?\n* 2\n- 3\n* 4",
        import_block_error: 'Bloco :number ignorado («:question»): precisa de pelo menos duas opções e uma resposta correta (linha que começa por *).',
        import_empty: 'Nenhuma pergunta encontrada.',
        questions_imported: '{1} :count pergunta importada.|[2,*] :count perguntas importadas.',
        question_module: 'Módulo avaliado',
        no_module: 'Todo o curso',
        question_module_help: 'Serve para medir o domínio por módulo.',
        explanation: 'Explicação (opcional)',
        explanation_placeholder: 'Mostrada ao estudante depois de responder.',
        final_evaluation_help: 'Encerra o curso e mede o progresso de cada estudante.',
        check_lesson_quizzes: 'Um questionário de pelo menos :min perguntas depois de cada aula',
        check_module_exercises: 'Um exercício de pelo menos :min perguntas depois de cada módulo',
        check_final_evaluation: 'Uma avaliação final de pelo menos :min perguntas',
        knowledge_tracking: 'Acompanhamento dos conhecimentos',
        knowledge_tracking_help: 'Nível de cada estudante medido com a avaliação final (nivelamento, fim do curso, reavaliações) e a sua evolução.',
        final_needed_for_tracking: 'Adicione uma avaliação final de pelo menos :min perguntas para medir os conhecimentos dos seus estudantes.',
        edit_final_evaluation: 'Editar a avaliação final',
        evaluated_students: 'Estudantes avaliados',
        average_level: 'Nível médio',
        average_gain: 'Progresso médio',
        in_progression: 'Em progresso',
        in_regression: 'Em regressão',
        students_knowledge: 'Conhecimentos dos seus estudantes',
        students_knowledge_help: 'Medidos com a avaliação final de cada curso: nível inicial, nível atual, progresso ou regressão.',
        students_in_regression: 'Estudantes em regressão',
        books_help: 'Livros em PDF e documentos de áudio ou vídeo. Os estudantes inscritos adicionam-nos à sua biblioteca e leem-nos na aplicação, mesmo offline.',
        book_author: 'Autor',
        book_formats: 'PDF, MP3, M4A, OGG, WAV, MP4, WebM — máx. :max',
        no_books: 'Este curso ainda não tem livros.',
        confirm_delete_book: 'Eliminar este livro? Vai desaparecer das bibliotecas dos estudantes.',
        book_uploaded: 'Livro adicionado.',
        book_updated: 'Livro atualizado.',
        book_deleted: 'Livro eliminado.',
        my_library: 'A minha biblioteca',
        library_help: 'Os livros que adiciona ficam guardados na sua conta, não nos ficheiros do seu dispositivo: encontra-os em todos os dispositivos onde inicia sessão, e a aplicação guarda uma cópia privada para os ler offline.',
        library_empty: 'A sua biblioteca está vazia',
        library_empty_help: 'Adicione os livros dos seus cursos para os ler em qualquer lugar, mesmo sem Internet.',
        books_of_my_courses: 'Livros dos meus cursos',
        course_books: 'Livros do curso',
        add_to_library: 'Adicionar à minha biblioteca',
        in_library: 'Na minha biblioteca',
        remove_from_library: 'Retirar da minha biblioteca',
        confirm_remove_book: 'Retirar este livro da sua biblioteca? Também será retirado dos seus dispositivos.',
        book_added: 'Livro adicionado à sua biblioteca. Ficará disponível offline nos seus dispositivos.',
        book_removed: 'Livro retirado da sua biblioteca.',
        read: 'Ler',
        continue_reading: 'Continuar a ler',
        open: 'Abrir',
        hero_image: 'Foto da página inicial',
        hero_image_help: 'JPG, PNG ou WebP, na horizontal (ex. 1920×1080), máx. 5 MB. Aparece atrás do título da página inicial.',
        hero_image_reset: 'Voltar à foto predefinida',
        cert_awarded_to: 'Este certificado é atribuído a',
        cert_hours: 'Duração do curso: :hours',
        cert_final_score: 'Avaliação final: :score %',
        js: {
            now_take_quiz: 'Vídeo terminado: faça o questionário para validar a aula.',
            knowledge_evolution: 'Evolução dos conhecimentos',
            current_level: 'Nível atual',
            knowledge_gain: 'Progresso',
            trend_progress: 'Em progresso', trend_regression: 'Em regressão', trend_stable: 'Estável',
            trend_single: 'Primeira avaliação', trend_none: 'Não avaliado',
            media_error: 'Não é possível abrir este documento.',
            media_not_offline: 'Este documento não está disponível offline neste dispositivo.',
            zoom_in: 'Ampliar', zoom_out: 'Reduzir', page_x_of_y: ':x / :y',
            close: 'Fechar', loading: 'A carregar…', read: 'Ler',
            my_library: 'A minha biblioteca',
            library_offline_help: 'Livros da sua biblioteca guardados neste dispositivo.',
            library_empty_offline: 'Ainda não há livros guardados neste dispositivo. Abra «A minha biblioteca» quando estiver online.',
            book_not_downloaded: 'Ainda não está neste dispositivo',
            book_downloading: 'A guardar neste dispositivo…',
            final_online_only: 'avaliação final — apenas online',
            with_quiz: 'questionário',
            questions_n: 'Perguntas: :count',
            check_your_knowledge: 'Verifique o que aprendeu',
            take_lesson_quiz: 'Fazer o questionário da aula',
            pass_at: 'Aprovação: :score %',
            provisional_score: 'Pontuação provisória: :score % (:correct/:total)',
            provisional_passed: 'aprovado (confirmado quando voltar a ligação)',
            provisional_failed: 'não aprovado: são necessários :score %',
        },
    },

    zh: {
        final_evaluation: '期末评估',
        module_exercise: '模块练习',
        module_exercise_of: '练习 — :module',
        lesson_quiz: '课时测验',
        lesson_quiz_of: '测验 — :lesson',
        assessment_locked: '完成前面的步骤后即可解锁此评估。',
        step_x_of_y: '第 :x 步，共 :y 步',
        with_quiz: '测验',
        take_lesson_quiz: '参加课时测验',
        lesson_quiz_rule: '测验得分至少 :score %（10 题答对 7 题）即可通过本课时。',
        check_your_knowledge: '检验你的学习成果',
        module_exercise_intro: '本练习涵盖整个模块。通过后即可完成该模块并继续学习。',
        final_intro: '期末评估涵盖整个课程。通过后即可完成课程并获得证书。',
        quiz_failed_need: '未通过：至少需要 :score %。请复习本课时后再试。',
        mode_not_available: '此模式仅适用于期末评估。',
        diagnostic_title: '入学水平测试',
        diagnostic_banner: '用期末评估测出你的起始水平。它不计入学习进度，但能让你看到自己学到了多少。',
        diagnostic_start: '参加水平测试',
        diagnostic_intro: '此测试衡量你学习前已掌握的知识。它不计入学习进度，也不会显示答案。',
        diagnostic_done: '水平测试完成：:score %。你的起始水平已保存。',
        diagnostic_already_taken: '水平测试只能在期末评估之前参加一次。',
        later: '稍后',
        retake_title: '再次评估',
        retake_intro: '重新参加期末评估，检查你是否仍然掌握所学知识。你的证书不会改变。',
        retake_start: '重新评估我的知识',
        retake_done: '再次评估完成：:score %。',
        retake_after_pass: '通过期末评估后才能进行再次评估。',
        retake_available_on: '下次可再次评估的日期：:date。',
        final_passed_retake_hint: '期末评估已通过。请定期回来再次评估，跟踪你的知识变化。',
        my_results: '我的成绩',
        knowledge_evolution: '知识变化',
        knowledge_evolution_help: '通过期末评估衡量：水平测试、课程结束，然后是再次评估。',
        knowledge_chart: '期末评估分数变化',
        no_final_evaluation: '本课程尚无期末评估。',
        starting_level: '起始水平',
        first_evaluation: '首次评估',
        current_level: '当前水平',
        knowledge_gain: '进步',
        trend: '趋势',
        trend_progress: '进步中',
        trend_regression: '退步中',
        trend_stable: '稳定',
        trend_single: '仅一次评估',
        trend_none: '未评估',
        knowledge_level_beginner: '入门',
        knowledge_level_intermediate: '中级',
        knowledge_level_advanced: '高级',
        knowledge_level_expert: '专家',
        mode_diagnostic: '水平测试',
        mode_standard: '期末评估',
        mode_retake: '再次评估',
        pass_line: '及格线（:score %）',
        mastery_by_module: '各模块掌握程度',
        mastery_by_module_help: '每个模块的平均分（期末评估，否则为模块练习）。',
        while_studying: '学习过程中',
        lesson_quiz_average: '课时测验（平均）',
        module_exercise_average: '模块练习（平均）',
        evaluation_history: '评估记录',
        best_evaluation: '最佳评估',
        date: '日期',
        type: '类型',
        result: '水平',
        points: ':value 分',
        not_evaluated: '未评估',
        student_not_evaluated: '该学员尚未参加期末评估。',
        notif_regression_subject: '有学员出现退步',
        notif_regression_line: ':student 在“:course”的期末评估中得分 :score %，比之前低 :delta 分。',
        notif_reassess_subject: '该重新评估你的知识了',
        notif_reassess_line: '重新参加“:course”的期末评估，检查你还记得多少。',
        tab_assessments: '评估',
        tab_books: '书籍',
        assessment_editor: '评估',
        assessment_path: '课程评估路径',
        path_lesson: '每个课时之后：至少 :min 道题的测验；学员须达到 :pass %（10 题答对 7 题）才能通过课时。',
        path_module: '每个模块之后：至少 :min 道题的综合练习（及格线 :pass %）。',
        path_final: '课程结束后：至少 :min 道题的期末评估（及格线 :pass %）。它也用作水平测试和再次评估，以衡量每位学员的进步或退步。',
        assessment_plan: '评估计划',
        assessment_plan_help: '课程的所有评估及其题目数量。',
        scope_help_lesson: '课时测验用于通过课时：至少 :min 道题，及格线 :pass %（10 题答对 7 题）。',
        scope_help_module: '模块练习用于结束模块：至少 :min 道题，及格线 :pass %。',
        scope_help_course: '期末评估用于结束课程：至少 :min 道题，及格线 :pass %。为每道题关联所属模块，以衡量各模块的掌握程度。',
        quiz_lesson_help: '本课时是测验：至少 :min 道题，及格线 :pass %。',
        questions_of_min: ':count/:min 道题',
        questions_missing: '还缺 :count 道题。',
        edit_questions: '编辑题目',
        create_quiz: '创建测验',
        pass_minimum: '最低 :pass %（平台规则）。',
        final_settings_help: '建议：关闭“显示正确答案”，以保证再次评估的有效性。',
        import_questions: '导入题目',
        import_help: '粘贴你的题目：每题一个段落，段落之间空一行。',
        import_example: '示例',
        import_sample: "喀麦隆的首都是哪里？\n- 杜阿拉\n* 雅温得\n- 贝尔图阿\n> 雅温得是政治首都。\n\n下列哪些是偶数？\n* 2\n- 3\n* 4",
        import_block_error: '已忽略第 :number 段（“:question”）：至少需要两个选项和一个正确答案（以 * 开头的行）。',
        import_empty: '未找到任何题目。',
        questions_imported: '已导入 :count 道题。',
        question_module: '考查的模块',
        no_module: '整个课程',
        question_module_help: '用于衡量各模块的掌握程度。',
        explanation: '解析（可选）',
        explanation_placeholder: '学员作答后显示。',
        final_evaluation_help: '结束课程并衡量每位学员的进步。',
        check_lesson_quizzes: '每个课时后都有至少 :min 道题的测验',
        check_module_exercises: '每个模块后都有至少 :min 道题的练习',
        check_final_evaluation: '至少 :min 道题的期末评估',
        knowledge_tracking: '知识跟踪',
        knowledge_tracking_help: '通过期末评估（水平测试、课程结束、再次评估）衡量每位学员的水平及其变化。',
        final_needed_for_tracking: '添加至少 :min 道题的期末评估，以衡量学员的知识水平。',
        edit_final_evaluation: '编辑期末评估',
        evaluated_students: '已评估学员',
        average_level: '平均水平',
        average_gain: '平均进步',
        in_progression: '进步中',
        in_regression: '退步中',
        students_knowledge: '学员的知识水平',
        students_knowledge_help: '通过各课程的期末评估衡量：起始水平、当前水平、进步或退步。',
        students_in_regression: '退步中的学员',
        books_help: 'PDF 书籍以及音频或视频资料。已报名的学员可将其加入书架，并在应用内阅读，离线也可以。',
        book_author: '作者',
        book_formats: 'PDF、MP3、M4A、OGG、WAV、MP4、WebM — 最大 :max',
        no_books: '本课程暂无书籍。',
        confirm_delete_book: '删除这本书吗？它将从学员的书架中消失。',
        book_uploaded: '书籍已添加。',
        book_updated: '书籍已更新。',
        book_deleted: '书籍已删除。',
        my_library: '我的书架',
        library_help: '你添加的书籍保存在你的账户中，而不是设备的文件里：在任何登录的设备上都能找到，应用还会保存一份私有副本，以便离线阅读。',
        library_empty: '你的书架是空的',
        library_empty_help: '添加课程书籍，随时随地阅读，没有网络也可以。',
        books_of_my_courses: '我的课程书籍',
        course_books: '课程书籍',
        add_to_library: '加入我的书架',
        in_library: '已在书架中',
        remove_from_library: '从书架移除',
        confirm_remove_book: '从书架移除这本书吗？它也会从你的设备中移除。',
        book_added: '书籍已加入你的书架，将在你的设备上离线可用。',
        book_removed: '书籍已从你的书架移除。',
        read: '阅读',
        continue_reading: '继续阅读',
        open: '打开',
        hero_image: '首页图片',
        hero_image_help: 'JPG、PNG 或 WebP，横向（例如 1920×1080），最大 5 MB。显示在首页标题的背后。',
        hero_image_reset: '恢复默认图片',
        cert_awarded_to: '兹授予此证书给',
        cert_hours: '课程时长：:hours',
        cert_final_score: '期末评估：:score %',
        js: {
            now_take_quiz: '视频已看完：请参加测验以通过本课时。',
            knowledge_evolution: '知识变化',
            current_level: '当前水平',
            knowledge_gain: '进步',
            trend_progress: '进步中', trend_regression: '退步中', trend_stable: '稳定',
            trend_single: '首次评估', trend_none: '未评估',
            media_error: '无法打开此文档。',
            media_not_offline: '此文档在本设备上无法离线使用。',
            zoom_in: '放大', zoom_out: '缩小', page_x_of_y: ':x / :y',
            close: '关闭', loading: '加载中…', read: '阅读',
            my_library: '我的书架',
            library_offline_help: '保存在本设备上的书架书籍。',
            library_empty_offline: '本设备上还没有保存书籍。联网时请打开“我的书架”。',
            book_not_downloaded: '尚未保存到本设备',
            book_downloading: '正在保存到本设备…',
            final_online_only: '期末评估 — 仅限在线',
            with_quiz: '测验',
            questions_n: '题目：:count',
            check_your_knowledge: '检验你的学习成果',
            take_lesson_quiz: '参加课时测验',
            pass_at: '及格线：:score %',
            provisional_score: '暂定得分：:score %（:correct/:total）',
            provisional_passed: '已通过（联网后确认）',
            provisional_failed: '未通过：需要 :score %',
        },
    },

    ar: {
        final_evaluation: 'التقييم النهائي',
        module_exercise: 'تمرين الوحدة',
        module_exercise_of: 'تمرين — :module',
        lesson_quiz: 'اختبار الدرس',
        lesson_quiz_of: 'اختبار — :lesson',
        assessment_locked: 'أكمل الخطوات السابقة لفتح هذا التقييم.',
        step_x_of_y: 'الخطوة :x من :y',
        with_quiz: 'اختبار',
        take_lesson_quiz: 'إجراء اختبار الدرس',
        lesson_quiz_rule: 'احصل على :score % على الأقل (7 من 10) في الاختبار لإتمام هذا الدرس.',
        check_your_knowledge: 'تحقّق من مكتسباتك',
        module_exercise_intro: 'يشمل هذا التمرين الوحدة كلها. انجح فيه لإتمام الوحدة والمتابعة.',
        final_intro: 'يشمل التقييم النهائي الدورة كلها. انجح فيه لإتمام الدورة والحصول على شهادتك.',
        quiz_failed_need: 'لم تنجح: يلزم :score % على الأقل. راجع الدرس ثم أعد المحاولة.',
        mode_not_available: 'هذا الوضع متاح للتقييم النهائي فقط.',
        diagnostic_title: 'اختبار تحديد المستوى',
        diagnostic_banner: 'قِس مستواك الأولي بالتقييم النهائي. لا يُحتسب في تقدّمك، لكنه يتيح لك رؤية كل ما تتعلّمه.',
        diagnostic_start: 'إجراء اختبار تحديد المستوى',
        diagnostic_intro: 'يقيس هذا الاختبار ما تعرفه قبل الدراسة. لا يُحتسب في تقدّمك ولا تُعرض الإجابات.',
        diagnostic_done: 'انتهى اختبار تحديد المستوى: :score %. تم حفظ مستواك الأولي.',
        diagnostic_already_taken: 'لا يمكن إجراء اختبار تحديد المستوى إلا مرة واحدة، قبل التقييم النهائي.',
        later: 'لاحقًا',
        retake_title: 'إعادة التقييم',
        retake_intro: 'أعد التقييم النهائي للتحقق من أنك ما زلت تحتفظ بمعارفك. لا تتغيّر شهادتك.',
        retake_start: 'إعادة تقييم معارفي',
        retake_done: 'انتهت إعادة التقييم: :score %.',
        retake_after_pass: 'تتاح إعادة التقييم بعد النجاح في التقييم النهائي.',
        retake_available_on: 'إعادة التقييم التالية ممكنة في :date.',
        final_passed_retake_hint: 'تم النجاح في التقييم النهائي. عُد بانتظام لإعادة تقييم معارفك ومتابعة تطوّرها.',
        my_results: 'نتائجي',
        knowledge_evolution: 'تطوّر المعارف',
        knowledge_evolution_help: 'يُقاس بالتقييم النهائي: اختبار تحديد المستوى، ثم نهاية الدورة، ثم إعادات التقييم.',
        knowledge_chart: 'تطوّر درجات التقييم النهائي',
        no_final_evaluation: 'لا يوجد تقييم نهائي لهذه الدورة بعد.',
        starting_level: 'المستوى الأولي',
        first_evaluation: 'التقييم الأول',
        current_level: 'المستوى الحالي',
        knowledge_gain: 'التقدّم',
        trend: 'الاتجاه',
        trend_progress: 'في تقدّم',
        trend_regression: 'في تراجع',
        trend_stable: 'مستقر',
        trend_single: 'تقييم واحد',
        trend_none: 'غير مُقيَّم',
        knowledge_level_beginner: 'مبتدئ',
        knowledge_level_intermediate: 'متوسط',
        knowledge_level_advanced: 'متقدّم',
        knowledge_level_expert: 'خبير',
        mode_diagnostic: 'اختبار تحديد المستوى',
        mode_standard: 'التقييم النهائي',
        mode_retake: 'إعادة التقييم',
        pass_line: 'درجة النجاح (:score %)',
        mastery_by_module: 'الإتقان حسب الوحدة',
        mastery_by_module_help: 'متوسط الدرجات لكل وحدة (التقييم النهائي، وإلا فتمرين الوحدة).',
        while_studying: 'أثناء التعلّم',
        lesson_quiz_average: 'اختبارات الدروس (المتوسط)',
        module_exercise_average: 'تمارين الوحدات (المتوسط)',
        evaluation_history: 'سجل التقييمات',
        best_evaluation: 'أفضل تقييم',
        date: 'التاريخ',
        type: 'النوع',
        result: 'المستوى',
        points: 'النقاط: :value',
        not_evaluated: 'غير مُقيَّم',
        student_not_evaluated: 'لم يُجرِ هذا الطالب التقييم النهائي بعد.',
        notif_regression_subject: 'طالب في تراجع',
        notif_regression_line: 'حصل :student على :score % في التقييم النهائي لدورة «:course»، أي أقل من السابق بفارق :delta.',
        notif_reassess_subject: 'حان وقت إعادة تقييم معارفك',
        notif_reassess_line: 'أعد التقييم النهائي لدورة «:course» للتحقق مما تتذكّره.',
        tab_assessments: 'التقييمات',
        tab_books: 'الكتب',
        assessment_editor: 'التقييم',
        assessment_path: 'مسار التقييم في الدورة',
        path_lesson: 'بعد كل درس: اختبار من :min أسئلة على الأقل؛ يجب أن يحصل الطالب على :pass % (7/10) لإتمام الدرس.',
        path_module: 'بعد كل وحدة: تمرين شامل من :min أسئلة على الأقل (النجاح عند :pass %).',
        path_final: 'بعد الدورة: تقييم نهائي من :min سؤالًا على الأقل (النجاح عند :pass %). ويُستخدم أيضًا لتحديد المستوى ولإعادة التقييم لقياس تقدّم كل طالب أو تراجعه.',
        assessment_plan: 'خطة التقييم',
        assessment_plan_help: 'جميع تقييمات الدورة وعدد أسئلة كل منها.',
        scope_help_lesson: 'اختبار الدرس يُتمّ الدرس: :min أسئلة على الأقل، والنجاح عند :pass % (7/10).',
        scope_help_module: 'تمرين الوحدة يختم الوحدة: :min أسئلة على الأقل، والنجاح عند :pass %.',
        scope_help_course: 'التقييم النهائي يختم الدورة: :min سؤالًا على الأقل، والنجاح عند :pass %. اربط كل سؤال بوحدته لقياس الإتقان حسب الوحدة.',
        quiz_lesson_help: 'هذا الدرس اختبار: :min أسئلة على الأقل، والنجاح عند :pass %.',
        questions_of_min: 'الأسئلة: :count/:min',
        questions_missing: 'عدد الأسئلة الناقصة: :count.',
        edit_questions: 'تعديل الأسئلة',
        create_quiz: 'إنشاء الاختبار',
        pass_minimum: 'الحد الأدنى :pass % (قاعدة المنصة).',
        final_settings_help: 'نصيحة: أبقِ خيار «إظهار الإجابات الصحيحة» معطّلًا لتبقى إعادات التقييم مفيدة.',
        import_questions: 'استيراد أسئلة',
        import_help: 'الصق أسئلتك: كتلة لكل سؤال، مع سطر فارغ بين الكتل.',
        import_example: 'مثال',
        import_sample: "ما عاصمة الكاميرون؟\n- دوالا\n* ياوندي\n- برتوا\n> ياوندي هي العاصمة السياسية.\n\nأيّ هذه الأعداد زوجية؟\n* 2\n- 3\n* 4",
        import_block_error: 'تم تجاهل الكتلة :number («:question»): يلزم خياران على الأقل وإجابة صحيحة واحدة (سطر يبدأ بـ *).',
        import_empty: 'لم يُعثر على أي سؤال.',
        questions_imported: 'عدد الأسئلة المستوردة: :count.',
        question_module: 'الوحدة المُقيَّمة',
        no_module: 'الدورة كلها',
        question_module_help: 'يُستخدم لقياس الإتقان حسب الوحدة.',
        explanation: 'شرح (اختياري)',
        explanation_placeholder: 'يُعرض على الطالب بعد الإجابة.',
        final_evaluation_help: 'يختم الدورة ويقيس تقدّم كل طالب.',
        check_lesson_quizzes: 'اختبار من :min أسئلة على الأقل بعد كل درس',
        check_module_exercises: 'تمرين من :min أسئلة على الأقل بعد كل وحدة',
        check_final_evaluation: 'تقييم نهائي من :min سؤالًا على الأقل',
        knowledge_tracking: 'متابعة المعارف',
        knowledge_tracking_help: 'مستوى كل طالب مقيسًا بالتقييم النهائي (تحديد المستوى، نهاية الدورة، إعادات التقييم) وتطوّره.',
        final_needed_for_tracking: 'أضف تقييمًا نهائيًا من :min سؤالًا على الأقل لقياس معارف طلابك.',
        edit_final_evaluation: 'تعديل التقييم النهائي',
        evaluated_students: 'الطلاب المُقيَّمون',
        average_level: 'متوسط المستوى',
        average_gain: 'متوسط التقدّم',
        in_progression: 'في تقدّم',
        in_regression: 'في تراجع',
        students_knowledge: 'معارف طلابك',
        students_knowledge_help: 'مقيسة بالتقييم النهائي لكل دورة: المستوى الأولي، المستوى الحالي، التقدّم أو التراجع.',
        students_in_regression: 'طلاب في تراجع',
        books_help: 'كتب PDF ومستندات صوتية أو مرئية. يضيفها الطلاب المسجّلون إلى مكتبتهم ويقرؤونها داخل التطبيق، حتى دون اتصال.',
        book_author: 'المؤلف',
        book_formats: 'PDF وMP3 وM4A وOGG وWAV وMP4 وWebM — الحد الأقصى :max',
        no_books: 'لا توجد كتب لهذه الدورة بعد.',
        confirm_delete_book: 'حذف هذا الكتاب؟ سيختفي من مكتبات الطلاب.',
        book_uploaded: 'تمت إضافة الكتاب.',
        book_updated: 'تم تحديث الكتاب.',
        book_deleted: 'تم حذف الكتاب.',
        my_library: 'مكتبتي',
        library_help: 'تُحفظ الكتب التي تضيفها في حسابك، لا في ملفات جهازك: تجدها على كل جهاز تسجّل الدخول منه، ويحتفظ التطبيق بنسخة خاصة لقراءتها دون اتصال.',
        library_empty: 'مكتبتك فارغة',
        library_empty_help: 'أضف كتب دوراتك لقراءتها في أي مكان، حتى دون إنترنت.',
        books_of_my_courses: 'كتب دوراتي',
        course_books: 'كتب الدورة',
        add_to_library: 'إضافة إلى مكتبتي',
        in_library: 'في مكتبتي',
        remove_from_library: 'إزالة من مكتبتي',
        confirm_remove_book: 'إزالة هذا الكتاب من مكتبتك؟ ستتم إزالته أيضًا من أجهزتك.',
        book_added: 'تمت إضافة الكتاب إلى مكتبتك. سيكون متاحًا دون اتصال على أجهزتك.',
        book_removed: 'تمت إزالة الكتاب من مكتبتك.',
        read: 'قراءة',
        continue_reading: 'متابعة القراءة',
        open: 'فتح',
        hero_image: 'صورة الصفحة الرئيسية',
        hero_image_help: 'JPG أو PNG أو WebP بالوضع الأفقي (مثل 1920×1080)، بحد أقصى 5 ميغابايت. تظهر خلف عنوان الصفحة الرئيسية.',
        hero_image_reset: 'العودة إلى الصورة الافتراضية',
        cert_awarded_to: 'تُمنح هذه الشهادة إلى',
        cert_hours: 'مدة الدورة: :hours',
        cert_final_score: 'التقييم النهائي: :score %',
        js: {
            now_take_quiz: 'انتهى الفيديو: أجرِ الاختبار لإتمام الدرس.',
            knowledge_evolution: 'تطوّر المعارف',
            current_level: 'المستوى الحالي',
            knowledge_gain: 'التقدّم',
            trend_progress: 'في تقدّم', trend_regression: 'في تراجع', trend_stable: 'مستقر',
            trend_single: 'التقييم الأول', trend_none: 'غير مُقيَّم',
            media_error: 'تعذّر فتح هذا المستند.',
            media_not_offline: 'هذا المستند غير متاح دون اتصال على هذا الجهاز.',
            zoom_in: 'تكبير', zoom_out: 'تصغير', page_x_of_y: ':x / :y',
            close: 'إغلاق', loading: 'جارٍ التحميل…', read: 'قراءة',
            my_library: 'مكتبتي',
            library_offline_help: 'كتب مكتبتك المحفوظة على هذا الجهاز.',
            library_empty_offline: 'لا توجد كتب محفوظة على هذا الجهاز بعد. افتح «مكتبتي» عند الاتصال.',
            book_not_downloaded: 'غير محفوظ على هذا الجهاز بعد',
            book_downloading: 'جارٍ الحفظ على هذا الجهاز…',
            final_online_only: 'التقييم النهائي — عبر الإنترنت فقط',
            with_quiz: 'اختبار',
            questions_n: 'الأسئلة: :count',
            check_your_knowledge: 'تحقّق من مكتسباتك',
            take_lesson_quiz: 'إجراء اختبار الدرس',
            pass_at: 'النجاح: :score %',
            provisional_score: 'درجة مؤقتة: :score % (:correct/:total)',
            provisional_passed: 'ناجح (يُؤكَّد عند عودة الاتصال)',
            provisional_failed: 'غير ناجح: يلزم :score %',
        },
    },
};

// Sign in with Google, confirmation codes, two-factor authentication and profile.
const auth = require('./learn-auth.cjs');
for (const locale of Object.keys(module.exports)) Object.assign(module.exports[locale], auth[locale]);

// Course content protection (keys also merged into the "js" block used by the scripts).
const protect = require('./learn-protect.cjs');
for (const locale of Object.keys(module.exports)) {
    const { js, ...rest } = protect[locale];
    Object.assign(module.exports[locale], rest);
    Object.assign(module.exports[locale].js, js);
}

// New course wizard and presentation video.
const course = require('./learn-course.cjs');
for (const locale of Object.keys(module.exports)) Object.assign(module.exports[locale], course[locale]);
