// Portuguese — auth, dashboard, courses, navigation, messages
module.exports = {
    auth: {
        failed: 'Estas credenciais não correspondem aos nossos registos.',
        password: 'A senha está incorreta.',
        throttle: 'Demasiadas tentativas. Tente novamente dentro de :seconds segundos.',
        login: 'Entrar', register: 'Criar conta', logout: 'Sair',
        email: 'E-mail', password_label: 'Senha', confirm_password: 'Confirmar senha',
        remember_me: 'Lembrar-me', forgot_password: 'Esqueceu a senha?', reset_password: 'Redefinir senha',
        send_reset_link: 'Enviar link de redefinição', name: 'Nome completo',
        already_registered: 'Já tem conta?', no_account: 'Não tem conta?',
        verify_email: 'Verificar e-mail',
        verify_notice: 'Obrigado por se registar! Antes de começar, pode confirmar o seu endereço de e-mail?',
        verify_sent: 'Foi enviado um novo link de verificação para o seu e-mail.',
        verify_resend: 'Reenviar e-mail de verificação', country: 'País',
        trial_notice: 'Comece hoje o seu teste gratuito de :days dias. Sem cartão de crédito.',
        register_as: 'Crie a sua conta gratuita', admin_login: 'Acesso de administrador',
        admin_only: 'Esta área é reservada aos administradores.',
        welcome_back: 'Bem-vindo de volta', sign_in_to_continue: 'Entre para continuar a aprender',
        join_acadexa: 'Junte-se à ACADEXA', create_account: 'Crie a sua conta gratuita', full_name: 'Nome completo',
        have_account: 'Já tem uma conta?', register_here: 'Entre aqui',
    },
    dashboard: {
        welcome: 'Bem-vindo de volta', total_courses: 'Cursos', instructors: 'Instrutores', my_courses: 'Meus cursos',
        certificates: 'Certificados', announcements: 'Avisos', quick_links: 'Atalhos', browse_courses: 'Explorar cursos',
        edit_profile: 'Editar perfil', enrolled_courses: 'Cursos inscritos', completed_courses: 'Cursos concluídos',
        in_progress: 'Em andamento', trial_status: 'Estado do teste', trial_active: 'Ativo — faltam :days dias',
        trial_expired: 'Expirado', continue: 'Continuar', view_all: 'Ver tudo',
        no_courses: 'Ainda não se inscreveu em nenhum curso.',
        no_certificates: 'Ainda não tem certificados. Conclua um curso para obter um!',
        no_announcements: 'Não há avisos de momento.', download_certificate: 'Baixar certificado', verify: 'Verificar',
        progress: 'Progresso', instructor_dashboard: 'Painel do instrutor', total_students: 'Estudantes',
        my_courses_count: 'Meus cursos', published_courses: 'Publicados', avg_rating: 'Avaliação média',
        recent_reviews: 'Avaliações recentes', pending_review: 'Aguardando revisão', create_course: 'Criar curso',
        view_courses: 'Ver meus cursos', earnings: 'Receitas', students_enrolled: ':count estudantes inscritos',
    },
    courses: {
        by: 'por', featured: 'Destaques', latest: 'Mais recentes', courses: 'Cursos', view_all: 'Ver tudo',
        view_course: 'Ver curso', newest: 'Mais recentes', catalog: 'Catálogo de cursos', filters: 'Filtros',
        courses_found: 'cursos encontrados', explore_courses: 'Explorar cursos', browse_by: 'Explorar por',
        category: 'Categoria', enroll: 'Inscrever-se', enrolled: 'Inscrito', already_enrolled: 'Já está inscrito.',
        free: 'Grátis', level: 'Nível', duration: 'Duração', language: 'Idioma', students: 'Estudantes',
        rating: 'Avaliação', reviews: 'Avaliações', curriculum: 'Programa', what_you_learn: 'O que vai aprender',
        requirements: 'Pré-requisitos', description: 'Descrição', about_instructor: 'Sobre o instrutor',
        related_courses: 'Cursos relacionados', write_review: 'Escrever uma avaliação', your_review: 'A sua avaliação',
        submit_review: 'Enviar avaliação', filter: 'Filtrar cursos', sort_by: 'Ordenar por', sort_newest: 'Mais recentes',
        sort_popular: 'Mais populares', sort_rating: 'Mais bem avaliados', all_categories: 'Todas as categorias',
        all_levels: 'Todos os níveis', free_only: 'Apenas gratuitos', price: 'Preço', module: 'Módulo', lesson: 'Aula',
        quiz: 'Questionário', assignment: 'Trabalho', video: 'Vídeo', text: 'Artigo', mark_complete: 'Marcar como concluída',
        completed: 'Concluído', progress: 'Progresso', next_lesson: 'Próxima aula', prev_lesson: 'Aula anterior',
        course_completed: 'Parabéns! Concluiu este curso.', get_certificate: 'Obter o seu certificado',
        hours: 'horas', free_preview: 'Pré-visualização gratuita', locked: 'Bloqueado — inscreva-se para aceder',
        no_video: 'Não há vídeo disponível para esta aula.', submit_quiz: 'Enviar questionário',
        quiz_passed: 'Questionário aprovado! Pontuação: :score %', quiz_failed: 'Questionário não aprovado. Pontuação: :score %. Tente novamente.',
        question: 'Pergunta', your_score: 'A sua pontuação anterior', attempt_again: 'Tentar novamente',
        comments: 'Perguntas e respostas', add_comment: 'Fazer uma pergunta', reply: 'Responder', post_comment: 'Publicar',
        download_attachment: 'Baixar anexo', add_to_wishlist: 'Adicionar aos favoritos', remove_from_wishlist: 'Remover dos favoritos',
        popular: 'Mais populares', top_rated: 'Mais bem avaliados', price_low: 'Preço: do mais baixo ao mais alto',
        continue_learning: 'Continuar a aprender', enroll_now: 'Inscrever-se agora', no_courses_found: 'Nenhum curso encontrado.',
        student_reviews: 'Avaliações dos estudantes', try_different_filters: 'Experimente ajustar os filtros ou os termos de pesquisa.',
    },
    navigation: {
        home: 'Início', courses: 'Cursos', categories: 'Categorias', my_courses: 'Meus cursos', dashboard: 'Painel',
        profile: 'Perfil', wishlist: 'Favoritos', certificates: 'Certificados', subscription: 'Assinatura',
        logout: 'Sair', login: 'Entrar', register: 'Criar conta', become_instructor: 'Torne-se instrutor',
        contact: 'Contacto', about: 'Sobre', privacy: 'Política de privacidade', terms: 'Termos de serviço',
        admin_panel: 'Administração', instructor_portal: 'Espaço do instrutor', search: 'Pesquisar',
        quick_links: 'Atalhos', support: 'Suporte', contact_us: 'Fale connosco', notifications: 'Notificações',
        no_notifications: 'Sem novas notificações', start_free: 'Começar grátis',
    },
    messages: {
        welcome: 'Bem-vindo à ACADEXA', learn_grow: 'Aprenda, cresça e alcance os seus objetivos',
        hero_subtitle: 'Junte-se a milhares de estudantes do Instituto Universitário ZTF. Aceda a cursos de excelência, obtenha certificados e avance na sua carreira.',
        get_started: 'Começar grátis', browse_courses: 'Explorar cursos', featured_courses: 'Cursos em destaque',
        latest_courses: 'Cursos recentes', view_all: 'Ver tudo', categories: 'Categorias', why_acadexa: 'Por que escolher a ACADEXA?',
        enroll_now: 'Inscrever-se agora', start_learning: 'Começar a aprender', continue_learning: 'Continuar a aprender',
        free: 'Grátis', all_levels: 'Todos os níveis', beginner: 'Iniciante', intermediate: 'Intermediário', advanced: 'Avançado',
        students: 'estudantes', courses: 'cursos', instructors: 'instrutores', certificates_issued: 'certificados emitidos',
        trial_active: 'Teste ativo', trial_expires: 'O teste termina em :date',
        trial_expired: 'O seu período de teste terminou. Assine para continuar a aprender.', upgrade: 'Assinar',
        become_instructor: 'Torne-se instrutor', teach_world: 'Ensine o mundo', no_courses: 'Nenhum curso encontrado.',
        contact_us: 'Fale connosco', send_message: 'Enviar mensagem', name: 'Nome', email: 'E-mail', phone: 'Telefone',
        subject: 'Assunto', message: 'Mensagem', message_sent: 'A sua mensagem foi enviada. Responderemos em breve.',
        search_placeholder: 'Pesquisar cursos, temas...', no_results: 'Nenhum resultado para ":query"',
        certificate_verified: 'Certificado verificado', certificate_not_found: 'Certificado não encontrado',
        verify_certificate: 'Verificar certificado', enter_code: 'Introduza o código do certificado',
        payment_coming_soon: 'Pagamentos e monetização — em breve', contact_support: 'Contactar o suporte',
        language_changed: 'Idioma alterado com sucesso.', profile_updated: 'Perfil atualizado com sucesso.',
        password_changed: 'Senha alterada com sucesso.',
        account_deactivated: 'A sua conta foi desativada. Contacte o suporte.',
        already_applied: 'Já se candidatou para ser instrutor.', already_enrolled: 'Já está inscrito neste curso.',
        application_submitted: 'A sua candidatura foi enviada. Responderemos em breve.',
        certificate_issued: 'Parabéns! Concluiu o curso e o seu certificado está pronto.',
        comment_posted: 'A sua pergunta foi publicada.', contact_sent: 'A sua mensagem foi enviada. Responderemos em breve.',
        course_deleted: 'Curso eliminado.', course_submitted: 'Curso enviado para revisão. Será notificado da decisão.',
        course_updated: 'Curso atualizado.', enrolled_success: 'Está inscrito. Boa aprendizagem!',
        quiz_failed: 'Ainda não aprovado. Reveja a aula e tente novamente.', quiz_passed: 'Muito bem, foi aprovado no questionário!',
        review_submitted: 'Obrigado pela sua avaliação.', wishlist_added: 'Adicionado aos seus favoritos.', wishlist_removed: 'Removido dos seus favoritos.',
        wrong_password: 'A senha atual está incorreta.',
    },
};
