// Portuguese — security and validation groups
module.exports = {
    security: {
        '2fa_title': 'Autenticação em dois fatores (2FA)',
        '2fa_intro': 'Proteja a sua conta de administrador: além da senha, será pedido um código de 6 dígitos gerado pelo seu telemóvel.',
        '2fa_step1': 'Instale uma aplicação de autenticação (Google Authenticator, Microsoft Authenticator, Authy…).',
        '2fa_step2': 'Leia o código QR (ou escreva a chave manualmente).',
        '2fa_step3': 'Introduza o código mostrado pela aplicação para confirmar.',
        '2fa_active_since': 'Autenticação em dois fatores ativa desde :date.',
        '2fa_disable_help': 'Para a desativar, confirme com a sua senha e um código da aplicação.',
        '2fa_challenge_help': 'Introduza o código de 6 dígitos da sua aplicação de autenticação.',
        manual_key: 'Chave para escrever manualmente', enable: 'Ativar', disable: 'Desativar', verify: 'Verificar', password: 'Senha',
        enabled: 'Autenticação em dois fatores ativada.', disabled: 'Autenticação em dois fatores desativada.',
        invalid_code: 'Código inválido ou expirado.', invalid_credentials: 'Senha ou código incorretos.',
        reset_2fa: 'Redefinir 2FA', confirm_reset_2fa: 'Redefinir a autenticação em dois fatores desta conta?',
        reset_done: 'Autenticação em dois fatores redefinida.',
        use_admin_login: 'Esta conta usa autenticação em dois fatores: entre pela área de administração.',
        my_security: 'Segurança da conta',
        banned: 'Esta conta foi suspensa. Contacte o suporte se achar que se trata de um erro.',
        banned_badge: 'Bloqueado', banned_since: 'Bloqueado desde :date', ban_reason: 'Motivo (opcional)',
        confirm_ban: 'Bloquear este utilizador? A sessão dele será terminada imediatamente.', unban: 'Desbloquear',
        user_banned: 'Utilizador bloqueado e desligado.', user_unbanned: 'Bloqueio levantado.',
        cannot_edit_self: 'Não pode realizar esta ação na sua própria conta.',
        no_permission: 'Não tem acesso a esta secção da administração.',
        role_permissions: 'Função e permissões', save_permissions: 'Guardar',
        permissions_help: 'Para um administrador: secções permitidas. Nenhuma marcada = acesso total.',
        permissions_saved: 'Função e permissões guardadas.',
        perm_users: 'Utilizadores', perm_courses: 'Cursos', perm_categories: 'Categorias', perm_applications: 'Candidaturas',
        perm_announcements: 'Avisos', perm_cms: 'Páginas', perm_reviews: 'Avaliações', perm_certificates: 'Certificados',
        perm_contacts: 'Mensagens de contacto', perm_translations: 'Traduções', perm_settings: 'Definições',
        perm_logs: 'Registo de atividade', perm_reports: 'Relatórios',
        platform: 'Plataforma', allow_registration: 'Registo aberto',
        require_email_verification: 'Exigir a verificação do endereço de e-mail',
        maintenance_mode: 'Modo de manutenção (apenas os administradores acedem ao site)',
        email_verification_help: 'Ative a verificação de e-mail apenas quando os e-mails já estiverem a ser enviados: chave API da Brevo guardada na caixa «E-mails» desta página.',
        registration_closed: 'O registo está temporariamente fechado.',
        reports: 'Relatórios', total_students: 'Estudantes', active_30d: 'Ativos (30 dias)', total_enrollments: 'Inscrições em cursos',
        completion_rate: 'Taxa de conclusão', last_12_months: 'Últimos 12 meses', month: 'Mês',
        registrations: 'Novos estudantes', enrollments: 'Inscrições', completions: 'Cursos concluídos', certificates: 'Certificados',
        top_courses: 'Cursos mais seguidos',
        export_users: 'Utilizadores (CSV)', export_enrollments: 'Inscrições (CSV)', export_certificates: 'Certificados (CSV)',
    },
    validation: {
        accepted: 'O campo :attribute deve ser aceite.',
        active_url: 'O campo :attribute deve ser um URL válido.',
        after: 'O campo :attribute deve ser uma data posterior a :date.',
        after_or_equal: 'O campo :attribute deve ser uma data igual ou posterior a :date.',
        alpha: 'O campo :attribute só pode conter letras.',
        alpha_dash: 'O campo :attribute só pode conter letras, números, hífenes e sublinhados.',
        alpha_num: 'O campo :attribute só pode conter letras e números.',
        array: 'O campo :attribute deve ser uma lista.',
        before: 'O campo :attribute deve ser uma data anterior a :date.',
        before_or_equal: 'O campo :attribute deve ser uma data igual ou anterior a :date.',
        between: {
            array: 'O campo :attribute deve ter entre :min e :max itens.',
            file: 'O ficheiro :attribute deve ter entre :min e :max kilobytes.',
            numeric: 'O valor de :attribute deve estar entre :min e :max.',
            string: 'O texto :attribute deve ter entre :min e :max caracteres.',
        },
        boolean: 'O campo :attribute deve ser verdadeiro ou falso.',
        confirmed: 'A confirmação de :attribute não corresponde.',
        current_password: 'A senha está incorreta.',
        date: 'O campo :attribute deve ser uma data válida.',
        date_format: 'O campo :attribute deve ter o formato :format.',
        different: 'Os campos :attribute e :other devem ser diferentes.',
        digits: 'O campo :attribute deve ter :digits dígitos.',
        digits_between: 'O campo :attribute deve ter entre :min e :max dígitos.',
        email: 'O campo :attribute deve ser um e-mail válido.',
        ends_with: 'O campo :attribute deve terminar com um destes valores: :values.',
        enum: 'O valor selecionado para :attribute é inválido.',
        exists: 'O valor selecionado para :attribute é inválido.',
        extensions: 'O ficheiro :attribute deve ter uma destas extensões: :values.',
        file: 'O campo :attribute deve ser um ficheiro.',
        filled: 'O campo :attribute deve ter um valor.',
        gt: {
            array: 'O campo :attribute deve ter mais de :value itens.',
            file: 'O ficheiro :attribute deve ter mais de :value kilobytes.',
            numeric: 'O valor de :attribute deve ser maior que :value.',
            string: 'O texto :attribute deve ter mais de :value caracteres.',
        },
        gte: {
            array: 'O campo :attribute deve ter :value itens ou mais.',
            file: 'O ficheiro :attribute deve ter pelo menos :value kilobytes.',
            numeric: 'O valor de :attribute deve ser maior ou igual a :value.',
            string: 'O texto :attribute deve ter pelo menos :value caracteres.',
        },
        image: 'O campo :attribute deve ser uma imagem.',
        in: 'O valor selecionado para :attribute é inválido.',
        integer: 'O campo :attribute deve ser um número inteiro.',
        ip: 'O campo :attribute deve ser um endereço IP válido.',
        json: 'O campo :attribute deve ser um texto JSON válido.',
        lowercase: 'O campo :attribute deve estar em minúsculas.',
        lt: {
            array: 'O campo :attribute deve ter menos de :value itens.',
            file: 'O ficheiro :attribute deve ter menos de :value kilobytes.',
            numeric: 'O valor de :attribute deve ser menor que :value.',
            string: 'O texto :attribute deve ter menos de :value caracteres.',
        },
        lte: {
            array: 'O campo :attribute não deve ter mais de :value itens.',
            file: 'O ficheiro :attribute deve ter no máximo :value kilobytes.',
            numeric: 'O valor de :attribute deve ser menor ou igual a :value.',
            string: 'O texto :attribute deve ter no máximo :value caracteres.',
        },
        max: {
            array: 'O campo :attribute não deve ter mais de :max itens.',
            file: 'O ficheiro :attribute não deve ultrapassar :max kilobytes.',
            numeric: 'O valor de :attribute não deve ser maior que :max.',
            string: 'O texto :attribute não deve ultrapassar :max caracteres.',
        },
        mimes: 'O ficheiro :attribute deve ser do tipo: :values.',
        mimetypes: 'O ficheiro :attribute deve ser do tipo: :values.',
        min: {
            array: 'O campo :attribute deve ter pelo menos :min itens.',
            file: 'O ficheiro :attribute deve ter pelo menos :min kilobytes.',
            numeric: 'O valor de :attribute deve ser pelo menos :min.',
            string: 'O texto :attribute deve ter pelo menos :min caracteres.',
        },
        not_in: 'O valor selecionado para :attribute é inválido.',
        numeric: 'O campo :attribute deve ser um número.',
        password: {
            letters: 'O campo :attribute deve conter pelo menos uma letra.',
            mixed: 'O campo :attribute deve conter pelo menos uma maiúscula e uma minúscula.',
            numbers: 'O campo :attribute deve conter pelo menos um número.',
            symbols: 'O campo :attribute deve conter pelo menos um símbolo.',
            uncompromised: 'Esta :attribute apareceu numa fuga de dados. Escolha outra.',
        },
        present: 'O campo :attribute deve estar presente.',
        prohibited: 'O campo :attribute não é permitido.',
        regex: 'O formato do campo :attribute é inválido.',
        required: 'O campo :attribute é obrigatório.',
        required_if: 'O campo :attribute é obrigatório quando :other é :value.',
        required_with: 'O campo :attribute é obrigatório quando :values está presente.',
        required_without: 'O campo :attribute é obrigatório quando :values não está presente.',
        same: 'Os campos :attribute e :other devem coincidir.',
        size: {
            array: 'O campo :attribute deve conter :size itens.',
            file: 'O ficheiro :attribute deve ter :size kilobytes.',
            numeric: 'O valor de :attribute deve ser :size.',
            string: 'O texto :attribute deve ter :size caracteres.',
        },
        starts_with: 'O campo :attribute deve começar com um destes valores: :values.',
        string: 'O campo :attribute deve ser um texto.',
        timezone: 'O campo :attribute deve ser um fuso horário válido.',
        unique: 'O valor de :attribute já está a ser utilizado.',
        uploaded: 'Não foi possível enviar o ficheiro :attribute.',
        uppercase: 'O campo :attribute deve estar em maiúsculas.',
        url: 'O campo :attribute deve ser um URL válido.',
        uuid: 'O campo :attribute deve ser um UUID válido.',
        attributes: {
            name: 'nome', email: 'e-mail', password: 'senha', password_confirmation: 'confirmação da senha',
            current_password: 'senha atual', country: 'país', bio: 'biografia', title: 'título',
            description: 'descrição', content: 'conteúdo', body: 'mensagem', subject: 'assunto', message: 'mensagem',
            phone: 'telefone', category_id: 'categoria', level: 'nível', language: 'idioma', price: 'preço',
            duration_hours: 'horas', duration_minutes: 'duração', thumbnail: 'imagem de capa', file: 'ficheiro',
            rating: 'avaliação', comment: 'comentário', score: 'nota', feedback: 'comentário', code: 'código',
            slug: 'endereço', audience: 'público', expertise: 'área de especialização', credentials: 'qualificações',
            reason: 'motivo', days: 'número de dias', question: 'pergunta', options: 'opções', correct: 'resposta certa',
            youtube_url: 'link do YouTube', vimeo_url: 'link do Vimeo', external_url: 'link do vídeo', hero_image: 'imagem',
        },
    },
};
