// Portuguese — lms group
module.exports = {
    actions: 'Ações', add: 'Adicionar', all: 'Todos', back: 'Voltar', cancel: 'Cancelar', close: 'Fechar',
    delete: 'Eliminar', details: 'Detalhes', download: 'Baixar', edit: 'Editar', filter: 'Filtrar',
    loading: 'A carregar…', more: 'Mais', none: 'Nenhum', post: 'Publicar', previous: 'Anterior', next: 'Seguinte',
    save: 'Guardar', send: 'Enviar', see_all: 'Ver tudo', view: 'Ver', unlimited: 'Ilimitado',
    unauthorized: 'Ação não autorizada.', order_saved: 'Nova ordem guardada.', confirm_delete: 'Confirmar a eliminação?',
    name: 'Nome', title: 'Título', description: 'Descrição', category: 'Categoria', level: 'Nível',
    price: 'Preço', price_help: 'O pagamento online chegará em breve. 0 = grátis.', hours: 'horas',
    status: 'Estado', message: 'Mensagem', subject: 'Assunto', file: 'Ficheiro', course: 'Curso',
    student: 'Estudante', students: 'Estudantes', instructor: 'Instrutor', lesson: 'Aula', lessons: 'aulas',
    module: 'Módulo', modules: 'Módulos', progress: 'Progresso', rating: 'Avaliação', stats: 'Estatísticas',
    certificate: 'Certificado', preview: 'Pré-visualização', tips: 'Dicas', my_courses: 'Meus cursos',
    lessons_count: '{0} Sem aulas|{1} :count aula|[2,*] :count aulas',
    modules_count: '{0} Sem módulos|{1} :count módulo|[2,*] :count módulos',
    questions_count: '{0} Sem perguntas|{1} :count pergunta|[2,*] :count perguntas',
    status_draft: 'Rascunho', status_pending: 'Em revisão', status_published: 'Publicado', status_rejected: 'Recusado', status_unpublished: 'Despublicado',
    type_video: 'Vídeo', type_text: 'Texto / artigo', type_quiz: 'Questionário', type_assignment: 'Trabalho',
    source_upload: 'Ficheiro de vídeo', source_youtube: 'YouTube', source_vimeo: 'Vimeo', source_url: 'Link direto',
    new_course: 'Novo curso',
    new_course_help: 'Comece pelo essencial. Depois construirá o programa: módulos (com as suas horas) e depois aulas.',
    step_info: 'Informações', step_modules: 'Módulos e horas', step_lessons: 'Aulas e conteúdo', step_submit: 'Envio',
    course_language: 'Idioma principal do curso', course_language_help: 'Poderá adicionar uma tradução mais tarde.',
    course_hours: 'Carga horária do curso', course_hours_help: 'Número total de horas de formação (ex.: 40 h).',
    course_title_placeholder: 'Ex.: Introdução à contabilidade geral',
    thumbnail: 'Imagem de capa', thumbnail_help: 'JPG, PNG ou WebP, 1280×720 recomendado, 4 MB máx.',
    create_and_continue: 'Criar e construir o programa', course_created_next_step: 'Curso criado. Agora adicione os módulos e as suas horas.',
    edit_course: 'Editar curso', tab_info: 'Informações', tab_curriculum: 'Programa',
    view_public_page: 'Página pública', admin_feedback: 'Comentário da administração',
    course_locked_pending: 'Este curso está em revisão: não pode ser editado até a administração decidir.',
    sequential: 'Progressão sequencial', sequential_help: 'cada aula é desbloqueada quando a anterior é concluída.',
    optional_translation: 'Tradução opcional: deixe em branco se o curso só for oferecido no idioma principal.',
    what_you_learn: 'O que os estudantes vão aprender', requirements: 'Pré-requisitos', one_per_line: 'Um item por linha',
    course_delete_forbidden: 'Não é possível eliminar um curso publicado ou com estudantes inscritos.',
    delete_course: 'Eliminar este curso', confirm_delete_course: 'Eliminar definitivamente este curso, os seus módulos, aulas e vídeos?',
    no_courses_yet: 'Ainda não criou nenhum curso.', students_and_stats: 'Estudantes e estatísticas',
    drag_help: 'Arraste e largue módulos e aulas para os reordenar (inclusive entre módulos).',
    drag: 'Mover', add_module: 'Adicionar um módulo', edit_module: 'Editar módulo', add_first_module: 'Adicionar o primeiro módulo',
    no_modules_title: 'Ainda não há módulos', no_modules_help: 'Um curso divide-se em módulos (com o seu número de horas), que por sua vez se dividem em aulas.',
    module_hours: 'Horas do módulo', module_title: 'Título do módulo', module_description: 'Descrição / objetivos do módulo',
    module_description_placeholder: 'Objetivos de aprendizagem, competências…',
    module_created: 'Módulo adicionado.', module_updated: 'Módulo atualizado.', module_deleted: 'Módulo eliminado.',
    confirm_delete_module: 'Eliminar este módulo e todas as suas aulas (incluindo vídeos)?',
    content_minutes: ':minutes min de conteúdo', content_duration: 'Duração dos conteúdos (vídeos, leituras): :duration',
    hours_breakdown: 'Distribuição das horas', modules_total: 'Total dos módulos',
    hours_over: 'A soma das horas dos módulos ultrapassa a carga horária do curso.',
    hours_remaining: 'Faltam :hours para distribuir pelos módulos.', hours_match: 'As horas dos módulos correspondem à carga do curso.',
    before_submit: 'Antes de enviar',
    check_info: 'Título e descrição no idioma principal', check_hours: 'Horas do curso e de cada módulo preenchidas',
    check_modules: 'Pelo menos um módulo, e cada módulo tem aulas', check_videos: 'Cada aula de vídeo tem um vídeo',
    check_quizzes: 'Cada questionário tem pelo menos uma pergunta', check_thumbnail: 'Imagem de capa',
    submit_review: 'Enviar para revisão', submit_incomplete: 'O curso está incompleto: verifique a lista «Antes de enviar».',
    pending_review_help: 'O seu curso está em revisão. Será notificado da decisão por e-mail.',
    add_lesson: 'Adicionar uma aula', add_lesson_help: 'Adicionará o conteúdo (vídeo, texto, questionário…) no passo seguinte.',
    create_and_edit: 'Criar e editar', edit_lesson: 'Editar aula', lesson_title: 'Título da aula', lesson_type: 'Tipo de aula',
    lesson_content: 'Conteúdo da aula', lesson_content_placeholder: 'Texto da aula, notas, links… (opcional para um vídeo)',
    lesson_created: 'Aula criada. Agora adicione o seu conteúdo.', lesson_saved: 'Aula guardada.', lesson_deleted: 'Aula eliminada.',
    lesson_incomplete: 'por completar', save_lesson: 'Guardar aula', back_to_curriculum: 'Programa',
    confirm_delete_lesson: 'Eliminar esta aula?', delete_lesson: 'Eliminar aula',
    duration_minutes: 'Duração', free_preview: 'Pré-visualização gratuita', free_preview_help: 'visível sem inscrição na página do curso',
    downloadable: 'Disponível offline', downloadable_help: 'os estudantes podem baixar esta aula na aplicação',
    video: 'Vídeo', upload_video: 'Enviar um vídeo', drop_video: 'Arraste o vídeo para aqui ou clique para escolher um ficheiro',
    video_formats: 'Formatos: :formats — até :max', upload_resumable_help: 'Se a ligação cair, escolha o mesmo ficheiro de novo: o envio continua de onde parou.',
    replace_video_help: 'Para substituir o vídeo, basta enviar um novo ficheiro.',
    delete_video: 'Eliminar vídeo', confirm_delete_video: 'Eliminar definitivamente este vídeo?',
    video_uploaded: 'Vídeo enviado com sucesso.', video_deleted: 'Vídeo eliminado.',
    upload_too_large: 'Ficheiro demasiado grande (máximo :max MB).', upload_bad_extension: 'Formato não aceite. Use MP4, WebM ou MOV.',
    upload_not_video: 'O ficheiro enviado não é um vídeo válido.', upload_missing_chunk: 'Falta uma parte do ficheiro (n.º :index). Envie-o novamente.',
    youtube_url: 'Link do vídeo do YouTube', youtube_invalid: 'Link do YouTube inválido.',
    youtube_help: 'O vídeo é reproduzido diretamente na ACADEXA, sem sair da plataforma. Dica: no YouTube, escolha a visibilidade «Não listado».',
    vimeo_url: 'Link do Vimeo', vimeo_invalid: 'Link do Vimeo inválido.',
    external_url: 'Link direto para um ficheiro de vídeo', external_url_help: 'URL de um ficheiro .mp4 alojado noutro local.',
    assignment_instructions: 'Instruções do trabalho', grading: 'Avaliação', max_score: 'Nota máxima', pass_score: 'Nota mínima para aprovação',
    assignment_completion_help: 'A aula fica concluída quando atribui uma nota igual ou superior à nota mínima.',
    tip_video: 'Envie os vídeos em MP4 (H.264): funciona em todos os dispositivos e fica disponível offline.',
    tip_youtube: 'Os vídeos do YouTube são reproduzidos na plataforma, mas não podem ser baixados para uso offline.',
    tip_offline: 'Adicione PDF como recursos: os estudantes podem lê-los sem ligação.',
    tip_completion: 'Um vídeo fica concluído quando o estudante viu realmente pelo menos 90 %.',
    resources: 'Recursos', resources_help: 'Apontamentos, exercícios, diapositivos… que os estudantes podem baixar (e usar offline).',
    resource_title: 'Título', resource_title_placeholder: 'Ex.: Apontamentos do curso (PDF)',
    resource_added: 'Recurso adicionado.', resource_deleted: 'Recurso eliminado.', confirm_delete_resource: 'Eliminar este recurso?',
    quiz: 'Questionário', passing_score: 'Nota mínima', max_attempts: 'Tentativas máximas', time_limit: 'Tempo limite',
    shuffle_questions: 'Baralhar as perguntas', show_correct_answers: 'Mostrar as respostas certas após a correção',
    save_settings: 'Guardar definições', quiz_settings_saved: 'Definições do questionário guardadas.',
    timed_quiz_offline_note: 'Um questionário com tempo só pode ser feito online.',
    add_question: 'Adicionar uma pergunta', question: 'Pergunta', answer_type: 'Tipo de resposta',
    single_answer: 'Uma única resposta certa', multiple_answers: 'Várias respostas certas', options: 'Opções',
    tick_correct: 'assinale a(s) resposta(s) certa(s)', add_option: 'Adicionar uma opção',
    question_added: 'Pergunta adicionada.', question_updated: 'Pergunta atualizada.', question_deleted: 'Pergunta eliminada.',
    confirm_delete_question: 'Eliminar esta pergunta?', no_questions: 'Não há perguntas. Adicione pelo menos uma.',
    save_to_create_quiz: 'Guarde a aula para criar o questionário.',
    quiz_need_correct: 'Assinale pelo menos uma resposta certa.', quiz_need_two_options: 'Uma pergunta precisa de pelo menos duas opções.',
    quiz_single_one_correct: 'Uma pergunta de resposta única só pode ter uma resposta certa.',
    lesson_x_of_y: 'Aula :x de :y', course_content: 'Conteúdo do curso', offline_mode: 'Modo offline',
    offline_mode_help: 'Baixe o curso para o seguir sem ligação. O progresso sincroniza assim que voltar a estar online.',
    contact_instructor: 'Escrever ao instrutor', course_page: 'Página do curso', course_empty: 'Este curso ainda não tem aulas.',
    video_unavailable: 'O vídeo desta aula ainda não está disponível.', completed: 'Concluído', mark_complete: 'Marcar como concluída',
    watched_percent: 'Visto: :percent %', auto_complete_hint: 'concluída automaticamente no fim do vídeo',
    watch_more: 'Veja pelo menos :percent % do vídeo para concluir a aula.',
    quiz_completes_lesson: 'Seja aprovado no questionário para concluir esta aula.', assignment_completes_lesson: 'Concluída quando o seu trabalho for avaliado como aprovado.',
    complete_via_assessment: 'Esta aula conclui-se passando na avaliação.', lesson_completed: 'Aula concluída!',
    lesson_locked: 'Conclua as aulas anteriores para desbloquear esta.',
    tab_lesson: 'Aula', qa: 'Perguntas e respostas', ask_question: 'Fazer uma pergunta ao instrutor',
    ask_question_placeholder: 'A sua pergunta sobre esta aula…', no_questions_yet: 'Ainda não há perguntas. Seja o primeiro!',
    lesson_navigation: 'Navegação entre aulas', get_certificate: 'Obter o meu certificado', back_to_course: 'Voltar ao curso',
    quiz_not_ready: 'Este questionário ainda não está pronto.',
    pass_at: 'Aprovação com :score %', attempts_unlimited: 'Tentativas ilimitadas',
    attempts_left: '{0} Sem tentativas restantes|{1} Resta :count tentativa|[2,*] Restam :count tentativas',
    quiz_passed_best: 'Questionário aprovado — melhor pontuação: :score %', quiz_last_score: 'Última pontuação: :score % (aprovação com :pass %)',
    quiz_no_attempts_left: 'Já usou todas as tentativas deste questionário.',
    quiz_not_started: 'O cronómetro não foi iniciado. Recarregue a página.',
    quiz_timed_out: 'O tempo acabou: esta tentativa não foi contada como aprovada.',
    timed_quiz_intro: 'Este questionário tem tempo: terá :minutes minutos a partir do momento em que clicar em «Começar».',
    start_quiz: 'Começar', several_answers: 'várias respostas', submit_answers: 'Enviar as minhas respostas',
    your_work: 'O seu trabalho', your_grade: 'A sua nota', assignment_passed: 'aprovado', assignment_failed: 'a melhorar',
    assignment_waiting: 'Entregue em :date — a aguardar correção.', view_my_submission: 'Ver a minha entrega',
    resubmit: 'Entregar uma nova versão', your_answer: 'A sua resposta', attach_file: 'Anexar um ficheiro',
    submit_assignment: 'Entregar o trabalho', assignment_submitted: 'Trabalho entregue. O seu instrutor foi notificado.',
    assignment_already_passed: 'Este trabalho já foi aprovado.', assignment_empty: 'Escreva uma resposta ou anexe um ficheiro.',
    pass_mark_is: 'Aprovação a partir de :score',
    assignments: 'Trabalhos', to_grade: 'Por corrigir', graded: 'Corrigidos', all_courses: 'Todos os cursos',
    submitted_on: 'Entregue em', grade: 'Avaliar', grade_submission: 'Correção do trabalho', no_submissions: 'Não há trabalhos aqui.',
    score: 'Nota', feedback: 'Comentário', feedback_placeholder: 'Pontos fortes, aspetos a melhorar…',
    save_grade: 'Guardar a nota', grade_notify_help: 'O estudante é notificado e a aula fica concluída se a nota atingir o mínimo.',
    graded_by_on: 'Avaliado por :name em :date', submission_graded: 'Nota guardada. O estudante foi notificado.',
    enrolled: 'Inscritos', completion_rate: 'Taxa de conclusão', avg_progress: 'Progresso médio', avg_quiz: 'Média nos questionários',
    search_student: 'Nome ou e-mail', not_started: 'Não iniciado', in_progress: 'Em andamento',
    export_csv: 'Exportar (CSV)', last_lesson: 'Última aula', enrolled_on: 'Inscrito em', completed_on: 'Concluído em',
    no_students: 'Não há estudantes.', completion_by_lesson: 'Conclusão por aula',
    completion_by_lesson_help: 'Percentagem de inscritos que concluiu cada aula: identifique onde os estudantes desistem.',
    student_progress: 'Progresso do estudante', best_score: 'Melhor pontuação', send_message: 'Enviar uma mensagem',
    announcements: 'Avisos', new_announcement: 'Novo aviso',
    announcement_help: 'Enviado a todos os inscritos do curso (notificação + e-mail).', publish_announcement: 'Publicar o aviso',
    announcement_sent: '{0} Aviso publicado (ainda sem inscritos).|{1} Aviso enviado a :count estudante.|[2,*] Aviso enviado a :count estudantes.',
    announcement_deleted: 'Aviso eliminado.', no_announcements: 'Não há avisos.',
    unanswered: 'Sem resposta', your_reply: 'A sua resposta…', reply: 'Responder', reply_posted: 'Resposta publicada.',
    no_questions_to_answer: 'Não há perguntas pendentes. Muito bem!',
    todo_submissions: '{1} :count trabalho por corrigir|[2,*] :count trabalhos por corrigir', todo_submissions_help: 'Os estudantes aguardam a nota.',
    todo_questions: '{1} :count pergunta sem resposta|[2,*] :count perguntas sem resposta', todo_questions_help: 'Responda na página de perguntas.',
    messages: 'Mensagens', new_message: 'Nova mensagem', new_message_help: 'Escreva ao instrutor de um dos seus cursos.',
    no_messages: 'Não há conversas.', message_sent: 'Mensagem enviada.',
    mark_all_read: 'Marcar tudo como lido', notifications_all_read: 'Todas as notificações foram lidas.',
    email_notifications: 'Receber também as notificações por e-mail', preferences_saved: 'Preferências guardadas.',
    mail_greeting: 'Olá, :name,', mail_salutation: 'A equipa ACADEXA — Instituto Universitário ZTF', notif_open: 'Abrir',
    notif_feedback: 'Comentário: :feedback',
    notif_certificate_subject: 'O seu certificado está pronto', notif_certificate_line: 'Parabéns! Concluiu «:course».',
    notif_certificate_code: 'Código de verificação: :code',
    notif_course_approved_subject: 'O seu curso foi publicado', notif_course_approved_line: 'O seu curso «:course» foi aprovado e já está online.',
    notif_course_rejected_subject: 'O seu curso precisa de alterações', notif_course_rejected_line: 'O seu curso «:course» não foi aprovado. Leia os comentários e envie-o novamente.',
    notif_course_submitted_subject: 'Curso para revisão', notif_course_submitted_line: ':instructor enviou «:course» para revisão.',
    notif_application_approved_subject: 'Candidatura aceite', notif_application_approved_line: 'Agora é instrutor na ACADEXA. Crie o seu primeiro curso!',
    notif_application_rejected_subject: 'Candidatura de instrutor', notif_application_rejected_line: 'A sua candidatura não foi aceite de momento.',
    notif_assignment_submitted_subject: 'Novo trabalho por corrigir', notif_assignment_submitted_line: ':student entregou o trabalho «:lesson».',
    notif_assignment_graded_subject: 'O seu trabalho foi corrigido', notif_assignment_graded_line: 'Trabalho «:lesson»: :score / :max.',
    notif_question_subject: 'Nova pergunta de um estudante', notif_question_line: ':name fez uma pergunta em «:lesson».',
    notif_reply_subject: 'Resposta à sua pergunta', notif_reply_line: ':name respondeu à sua pergunta em «:lesson».',
    notif_announcement_subject: 'Aviso — :course',
    notif_message_subject: 'Nova mensagem de :name', notif_message_line: ':name escreveu-lhe: «:subject».',
    notif_trial_subject: 'O seu teste termina em breve',
    notif_trial_line: '{1} Resta-lhe :days dia de acesso gratuito.|[2,*] Restam-lhe :days dias de acesso gratuito.',
    notif_welcome_subject: 'Bem-vindo à :site!', notif_browse_courses: 'Explorar os cursos',
    notif_welcome_line: '{1} A sua conta está pronta: tem :days dia de acesso gratuito a todos os cursos.|[2,*] A sua conta está pronta: tem :days dias de acesso gratuito a todos os cursos.',
    install_app: 'Instalar a aplicação', offline_courses: 'Cursos offline', back_online: 'Versão online',
    offline_needs_js: 'Ative o JavaScript para usar os seus cursos offline.',
    pwa_description: 'Siga os seus cursos do Instituto Universitário ZTF, mesmo sem ligação.',
    preview_cta_title: 'Quer ir mais longe?', preview_cta_help: 'Inscreva-se para aceder a todas as aulas e obter o certificado.',
    review_requires_completion: 'Conclua o curso para deixar uma avaliação.',
    no_enrollments: 'Ainda não está inscrito em nenhum curso.',
    minutes_short: ':count min', hours_short: ':count h', hours_minutes_short: ':hours h :minutes min',
    byte_units: ['B', 'KB', 'MB', 'GB', 'TB'], decimal_separator: ',',
    role_student: 'Estudante', role_instructor: 'Instrutor', role_admin: 'Administrador', role_super_admin: 'Superadministrador',
    instructor_status_none: 'Nenhum', instructor_status_pending: 'Pendente', instructor_status_confirmed: 'Confirmado', instructor_status_rejected: 'Recusado',
    application_status_pending: 'Pendente', application_status_approved: 'Aceite', application_status_rejected: 'Recusada',
    audience_all: 'Todos', audience_students: 'Estudantes', audience_instructors: 'Instrutores',
    js: {
        byte_units: ['B', 'KB', 'MB', 'GB'],
        seconds_short: ':count s', minutes_short: ':count min', hours_minutes_short: ':hours h :minutes min',
        offline_banner: 'Está offline.', offline_open: 'Abrir os meus cursos offline',
        syncing: 'A sincronizar :count ação(ões) feita(s) offline…', synced: ':count ação(ões) sincronizada(s)',
        offline_download: 'Baixar para usar offline', offline_available: 'Disponível offline',
        offline_remove: 'Eliminar', offline_remove_confirm: 'Confirmar a eliminação', offline_update: 'Atualizar',
        offline_unsupported: 'O seu navegador não suporta o modo offline. Use o Chrome, Edge, Firefox ou Safari recentes.',
        offline_need_network: 'É necessária ligação à Internet para baixar.',
        offline_preparing: 'A preparar…', offline_progress: ':pct % — :loaded / :total (ficheiro :file/:files)',
        offline_done: 'Curso disponível offline', offline_cancelled: 'Transferência cancelada.',
        offline_failed: 'A transferência falhou.', offline_quota: 'Espaço insuficiente: são necessários :needed, restam :available.',
        offline_courses: 'Cursos offline', offline_empty_title: 'Nenhum curso baixado',
        offline_empty_help: 'Com ligação, abra «Meus cursos» e toque em «Baixar para usar offline». Depois poderá seguir o curso sem Internet.',
        offline_home_help: 'Estes cursos estão guardados neste dispositivo. O seu progresso será enviado automaticamente quando voltar a ter ligação.',
        go_my_courses: 'Ir para os meus cursos', online: 'Online', offline: 'Offline',
        pending_sync: ':count a aguardar sincronização', progress_pct: ':pct % concluído', open: 'Abrir',
        module: 'Módulo', previous: 'Anterior', next: 'Seguinte', resources: 'Recursos',
        online_only: 'online', course_empty: 'Este curso não tem aulas.',
        youtube_needs_network: 'Os vídeos do YouTube precisam de ligação à Internet.',
        video_needs_network: 'Este vídeo precisa de ligação à Internet.',
        assignment_online_only: 'Os trabalhos são entregues online. Prepare o seu trabalho e envie-o quando voltar a ter ligação.',
        offline_quiz_help: 'Offline, as suas respostas são guardadas e corrigidas quando voltar a ligar-se (aprovação com :score %).',
        quiz_saved_offline: 'Respostas guardadas: serão corrigidas assim que voltar a ter ligação.',
        saved_offline: 'Guardado no dispositivo: será sincronizado quando voltar a ter ligação.',
        next_available: 'Próxima aula desbloqueada.', lesson_completed: 'Aula concluída!',
        mark_complete: 'Marcar como concluída', completed: 'Concluído',
        watched_percent: 'Visto: :percent %', auto_complete_hint: 'concluída automaticamente no fim do vídeo',
        certificate_ready: 'Curso concluído! O seu certificado está pronto.', resumed_at: 'Retomado em :time',
        next_in: 'Próxima aula em :seconds s…', go_now: 'Ir agora', cancel: 'Cancelar',
        youtube_unreachable: 'Não foi possível carregar o vídeo do YouTube. Verifique a sua ligação.',
        timed_quiz_needs_network: 'Um questionário com tempo precisa de ligação à Internet.',
        time_up: 'O tempo acabou: a enviar as suas respostas.',
        unanswered_confirm: ':count pergunta(s) sem resposta. Clique novamente em «Enviar» para enviar assim mesmo.',
        sending: 'A enviar…', submit_answers: 'Enviar as minhas respostas', error: 'Ocorreu um erro. Tente novamente.',
        correct: 'Certa', incorrect: 'Errada', retry: 'Tentar novamente',
        score_line: 'Pontuação: :score % (:correct/:total)',
        pause: 'Pausa', resume: 'Retomar', upload_eta: 'Tempo restante ≈ :time',
        upload_resuming: 'A retomar o envio a :pct %.', upload_retry_hint: 'escolha o mesmo ficheiro de novo para retomar.',
        upload_bad_extension: 'Formato não aceite. Use MP4, WebM ou MOV.', upload_too_large: 'Ficheiro demasiado grande (máximo :max MB).',
        youtube_invalid: 'Link do YouTube inválido.', option: 'Opção', correct_answer: 'Resposta certa', delete: 'Eliminar',
        quiz_need_correct: 'Assinale pelo menos uma resposta certa.', quiz_need_two_options: 'Uma pergunta precisa de pelo menos duas opções.',
    },
};
