// Chinese (Simplified) — auth, dashboard, courses, navigation, messages
module.exports = {
    auth: {
        failed: '账号或密码不正确。',
        password: '密码不正确。',
        throttle: '登录尝试次数过多，请在 :seconds 秒后重试。',
        login: '登录', register: '注册', logout: '退出登录',
        email: '电子邮箱', password_label: '密码', confirm_password: '确认密码',
        remember_me: '记住我', forgot_password: '忘记密码？', reset_password: '重置密码',
        send_reset_link: '发送重置链接', name: '姓名',
        already_registered: '已有账号？', no_account: '还没有账号？',
        verify_email: '验证电子邮箱',
        verify_notice: '感谢注册！开始之前，请先验证您的电子邮箱。',
        verify_sent: '新的验证链接已发送到您的邮箱。',
        verify_resend: '重新发送验证邮件', country: '国家',
        trial_notice: '立即开始 :days 天免费试用，无需信用卡。',
        register_as: '创建免费账号', admin_login: '管理员登录',
        admin_only: '此区域仅限管理员访问。',
        welcome_back: '欢迎回来', sign_in_to_continue: '登录后继续学习',
        join_acadexa: '加入 ACADEXA', create_account: '创建免费账号', full_name: '姓名',
        have_account: '已有账号？', register_here: '在此登录',
    },
    dashboard: {
        welcome: '欢迎回来', total_courses: '课程', instructors: '讲师', my_courses: '我的课程',
        certificates: '证书', announcements: '公告', quick_links: '快捷链接', browse_courses: '浏览课程',
        edit_profile: '编辑资料', enrolled_courses: '已报名课程', completed_courses: '已完成课程',
        in_progress: '学习中', trial_status: '试用状态', trial_active: '有效 — 剩余 :days 天',
        trial_expired: '已过期', continue: '继续', view_all: '查看全部',
        no_courses: '您还没有报名任何课程。',
        no_certificates: '还没有证书。完成一门课程即可获得！',
        no_announcements: '目前没有公告。', download_certificate: '下载证书', verify: '验证',
        progress: '进度', instructor_dashboard: '讲师面板', total_students: '学员',
        my_courses_count: '我的课程', published_courses: '已发布', avg_rating: '平均评分',
        recent_reviews: '最新评价', pending_review: '等待审核', create_course: '创建课程',
        view_courses: '查看我的课程', earnings: '收入', students_enrolled: ':count 名学员已报名',
    },
    courses: {
        by: '讲师：', featured: '精选', latest: '最新', courses: '课程', view_all: '查看全部',
        view_course: '查看课程', newest: '最新', catalog: '课程目录', filters: '筛选',
        courses_found: '门课程', explore_courses: '探索课程', browse_by: '按',
        category: '分类浏览', enroll: '立即报名', enrolled: '已报名', already_enrolled: '您已报名。',
        free: '免费', level: '级别', duration: '时长', language: '语言', students: '学员',
        rating: '评分', reviews: '评价', curriculum: '课程大纲', what_you_learn: '您将学到',
        requirements: '先修要求', description: '简介', about_instructor: '关于讲师',
        related_courses: '相关课程', write_review: '撰写评价', your_review: '您的评价',
        submit_review: '提交评价', filter: '筛选课程', sort_by: '排序方式', sort_newest: '最新',
        sort_popular: '最受欢迎', sort_rating: '评分最高', all_categories: '全部分类',
        all_levels: '全部级别', free_only: '仅免费', price: '价格', module: '模块', lesson: '课时',
        quiz: '测验', assignment: '作业', video: '视频', text: '文章', mark_complete: '标记为已完成',
        completed: '已完成', progress: '进度', next_lesson: '下一课时', prev_lesson: '上一课时',
        course_completed: '恭喜！您已完成本课程。', get_certificate: '领取证书',
        hours: '小时', free_preview: '免费试看', locked: '已锁定 — 报名后可学习',
        no_video: '本课时暂无视频。', submit_quiz: '提交测验',
        quiz_passed: '测验通过！得分：:score%', quiz_failed: '测验未通过。得分：:score%。请再试一次。',
        question: '题目', your_score: '上次得分', attempt_again: '再试一次',
        comments: '问答', add_comment: '提问', reply: '回复', post_comment: '发布',
        download_attachment: '下载附件', add_to_wishlist: '加入收藏', remove_from_wishlist: '取消收藏',
        popular: '最受欢迎', top_rated: '评分最高', price_low: '价格从低到高',
        continue_learning: '继续学习', enroll_now: '立即报名', no_courses_found: '未找到课程。',
        student_reviews: '学员评价', try_different_filters: '请尝试调整筛选条件或搜索词。',
    },
    navigation: {
        home: '首页', courses: '课程', categories: '分类', my_courses: '我的课程', dashboard: '面板',
        profile: '个人资料', wishlist: '收藏', certificates: '证书', subscription: '订阅',
        logout: '退出登录', login: '登录', register: '注册', become_instructor: '成为讲师',
        contact: '联系我们', about: '关于', privacy: '隐私政策', terms: '服务条款',
        admin_panel: '管理后台', instructor_portal: '讲师空间', search: '搜索',
        quick_links: '快捷链接', support: '支持', contact_us: '联系我们', notifications: '通知',
        no_notifications: '没有新通知', start_free: '免费开始',
    },
    messages: {
        welcome: '欢迎来到 ACADEXA', learn_grow: '学习、成长、实现目标',
        hero_subtitle: '加入 ZTF 大学学院的众多学员。学习一流课程，获得证书，推动职业发展。',
        get_started: '免费开始', browse_courses: '浏览课程', featured_courses: '精选课程',
        latest_courses: '最新课程', view_all: '查看全部', categories: '分类', why_acadexa: '为什么选择 ACADEXA？',
        enroll_now: '立即报名', start_learning: '开始学习', continue_learning: '继续学习',
        free: '免费', all_levels: '全部级别', beginner: '初级', intermediate: '中级', advanced: '高级',
        students: '名学员', courses: '门课程', instructors: '位讲师', certificates_issued: '份证书已颁发',
        trial_active: '试用中', trial_expires: '试用将于 :date 到期',
        trial_expired: '您的试用期已结束。请订阅以继续学习。', upgrade: '立即订阅',
        become_instructor: '成为讲师', teach_world: '面向世界授课', no_courses: '未找到课程。',
        contact_us: '联系我们', send_message: '发送消息', name: '姓名', email: '电子邮箱', phone: '电话',
        subject: '主题', message: '留言', message_sent: '您的留言已发送，我们会尽快回复。',
        search_placeholder: '搜索课程、主题...', no_results: '未找到与“:query”相关的结果',
        certificate_verified: '证书已验证', certificate_not_found: '未找到证书',
        verify_certificate: '验证证书', enter_code: '输入证书编号',
        payment_coming_soon: '支付与盈利 — 即将推出', contact_support: '联系客服',
        language_changed: '语言已切换。', profile_updated: '资料已更新。',
        password_changed: '密码已修改。',
        account_deactivated: '您的账号已被停用，请联系客服。',
        already_applied: '您已申请成为讲师。', already_enrolled: '您已报名本课程。',
        application_submitted: '您的申请已提交，我们会尽快回复。',
        certificate_issued: '恭喜！您已完成课程，证书已生成。',
        comment_posted: '您的问题已发布。', contact_sent: '您的留言已发送，我们会尽快回复。',
        course_deleted: '课程已删除。', course_submitted: '课程已提交审核，我们会通知您审核结果。',
        course_updated: '课程已更新。', enrolled_success: '报名成功，祝您学习愉快！',
        quiz_failed: '尚未通过。请复习本课时后再试。', quiz_passed: '太棒了，您通过了测验！',
        review_submitted: '感谢您的评价。', wishlist_added: '已加入收藏。', wishlist_removed: '已取消收藏。',
        wrong_password: '当前密码不正确。',
    },
};
