// Chinese (Simplified) — security and validation groups
module.exports = {
    security: {
        '2fa_title': '双重验证（2FA）',
        '2fa_intro': '保护您的管理员账号：除了密码，还需要输入手机生成的 6 位验证码。',
        '2fa_step1': '安装身份验证器应用（Google Authenticator、Microsoft Authenticator、Authy…）。',
        '2fa_step2': '扫描下方二维码（或手动输入密钥）。',
        '2fa_step3': '输入应用显示的验证码以确认。',
        '2fa_active_since': '双重验证自 :date 起已启用。',
        '2fa_disable_help': '如需停用，请输入密码和应用中的验证码确认。',
        '2fa_challenge_help': '请输入身份验证器应用显示的 6 位验证码。',
        manual_key: '手动输入的密钥', enable: '启用', disable: '停用', verify: '验证', password: '密码',
        enabled: '双重验证已启用。', disabled: '双重验证已停用。',
        invalid_code: '验证码无效或已过期。', invalid_credentials: '密码或验证码不正确。',
        reset_2fa: '重置双重验证', confirm_reset_2fa: '重置此账号的双重验证？',
        reset_done: '双重验证已重置。',
        use_admin_login: '此账号已启用双重验证：请从管理后台登录。',
        my_security: '账号安全',
        banned: '此账号已被封禁。如您认为有误，请联系客服。',
        banned_badge: '已封禁', banned_since: '自 :date 起封禁', ban_reason: '原因（可选）',
        confirm_ban: '封禁此用户？其登录状态将立即失效。', unban: '解除封禁',
        user_banned: '用户已被封禁并退出登录。', user_unbanned: '已解除封禁。',
        cannot_edit_self: '不能对自己的账号执行此操作。',
        no_permission: '您无权访问管理后台的此栏目。',
        role_permissions: '角色与权限', save_permissions: '保存',
        permissions_help: '适用于管理员：允许访问的栏目。不勾选 = 全部权限。',
        permissions_saved: '角色与权限已保存。',
        perm_users: '用户', perm_courses: '课程', perm_categories: '分类', perm_applications: '申请',
        perm_announcements: '公告', perm_cms: '页面', perm_reviews: '评价', perm_certificates: '证书',
        perm_contacts: '联系留言', perm_translations: '翻译', perm_settings: '设置',
        perm_logs: '操作日志', perm_reports: '报表',
        platform: '平台', allow_registration: '开放注册',
        require_email_verification: '要求验证电子邮箱',
        maintenance_mode: '维护模式（仅管理员可访问网站）',
        email_verification_help: '请先在 .env 文件中配置邮件发送（SMTP），再启用邮箱验证。',
        registration_closed: '注册暂时关闭。',
        reports: '报表', total_students: '学员', active_30d: '活跃（30 天）', total_enrollments: '课程报名数',
        completion_rate: '完成率', last_12_months: '最近 12 个月', month: '月份',
        registrations: '新学员', enrollments: '报名', completions: '已完成课程', certificates: '证书',
        top_courses: '最热门课程',
        export_users: '用户（CSV）', export_enrollments: '报名（CSV）', export_certificates: '证书（CSV）',
    },
    validation: {
        accepted: '必须接受 :attribute。',
        active_url: ':attribute 必须是有效的网址。',
        after: ':attribute 必须是 :date 之后的日期。',
        after_or_equal: ':attribute 必须是 :date 或之后的日期。',
        alpha: ':attribute 只能包含字母。',
        alpha_dash: ':attribute 只能包含字母、数字、短横线和下划线。',
        alpha_num: ':attribute 只能包含字母和数字。',
        array: ':attribute 必须是列表。',
        before: ':attribute 必须是 :date 之前的日期。',
        before_or_equal: ':attribute 必须是 :date 或之前的日期。',
        between: {
            array: ':attribute 必须包含 :min 到 :max 项。',
            file: ':attribute 必须介于 :min 到 :max KB 之间。',
            numeric: ':attribute 必须介于 :min 到 :max 之间。',
            string: ':attribute 必须为 :min 到 :max 个字符。',
        },
        boolean: ':attribute 必须是“是”或“否”。',
        confirmed: '两次输入的 :attribute 不一致。',
        current_password: '密码不正确。',
        date: ':attribute 必须是有效的日期。',
        date_format: ':attribute 必须符合 :format 格式。',
        different: ':attribute 和 :other 必须不同。',
        digits: ':attribute 必须是 :digits 位数字。',
        digits_between: ':attribute 必须是 :min 到 :max 位数字。',
        email: ':attribute 必须是有效的电子邮箱地址。',
        ends_with: ':attribute 必须以下列之一结尾：:values。',
        enum: '所选的 :attribute 无效。',
        exists: '所选的 :attribute 无效。',
        extensions: ':attribute 的扩展名必须是以下之一：:values。',
        file: ':attribute 必须是文件。',
        filled: ':attribute 不能为空。',
        gt: {
            array: ':attribute 必须多于 :value 项。',
            file: ':attribute 必须大于 :value KB。',
            numeric: ':attribute 必须大于 :value。',
            string: ':attribute 必须多于 :value 个字符。',
        },
        gte: {
            array: ':attribute 至少要有 :value 项。',
            file: ':attribute 至少为 :value KB。',
            numeric: ':attribute 必须大于或等于 :value。',
            string: ':attribute 至少为 :value 个字符。',
        },
        image: ':attribute 必须是图片。',
        in: '所选的 :attribute 无效。',
        integer: ':attribute 必须是整数。',
        ip: ':attribute 必须是有效的 IP 地址。',
        json: ':attribute 必须是有效的 JSON 字符串。',
        lowercase: ':attribute 必须为小写。',
        lt: {
            array: ':attribute 必须少于 :value 项。',
            file: ':attribute 必须小于 :value KB。',
            numeric: ':attribute 必须小于 :value。',
            string: ':attribute 必须少于 :value 个字符。',
        },
        lte: {
            array: ':attribute 不能多于 :value 项。',
            file: ':attribute 最多为 :value KB。',
            numeric: ':attribute 必须小于或等于 :value。',
            string: ':attribute 最多为 :value 个字符。',
        },
        max: {
            array: ':attribute 不能多于 :max 项。',
            file: ':attribute 不能大于 :max KB。',
            numeric: ':attribute 不能大于 :max。',
            string: ':attribute 不能超过 :max 个字符。',
        },
        mimes: ':attribute 必须是以下类型的文件：:values。',
        mimetypes: ':attribute 必须是以下类型的文件：:values。',
        min: {
            array: ':attribute 至少要有 :min 项。',
            file: ':attribute 至少为 :min KB。',
            numeric: ':attribute 至少为 :min。',
            string: ':attribute 至少为 :min 个字符。',
        },
        not_in: '所选的 :attribute 无效。',
        numeric: ':attribute 必须是数字。',
        password: {
            letters: ':attribute 至少要包含一个字母。',
            mixed: ':attribute 至少要包含一个大写字母和一个小写字母。',
            numbers: ':attribute 至少要包含一个数字。',
            symbols: ':attribute 至少要包含一个符号。',
            uncompromised: '该 :attribute 曾出现在数据泄露中，请换一个。',
        },
        present: '必须提供 :attribute。',
        prohibited: '不允许填写 :attribute。',
        regex: ':attribute 格式不正确。',
        required: ':attribute 为必填项。',
        required_if: '当 :other 为 :value 时，:attribute 为必填项。',
        required_with: '填写 :values 时，:attribute 为必填项。',
        required_without: '未填写 :values 时，:attribute 为必填项。',
        same: ':attribute 必须与 :other 一致。',
        size: {
            array: ':attribute 必须包含 :size 项。',
            file: ':attribute 必须为 :size KB。',
            numeric: ':attribute 必须为 :size。',
            string: ':attribute 必须为 :size 个字符。',
        },
        starts_with: ':attribute 必须以下列之一开头：:values。',
        string: ':attribute 必须是文本。',
        timezone: ':attribute 必须是有效的时区。',
        unique: ':attribute 已被使用。',
        uploaded: ':attribute 上传失败。',
        uppercase: ':attribute 必须为大写。',
        url: ':attribute 必须是有效的网址。',
        uuid: ':attribute 必须是有效的 UUID。',
        attributes: {
            name: '姓名', email: '电子邮箱', password: '密码', password_confirmation: '确认密码',
            current_password: '当前密码', country: '国家', bio: '个人简介', title: '标题',
            description: '简介', content: '内容', body: '消息', subject: '主题', message: '留言',
            phone: '电话', category_id: '分类', level: '级别', language: '语言', price: '价格',
            duration_hours: '学时', duration_minutes: '时长', thumbnail: '封面图片', file: '文件',
            rating: '评分', comment: '评论', score: '分数', feedback: '评语', code: '验证码',
            slug: '网址', audience: '受众', expertise: '专业领域', credentials: '学历与资质',
            reason: '原因', days: '天数', question: '题目', options: '选项', correct: '正确答案',
            youtube_url: 'YouTube 链接', vimeo_url: 'Vimeo 链接', external_url: '视频链接', hero_image: '图片',
        },
    },
};
