// Chinese (Simplified) — lms group
module.exports = {
    actions: '操作', add: '添加', all: '全部', back: '返回', cancel: '取消', close: '关闭',
    delete: '删除', details: '详情', download: '下载', edit: '编辑', filter: '筛选',
    loading: '加载中…', more: '更多', none: '无', post: '发布', previous: '上一个', next: '下一个',
    save: '保存', send: '发送', see_all: '查看全部', view: '查看', unlimited: '不限',
    unauthorized: '无权执行此操作。', order_saved: '新顺序已保存。', confirm_delete: '确认删除？',
    name: '名称', title: '标题', description: '简介', category: '分类', level: '级别',
    price: '价格', price_help: '在线支付即将推出。0 = 免费。', hours: '小时',
    status: '状态', message: '消息', subject: '主题', file: '文件', course: '课程',
    student: '学员', students: '学员', instructor: '讲师', lesson: '课时', lessons: '课时',
    module: '模块', modules: '模块', progress: '进度', rating: '评分', stats: '统计',
    certificate: '证书', preview: '试看', tips: '提示', my_courses: '我的课程',
    lessons_count: '{0} 暂无课时|[1,*] :count 个课时',
    modules_count: '{0} 暂无模块|[1,*] :count 个模块',
    questions_count: '{0} 暂无题目|[1,*] :count 道题',
    status_draft: '草稿', status_pending: '审核中', status_published: '已发布', status_rejected: '已驳回', status_unpublished: '已下架',
    type_video: '视频', type_text: '图文', type_quiz: '测验', type_assignment: '作业',
    source_upload: '视频文件', source_youtube: 'YouTube', source_vimeo: 'Vimeo', source_url: '直链',
    new_course: '新建课程',
    new_course_help: '先填写基本信息。然后构建课程大纲：先建模块（含学时），再建课时。',
    step_info: '基本信息', step_modules: '模块与学时', step_lessons: '课时与内容', step_submit: '提交审核',
    course_language: '课程主要语言', course_language_help: '以后可以添加其他语言的翻译。',
    course_hours: '课程总学时', course_hours_help: '培训总小时数（例如 40 小时）。',
    course_title_placeholder: '例如：会计学原理入门',
    thumbnail: '封面图片', thumbnail_help: 'JPG、PNG 或 WebP，建议 1280×720，最大 4 MB。',
    create_and_continue: '创建并构建大纲', course_created_next_step: '课程已创建。现在添加模块及其学时。',
    edit_course: '编辑课程', tab_info: '基本信息', tab_curriculum: '课程大纲',
    view_public_page: '公开页面', admin_feedback: '管理员反馈',
    course_locked_pending: '本课程正在审核中，审核结果出来前无法修改。',
    sequential: '顺序学习', sequential_help: '完成上一课时后才能解锁下一课时。',
    optional_translation: '可选翻译：如果课程只提供主要语言版本，请留空。',
    what_you_learn: '学员将学到', requirements: '先修要求', one_per_line: '每行一项',
    course_delete_forbidden: '已发布或已有学员报名的课程无法删除。',
    delete_course: '删除此课程', confirm_delete_course: '确定永久删除此课程及其所有模块、课时和视频吗？',
    no_courses_yet: '您还没有创建任何课程。', students_and_stats: '学员与统计',
    drag_help: '拖放模块和课时即可调整顺序（也可以在模块之间移动）。',
    drag: '移动', add_module: '添加模块', edit_module: '编辑模块', add_first_module: '添加第一个模块',
    no_modules_title: '还没有模块', no_modules_help: '课程由多个模块（各自有学时）组成，每个模块又由多个课时组成。',
    module_hours: '模块学时', module_title: '模块标题', module_description: '模块简介 / 学习目标',
    module_description_placeholder: '学习目标、目标能力…',
    module_created: '模块已添加。', module_updated: '模块已更新。', module_deleted: '模块已删除。',
    confirm_delete_module: '删除此模块及其所有课时（包括视频）？',
    content_minutes: ':minutes 分钟内容', content_duration: '内容时长（视频、阅读）：:duration',
    hours_breakdown: '学时分配', modules_total: '模块合计',
    hours_over: '模块学时之和超过了课程总学时。',
    hours_remaining: '还有 :hours 需要分配给各模块。', hours_match: '模块学时与课程总学时一致。',
    before_submit: '提交前检查',
    check_info: '主要语言的标题和简介', check_hours: '已填写课程及每个模块的学时',
    check_modules: '至少有一个模块，且每个模块都有课时', check_videos: '每个视频课时都有视频',
    check_quizzes: '每个测验至少有一道题', check_thumbnail: '封面图片',
    submit_review: '提交审核', submit_incomplete: '课程尚未完成：请查看“提交前检查”清单。',
    pending_review_help: '您的课程正在审核中，审核结果将通过邮件通知您。',
    add_lesson: '添加课时', add_lesson_help: '下一步再添加内容（视频、图文、测验…）。',
    create_and_edit: '创建并编辑', edit_lesson: '编辑课时', lesson_title: '课时标题', lesson_type: '课时类型',
    lesson_content: '课时内容', lesson_content_placeholder: '课时正文、笔记、链接…（视频课时可不填）',
    lesson_created: '课时已创建，请添加内容。', lesson_saved: '课时已保存。', lesson_deleted: '课时已删除。',
    lesson_incomplete: '待完善', save_lesson: '保存课时', back_to_curriculum: '课程大纲',
    confirm_delete_lesson: '删除此课时？', delete_lesson: '删除课时',
    duration_minutes: '时长', free_preview: '免费试看', free_preview_help: '未报名也可在课程页面观看',
    downloadable: '可离线学习', downloadable_help: '学员可在应用中下载此课时',
    video: '视频', upload_video: '上传视频', drop_video: '将视频拖到此处，或点击选择文件',
    video_formats: '格式：:formats — 最大 :max', upload_resumable_help: '如果网络中断，重新选择同一文件即可从中断处继续上传。',
    replace_video_help: '如需替换视频，直接上传新文件即可。',
    delete_video: '删除视频', confirm_delete_video: '确定永久删除此视频吗？',
    video_uploaded: '视频上传成功。', video_deleted: '视频已删除。',
    upload_too_large: '文件过大（最大 :max MB）。', upload_bad_extension: '不支持的格式。请使用 MP4、WebM 或 MOV。',
    upload_not_video: '上传的文件不是有效的视频。', upload_missing_chunk: '文件缺少一部分（第 :index 块）。请重新上传。',
    youtube_url: 'YouTube 视频链接', youtube_invalid: 'YouTube 链接无效。',
    youtube_help: '视频直接在 ACADEXXA 内播放，无需离开平台。提示：在 YouTube 上将可见性设为“不公开列出”。',
    vimeo_url: 'Vimeo 链接', vimeo_invalid: 'Vimeo 链接无效。',
    external_url: '视频文件直链', external_url_help: '托管在其他位置的 .mp4 文件地址。',
    assignment_instructions: '作业要求', grading: '评分', max_score: '满分', pass_score: '及格分',
    assignment_completion_help: '当您给出的分数不低于及格分时，本课时即视为完成。',
    tip_video: '请上传 MP4（H.264）格式的视频：所有设备都能播放，并可离线观看。',
    tip_youtube: 'YouTube 视频可在平台内播放，但无法下载离线观看。',
    tip_offline: '将 PDF 添加为学习资料：学员没有网络也能阅读。',
    tip_completion: '学员实际观看至少 90% 后，视频课时才算完成。',
    resources: '学习资料', resources_help: '讲义、练习、幻灯片…学员可下载（也可离线使用）。',
    resource_title: '标题', resource_title_placeholder: '例如：课程讲义（PDF）',
    resource_added: '资料已添加。', resource_deleted: '资料已删除。', confirm_delete_resource: '删除此资料？',
    quiz: '测验', passing_score: '及格分数', max_attempts: '最多尝试次数', time_limit: '时间限制',
    shuffle_questions: '随机打乱题目顺序', show_correct_answers: '批改后显示正确答案',
    save_settings: '保存设置', quiz_settings_saved: '测验设置已保存。',
    timed_quiz_offline_note: '限时测验只能在线完成。',
    add_question: '添加题目', question: '题目', answer_type: '答案类型',
    single_answer: '单选', multiple_answers: '多选', options: '选项',
    tick_correct: '勾选正确答案', add_option: '添加选项',
    question_added: '题目已添加。', question_updated: '题目已更新。', question_deleted: '题目已删除。',
    confirm_delete_question: '删除此题？', no_questions: '还没有题目，请至少添加一道。',
    save_to_create_quiz: '请先保存课时以创建测验。',
    quiz_need_correct: '请至少勾选一个正确答案。', quiz_need_two_options: '每道题至少需要两个选项。',
    quiz_single_one_correct: '单选题只能有一个正确答案。',
    lesson_x_of_y: '第 :x 课时，共 :y 课时', course_content: '课程内容', offline_mode: '离线模式',
    offline_mode_help: '下载课程后可在无网络时学习，恢复联网后进度会自动同步。',
    contact_instructor: '联系讲师', course_page: '课程页面', course_empty: '本课程还没有课时。',
    video_unavailable: '本课时的视频暂不可用。', completed: '已完成', mark_complete: '标记为已完成',
    watched_percent: '已观看：:percent%', auto_complete_hint: '视频播放结束后自动完成',
    watch_more: '请至少观看视频的 :percent% 才能完成本课时。',
    quiz_completes_lesson: '通过测验即可完成本课时。', assignment_completes_lesson: '作业评分合格后即完成。',
    complete_via_assessment: '通过考核即可完成本课时。', lesson_completed: '课时已完成！',
    lesson_locked: '请先完成前面的课时以解锁本课时。',
    tab_lesson: '课时', qa: '问答', ask_question: '向讲师提问',
    ask_question_placeholder: '关于本课时的问题…', no_questions_yet: '还没有提问，来做第一个吧！',
    lesson_navigation: '课时导航', get_certificate: '领取我的证书', back_to_course: '返回课程',
    quiz_not_ready: '此测验尚未准备好。',
    pass_at: ':score% 及格', attempts_unlimited: '不限次数',
    attempts_left: '{0} 已无剩余次数|[1,*] 剩余 :count 次',
    quiz_passed_best: '测验已通过 — 最高分：:score%', quiz_last_score: '上次得分：:score%（:pass% 及格）',
    quiz_no_attempts_left: '您已用完本测验的所有尝试次数。',
    quiz_not_started: '计时器未启动，请刷新页面。',
    quiz_timed_out: '时间已到：本次作答不计为通过。',
    timed_quiz_intro: '本测验限时：点击“开始”后您有 :minutes 分钟。',
    start_quiz: '开始', several_answers: '多个答案', submit_answers: '提交答案',
    your_work: '您的作业', your_grade: '您的成绩', assignment_passed: '合格', assignment_failed: '需改进',
    assignment_waiting: '已于 :date 提交 — 等待批改。', view_my_submission: '查看我的提交',
    resubmit: '提交新版本', your_answer: '您的回答', attach_file: '附加文件',
    submit_assignment: '提交作业', assignment_submitted: '作业已提交，已通知讲师。',
    assignment_already_passed: '此作业已合格。', assignment_empty: '请填写回答或附加文件。',
    pass_mark_is: ':score 分及格',
    assignments: '作业', to_grade: '待批改', graded: '已批改', all_courses: '全部课程',
    submitted_on: '提交时间', grade: '批改', grade_submission: '批改作业', no_submissions: '这里没有作业。',
    score: '分数', feedback: '评语', feedback_placeholder: '优点、需要改进的地方…',
    save_grade: '保存成绩', grade_notify_help: '系统会通知学员；若分数达到及格线，本课时即完成。',
    graded_by_on: '由 :name 于 :date 批改', submission_graded: '成绩已保存，已通知学员。',
    enrolled: '报名人数', completion_rate: '完成率', avg_progress: '平均进度', avg_quiz: '测验平均分',
    search_student: '姓名或邮箱', not_started: '未开始', in_progress: '学习中',
    export_csv: '导出（CSV）', last_lesson: '最近课时', enrolled_on: '报名时间', completed_on: '完成时间',
    no_students: '暂无学员。', completion_by_lesson: '各课时完成情况',
    completion_by_lesson_help: '完成每个课时的学员比例：找出学员流失的位置。',
    student_progress: '学员进度', best_score: '最高分', send_message: '发送消息',
    announcements: '公告', new_announcement: '新公告',
    announcement_help: '发送给本课程的所有学员（站内通知 + 邮件）。', publish_announcement: '发布公告',
    announcement_sent: '{0} 公告已发布（暂无学员）。|[1,*] 公告已发送给 :count 名学员。',
    announcement_deleted: '公告已删除。', no_announcements: '暂无公告。',
    unanswered: '未回复', your_reply: '您的回复…', reply: '回复', reply_posted: '回复已发布。',
    no_questions_to_answer: '没有待回复的问题，做得好！',
    todo_submissions: '[1,*] :count 份作业待批改', todo_submissions_help: '学员正在等待成绩。',
    todo_questions: '[1,*] :count 个问题待回复', todo_questions_help: '请在问答页面回复。',
    messages: '消息', new_message: '新消息', new_message_help: '给您所学课程的讲师写信。',
    no_messages: '暂无对话。', message_sent: '消息已发送。',
    mark_all_read: '全部标为已读', notifications_all_read: '所有通知已标为已读。',
    email_notifications: '同时通过邮件接收通知', preferences_saved: '偏好设置已保存。',
    mail_greeting: ':name，您好：', mail_salutation: 'ACADEXXA 团队 — ZTF 大学学院', notif_open: '打开',
    notif_feedback: '评语：:feedback',
    notif_certificate_subject: '您的证书已生成', notif_certificate_line: '恭喜！您已完成“:course”。',
    notif_certificate_code: '验证编号：:code',
    notif_course_approved_subject: '您的课程已发布', notif_course_approved_line: '您的课程“:course”已通过审核并上线。',
    notif_course_rejected_subject: '您的课程需要修改', notif_course_rejected_line: '您的课程“:course”未通过审核。请查看反馈后重新提交。',
    notif_course_submitted_subject: '待审核课程', notif_course_submitted_line: ':instructor 提交了“:course”，等待审核。',
    notif_application_approved_subject: '申请已通过', notif_application_approved_line: '您现在是 ACADEXXA 的讲师了。快来创建第一门课程吧！',
    notif_application_rejected_subject: '讲师申请', notif_application_rejected_line: '您的申请暂未通过。',
    notif_assignment_submitted_subject: '有新作业待批改', notif_assignment_submitted_line: ':student 提交了作业“:lesson”。',
    notif_assignment_graded_subject: '您的作业已批改', notif_assignment_graded_line: '作业“:lesson”：:score / :max。',
    notif_question_subject: '学员有新问题', notif_question_line: ':name 在“:lesson”中提了一个问题。',
    notif_reply_subject: '您的问题有了回复', notif_reply_line: ':name 回复了您在“:lesson”中的问题。',
    notif_announcement_subject: '公告 — :course',
    notif_message_subject: ':name 给您发来新消息', notif_message_line: ':name 给您写信：“:subject”。',
    notif_trial_subject: '您的试用即将到期',
    notif_trial_line: '[1,*] 您的免费访问还剩 :days 天。',
    notif_welcome_subject: '欢迎来到 :site！', notif_browse_courses: '浏览课程',
    notif_welcome_line: '[1,*] 您的账号已创建：您可免费学习所有课程 :days 天。',
    install_app: '安装应用', offline_courses: '离线课程', back_online: '在线版本',
    offline_needs_js: '请启用 JavaScript 以使用离线课程。',
    pwa_description: '随时学习 ZTF 大学学院的课程，没有网络也可以。',
    preview_cta_title: '想了解更多？', preview_cta_help: '报名即可学习全部课时并获得证书。',
    review_requires_completion: '完成课程后才能发表评价。',
    no_enrollments: '您还没有报名任何课程。',
    minutes_short: ':count 分钟', hours_short: ':count 小时', hours_minutes_short: ':hours 小时 :minutes 分钟',
    byte_units: ['B', 'KB', 'MB', 'GB', 'TB'], decimal_separator: '.',
    role_student: '学员', role_instructor: '讲师', role_admin: '管理员', role_super_admin: '超级管理员',
    instructor_status_none: '无', instructor_status_pending: '待审核', instructor_status_confirmed: '已认证', instructor_status_rejected: '已拒绝',
    application_status_pending: '待审核', application_status_approved: '已通过', application_status_rejected: '已拒绝',
    audience_all: '所有人', audience_students: '学员', audience_instructors: '讲师',
    js: {
        byte_units: ['B', 'KB', 'MB', 'GB'],
        seconds_short: ':count 秒', minutes_short: ':count 分钟', hours_minutes_short: ':hours 小时 :minutes 分钟',
        offline_banner: '您当前处于离线状态。', offline_open: '打开我的离线课程',
        syncing: '正在同步 :count 项离线操作…', synced: '已同步 :count 项操作',
        offline_download: '下载以离线学习', offline_available: '可离线学习',
        offline_remove: '删除', offline_remove_confirm: '确认删除', offline_update: '更新',
        offline_unsupported: '您的浏览器不支持离线模式。请使用较新版本的 Chrome、Edge、Firefox 或 Safari。',
        offline_need_network: '下载需要联网。',
        offline_preparing: '准备中…', offline_progress: ':pct% — :loaded / :total（文件 :file/:files）',
        offline_done: '课程已可离线学习', offline_cancelled: '下载已取消。',
        offline_failed: '下载失败。', offline_quota: '存储空间不足：需要 :needed，剩余 :available。',
        offline_courses: '离线课程', offline_empty_title: '没有已下载的课程',
        offline_empty_help: '联网时打开“我的课程”，点击“下载以离线学习”。之后没有网络也能学习。',
        offline_home_help: '这些课程保存在本设备上。恢复联网后，您的学习进度会自动上传。',
        go_my_courses: '前往我的课程', online: '在线', offline: '离线',
        pending_sync: ':count 项待同步', progress_pct: '已完成 :pct%', open: '打开',
        module: '模块', previous: '上一个', next: '下一个', resources: '学习资料',
        online_only: '需联网', course_empty: '本课程没有课时。',
        youtube_needs_network: 'YouTube 视频需要联网观看。',
        video_needs_network: '此视频需要联网观看。',
        assignment_online_only: '作业需要在线提交。请先准备好作业，联网后再提交。',
        offline_quiz_help: '离线时，您的答案会先保存，联网后再批改（:score% 及格）。',
        quiz_saved_offline: '答案已保存：恢复联网后将立即批改。',
        saved_offline: '已保存在本设备：恢复联网后会自动同步。',
        next_available: '下一课时已解锁。', lesson_completed: '课时已完成！',
        mark_complete: '标记为已完成', completed: '已完成',
        watched_percent: '已观看：:percent%', auto_complete_hint: '视频播放结束后自动完成',
        certificate_ready: '课程已完成！您的证书已生成。', resumed_at: '从 :time 继续播放',
        next_in: ':seconds 秒后进入下一课时…', go_now: '立即前往', cancel: '取消',
        youtube_unreachable: '无法加载 YouTube 视频，请检查网络连接。',
        timed_quiz_needs_network: '限时测验需要联网。',
        time_up: '时间到：正在提交您的答案。',
        unanswered_confirm: '还有 :count 道题未作答。再次点击“提交”即可直接提交。',
        sending: '提交中…', submit_answers: '提交答案', error: '出错了，请重试。',
        correct: '正确', incorrect: '错误', retry: '再试一次',
        score_line: '得分：:score%（:correct/:total）',
        pause: '暂停', resume: '继续', upload_eta: '剩余时间约 :time',
        upload_resuming: '从 :pct% 处继续上传。', upload_retry_hint: '重新选择同一文件即可继续。',
        upload_bad_extension: '不支持的格式。请使用 MP4、WebM 或 MOV。', upload_too_large: '文件过大（最大 :max MB）。',
        youtube_invalid: 'YouTube 链接无效。', option: '选项', correct_answer: '正确答案', delete: '删除',
        quiz_need_correct: '请至少勾选一个正确答案。', quiz_need_two_options: '每道题至少需要两个选项。',
    },
};
