// Builds resources/icons/sprite.svg: one <symbol> per icon actually used in the project,
// taken from the Bootstrap Icons SVG set (node_modules/bootstrap-icons).
// Run with `npm run icons` (also runs automatically before `npm run build`).
//
// Icon names are collected from:
//   <x-icon name="play-circle">          Blade component
//   icon('play-circle')                   JavaScript helper (resources/js/icons.js)
//   'bi-play-circle'                      icon names stored in PHP/JS data (models, config, notifications)
const fs = require('fs');
const path = require('path');

const BASE = path.join(__dirname, '..');
const ICONS_DIR = path.join(BASE, 'node_modules', 'bootstrap-icons', 'icons');
const OUT = path.join(BASE, 'resources', 'icons', 'sprite.svg');
const SCAN = ['resources/views', 'resources/js', 'app', 'config', 'database'];

function walk(dir) {
    if (!fs.existsSync(dir)) return [];
    return fs.readdirSync(dir, { withFileTypes: true }).flatMap(e =>
        e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]);
}

function collect() {
    const names = new Set();
    const optional = new Set();
    const patterns = [
        /<x-icon\b[^>]*?\sname="([a-z0-9-]+)"/g,
        /\bicon\(\s*['"]([a-z0-9-]+)['"]/g,
        /['"`\s]bi-([a-z0-9-]+)/g,
        // quoted names inside dynamic :name="..." expressions
        /:name="([^"]+)"/g,
    ];
    for (const dir of SCAN) {
        for (const file of walk(path.join(BASE, dir))) {
            if (!/\.(php|js|cjs)$/.test(file) || file.endsWith('sprite.svg')) continue;
            const src = fs.readFileSync(file, 'utf8');
            for (const re of patterns) {
                let m;
                while ((m = re.exec(src))) {
                    if (re.source.startsWith(':name')) {
                        // Dynamic expressions also contain other strings ('success', '-fill'…): keep only real icons.
                        for (const q of m[1].matchAll(/'([a-z0-9-]+)'/g)) optional.add(q[1].replace(/^bi-/, ''));
                    } else {
                        names.add(m[1]);
                    }
                }
            }
        }
    }
    return { names, optional };
}

function main() {
    if (!fs.existsSync(ICONS_DIR)) {
        console.error('bootstrap-icons is not installed: run `npm install`.');
        process.exit(1);
    }
    const available = new Set(fs.readdirSync(ICONS_DIR).filter(f => f.endsWith('.svg')).map(f => f.slice(0, -4)));
    const { names: used, optional } = collect();
    for (const name of optional) if (available.has(name)) used.add(name);

    // Filled variants are picked at runtime (e.g. star / star-fill): include them too.
    for (const name of [...used]) {
        if (available.has(`${name}-fill`)) used.add(`${name}-fill`);
    }

    // Tokens like "bi-" prefixes on CSS helpers are not icons; only keep real icon names,
    // but fail loudly on names that look intentional (used via <x-icon> or icon()).
    const missing = [];
    const symbols = [];
    for (const name of [...used].sort()) {
        if (!available.has(name)) {
            if (!/^(svg|icon|fill|\d.*)$/.test(name)) missing.push(name);
            continue;
        }
        const svg = fs.readFileSync(path.join(ICONS_DIR, `${name}.svg`), 'utf8');
        const viewBox = (svg.match(/viewBox="([^"]+)"/) || [, '0 0 16 16'])[1];
        const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s+/g, ' ').trim();
        symbols.push(`<symbol id="${name}" viewBox="${viewBox}">${inner}</symbol>`);
    }

    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT,
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n'
        + '<!-- Generated by scripts/build-icons.cjs from Bootstrap Icons (MIT). Do not edit by hand. -->\n'
        + symbols.join('\n') + '\n</svg>\n');

    console.log(`sprite.svg: ${symbols.length} icons`);
    if (missing.length) {
        console.warn('Unknown icon names (ignored): ' + missing.join(', '));
        if (process.argv.includes('--strict')) process.exit(1);
    }
}

main();
